### ISSUE TITLE
Support source file hirerarchy that doesn't start at top level.

### ISSUE THREAD

**Issue by Fuuzetsu** [tweag/rules_haskell#10]
Frequently libraries live under `src` or similar. As we are guessing module names from file paths, we can only translate  `<project-root>A/B/C.hs` right now. The way this is solved in cabal is simple: `hs-source-dirs`. Instead of using `srcs` as a flat list of files, we should take `(directory, files)` pairs instead. This way we can drop the `directory` prefix when needed.

Some alternative UI choices are possible.

**Comment by Fuuzetsu** [comment]
EDIT: Notably this is a problem because it doesn't let you put the `BUILD` file for `haskell_library` anywhere but inside `src`. This may be annoying if you want to keep single project in single BUILD file rather than have one per target.

**Comment by mboes** [comment]
Or have an equivalent of `hs-source-dirs`? We could define `strip_source_prefix` similar to `strip_include_prefix` in C/C++ rules: https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.strip_include_prefix. Java has `strip_resource_prefix` that works similarly.

**Comment by Fuuzetsu** [comment]
Right, that's what the solution was. It's not called `hs-source-dirs` but everything there is subject to change, UI was not exactly my greatest concern.
