### ISSUE TITLE
Support main files named something other than "Main.hs"

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#100]
I'd like to have a number of small tools in one directory and compile `haskell_binary`s for each of them. Currently, it seems the source file name must be Main.hs, otherwise it will fail to find the output:

```
[1 of 1] Compiling Main             ( hs-toxcore-c/tools/groupbot.hs, bazel-out/k8-fastbuild/bin/hs-toxcore-c/objects-groupbot-1.0.0/Main.o )
ERROR: /home/iphy/code/toktok-stack/hs-toxcore-c/BUILD:23:1: output 'hs-toxcore-c/objects-groupbot-1.0.0/groupbot.o' was not created
```

**Comment by Fuuzetsu** [comment]
Did you see mainis attribute?

**Comment by iphydf** [comment]
I see the "main" attribute, which denotes a Module.function, but that means I need to make the module name "Groupbot" and also rename the file from "groupbot.hs" to "Groupbot.hs", both of which I don't need to do with cabal, and the former possibly breaks cabal (I haven't tested this).

**Comment by iphydf** [comment]
Yes, it breaks cabal:
```
<no location info>: error:
    output was redirected with -o, but no output will be generated
because there is no Main module.
```

**Comment by gdeest** [comment]
Try adding a module name matching your file name

**Comment by iphydf** [comment]
https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-executable-main-is

So, I can make this work with bazel or with cabal, but I can't make it work with both bazel and cabal.

**Comment by gdeest** [comment]
If you want to build your program with both systems, you indeed need to name the main source file `Main.hs` (perhaps by putting the file in its own directory). Are there specific reasons preventing you from doing that ?

**Comment by iphydf** [comment]
Yes, the reason is that I have multiple programs, and I'd like to avoid having many directories with a single file called Main.hs in it.

**Comment by mboes** [comment]
Surely we can align to whatever Cabal does here?
