### ISSUE TITLE
Haddock output differs when using ghc bindist

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#1005]
**Describe the bug**

The output of our Haddock test is different when using GHC binary distributions, for reasons that escape me: https://buildkite.com/tweag-1/rules-haskell/builds/36#a5128231-3be9-43d7-b7bd-7a10f5af4be8

**Expected behavior**

The output shoud be the same, irrespective of where the compiler was obtained.

**Comment by Profpatsch** [comment]
`pkgdb_to_bzl.py` knows how to pass `haddock_html` and `haddock_interfaces` to `haskell_import`, and `haskell_import` creates `HaddockInfo` providers which contain those fields.

Now, both `ghc_bindist` and `ghc_nixpkgs_haskell_toolchain` use that script to generate the GHC toolchain. However, `ghc_bindist` is missing the haddock html files:

![screenshot (2)](https://user-images.githubusercontent.com/3153638/61970584-634af200-afdd-11e9-9457-c120139cdbfc.png)

while `ghc_nixpkgs_haskell_toolchain` isn’t missing them:

![screenshot](https://user-images.githubusercontent.com/3153638/61970618-7a89df80-afdd-11e9-8c37-0e6c1e0aaedb.png)

(I generated those warnings by adding a few `print`s to the script)

I see two different ways forward here:
- either remove the need for distribution package haddocks from the complaining test
- or make bindists magically generate haddock html somehow

Maybe there are html files in the bindists, just not where their databases say they are, so we should inspect the extracted bindist directories.
