### ISSUE TITLE
stackage_snapshot: generate haskell_binary targets for requested binaries

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#1006]
We mostly moved the test targets to `stackage_snapshot`, but for e.g.

https://github.com/tweag/rules_haskell/blob/master/tests/BUILD.bazel#L40-L59

the binary still comes from nixpkgs, even though it’s a very simple pure haskell binary package.

`stackage_snapshot` only generates `haskell_library` targets, but nothing should hinder us from extending it to also generate `haskell_binary`s.

e.g. by adding a `binaries` field, like

```
stackage_snapshot(
  name = "stackage",
  packages = [ … ],
  binaries = {
    "proto-lens-protoc": {
      package = "proto-lens-protoc",
      binary = "proto-lens-protoc"
    }
  }
)
```

where we can select binaries we need from the hackage packages that provide them (some packages provide multiple binaries).

**Comment by mboes** [comment]
> but nothing should hinder us from extending it to also generate haskell_binaries.

This has been discussed before. And it's not that simple: remember, we're not parsing .cabal files to guess what outputs might be produced. Also, see library vs binary: these are very different and binaries need not be constrained to come from the same snapshot or any snapshot at all.

**Comment by aherrmann** [comment]
A version of this has been implemented in https://github.com/tweag/rules_haskell/pull/1304. See also the discussion in https://github.com/tweag/rules_haskell/issues/1306.
