### ISSUE TITLE
Add support for happy/alex.

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#101]
Cabal has integration. Writing genrules manually is easy, but if rules_haskell accepts .x and .y files, it can just build them transparently.

**Comment by iphydf** [comment]
Turns out, writing genrules is not easy: it wants the sources to be in the actual source tree. Related to that thought: #102.

**Comment by woehr** [comment]
I just tried writing some genrules for some .x and .y files and ran into this problem; specifically, haskell_library doesn't want to build anything when sources files aren't in the package directory. Does anyone know if there is a solution to this problem or a way to work around it for the time being?

**Comment by iphydf** [comment]
I didn't get anything to work. I've files #190 for the general issue of genrule'd sources.

**Comment by woehr** [comment]
Now that #211 is merged, something along the lines of the following works if anyone comes across this issue.

```
nixpkgs_package(
  name = "happy"
, attribute_path = happy
, repository = "@nixpkgs"
)

genrule(
  name = "gen-happy"
, srcs = [ "src/Par.y" ]
, outs = [ "src/Par.hs" ]
, cmd = "$(location @happy//:bin) -gac -o $@ $<"
, tools = ["@happy//:bin"]
)

haskell_library(
  name = "a-happy-parser"
, src_strip_prefix = "src"
, srcs = [ ":gen-happy" ]
, prebuilt_dependencies = [ ... ]
)
```

**Comment by iphydf** [comment]
This works fine now. genrule is fine.
