### ISSUE TITLE
Setup script fails with Bazel v0.24.1

### ISSUE THREAD

**Issue by symbiont-joseph-kachmar** [tweag/rules_haskell#1015]
**Description**
The README says that `rules_haskell` should work with Bazel >=0.24, however when I install Bazel v0.24.1 and run the setup script in a fresh directory I see the following message:
```
Error: Need at least Bazel v0.27.0 but v0.24.1 detected.
``` 

**Steps To Reproduce**
1) Download and install Bazel v0.24.1
2) Run `curl https://haskell.build/start | sh` in a fresh directory
3) Observe the error message

**Expected behavior**
The setup script and initial `bazel build //...` should succeed in a fresh directory with the required version of Bazel present on the host system.

**Environment**
 - OS name + version: macOS
 - Bazel version: 0.24.1
 - Version of the rules: N/A (sourced via setup script)

**Comment by mboes** [comment]
The build script is correct. The README needs to be updated. Do you need 0.24? That's quite an old version by Bazel standards... (future Bazel release will have longer release windows, but previously they had only one month compatibility windows)

**Comment by symbiont-joseph-kachmar** [comment]
I don't! However when I perform the same steps with Bazel v0.28.1 installed I run into the following errors:
```
ERROR: /Users/jkachmar/src/bazel_test/WORKSPACE:19:1: file '@rules_haskell//haskell:repositories.bzl' does not contain symbol 'rules_haskell_dependencies'
ERROR: /Users/jkachmar/src/bazel_test/WORKSPACE:26:1: name 'rules_haskell_dependencies' is not defined
ERROR: /Users/jkachmar/src/bazel_test/WORKSPACE:30:1: name 'rules_haskell_toolchains' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.096s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
...and if I modify `WORKSPACE` to point to the latest `rules_haskell` commit it still fails, but with the following:
```
ERROR: /Users/jkachmar/src/bazel_test/BUILD.bazel:29:1: HaskellRegisterPackage link-config-example/link-config-example.conf failed (Exit 126) ghc-pkg failed: error executing command external/rules_haskell_ghc_darwin_amd64/bin/ghc-pkg recache '--package-db=bazel-out/darwin-fastbuild/bin/link-config-example' -v0 --no-expand-pkgroot

Use --sandbox_debug to see verbose messages from the sandbox
external/rules_haskell_ghc_darwin_amd64/bin/ghc-pkg: line 11: /lib/bin/ghc-pkg: No such file or directory
external/rules_haskell_ghc_darwin_amd64/bin/ghc-pkg: line 11: exec: /lib/bin/ghc-pkg: cannot execute: No such file or directory
INFO: Elapsed time: 4.267s, Critical Path: 0.11s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully
```

**Comment by mboes** [comment]
I'm inferring from the error message that you are using ghc bindists on macOS. Our macOS job tests using a GHC toolchain provided by Nixpkgs. Would love to make sure the bindist job on macOS works though (we already test them in CI but only have a linux job for that currently). Could you open a new issue with the error you see? It's pretty strange because it's coming from a wrapper script that ships as part of these upstream bindists.

**Comment by symbiont-joseph-kachmar** [comment]
Opened #1016 with more details.
