### ISSUE TITLE
macOS bindist project cannot find 'ar' when using 'stack_snapshot'

### ISSUE THREAD

**Issue by symbiont-joseph-kachmar** [tweag/rules_haskell#1019]
**Describe the bug**
`rules_haskell` fails to find the `ar` program, even when it is available on the `PATH`, when building projects using the `stack_snapshot` rule with a toolchain using GHC bindists.

This is using 8eee207eb01a9d2c369bc666fc50dfb37d95934a to get a version of `rules_haskell` that works with macOS bindists.

**To Reproduce**
[See this repository for a reproducible example](https://github.com/jkachmar/bazel_haskell_bindist_sandbox/tree/15ad1575df753abffbf7576f7cfb910c456d8217)

**Expected behavior**
`rules_haskell` should successfully build libraries using the `stack_snapshot` rules on macOS with a toolchain that uses GHC bindists.

**Environment**
 - OS name + version: macOS 10.14.5
 - Bazel version: 0.28.1
 - Version of the rules: 8eee207eb01a9d2c369bc666fc50dfb37d95934a

**Comment by mboes** [comment]
Could you try #1022?

**Comment by symbiont-joseph-kachmar** [comment]
I've updated my repository to reflect the version of `rules_haskell` in that commit and it looks like everything works now.

Thanks very much!

I can close the issue now, or wait until that PR goes in, depending on your preference.

**Comment by mboes** [comment]
It'll auto-close when the PR gets merged.
