### ISSUE TITLE
Don't generate files in the source tree.

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#102]
.hs files with foreign imports seem to generate _stub.h files inside the source tree.

**Comment by mrkkrp** [comment]
At first glance there is no mention of `_stub.h` anywhere in the source code. Maybe some tool generates it as a side effect though. Can you provide a complete reproducing example?

**Comment by iphydf** [comment]
https://github.com/TokTok/hs-toxcore-c/blob/master/BUILD.bazel

I haven't minimised the example, but you can remove the deps and get the same result.

**Comment by iphydf** [comment]
I can't reproduce it anymore with the latest version from git.
