### ISSUE TITLE
haskell.build should be deployed from last release instead of current master

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#1020]
**Describe the bug**

Building from release has two implications:

* The start script will refer to the one on current master, meaning if there were breaking changes it will fail with the last release.
* The docs document master instead of the release people are using.

**Expected behavior**

https://haskell.build should only be updated once per release.

Optionally, we should have a second subdomain https://master.api.haskell.build/, which points to the current master documentation.

**Comment by Profpatsch** [comment]
I opened another issue in the past that is a subset of this one: https://github.com/tweag/rules_haskell/issues/857

**Comment by Profpatsch** [comment]
We use netlify for deployment, and netlify supports creating subdomains for branches, iff the netlify DNS setup is used: https://www.netlify.com/docs/custom-domains/#branch-subdomains

I suggest we do the following (if possible, or similar):

* Point `master` to `master.api.build.haskell`, push with every branch update.
* Create a `release` branch and point it to `release.api.build.haskell`.
  * Add “push release branch to release tag” to the MAINTAINERS manual for creating a release
* Change the frontpage at https://haskell.build/ to point to both the master API documentation and the  latest release (preferring the latest release).

**Comment by mboes** [comment]
We can't use that because we don't use Netlify for the DNS. We use CloudFlare I believe.

**Comment by mboes** [comment]
OK we now have two branches, with branch subdomains:

* master.api.haskell.build
* release.api.haskell.build

**Comment by mboes** [comment]
Buttons to each site added to front page.
