### ISSUE TITLE
Stack has a --numeric-version flag

### ISSUE THREAD

**Issue by aspiwack** [tweag/rules_haskell#1025]
I don't know since when it exists, but all the versions installed on my computer have it. It prints the version number without any decoration.

```
$ stack --numeric-version
1.9.3
```

This provides a simpler and more robust solution to version checking than #1004 .

**Comment by mboes** [comment]
This is an easy one. @Profpatsch can you take it on?

**Comment by Profpatsch** [comment]
Sure.
