### ISSUE TITLE
libffi not found when a cc_binary depends on a haskell_library and using bindists

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#1032]
**Describe the bug**

The `haskell_import` test fails when using a GHC bindist. The test logs say:

```
error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
```

**To Reproduce**

The toolchain must be a bindist.

```
$ bazel test tests/haskell_import
```

**Environment**
 - OS name + version: Ubuntu Linux
 - Bazel version: 0.28
 - Version of the rules:

**Additional context**

The problem comes from the fact that in a GHC bindist, `libHSrts.so` has a `DT_NEEDED` entry for `libffi.so`, but the `RUNPATH` only says `$ORIGIN`. Since Bazel mangles the name of the library, using a symlink in a fresh directory, the linker will never find `libffi.so`, which indeed lives in the same folder as `libHSrts.so` (but not the folder where the symlink is).

GHC from Nixpkgs, on the other hand, has a `RUNPATH` with an explicit entry for the location of `libffi.so` (which in that case doesn't reside in the same folder as `libHSrts.so`). That's why this issue doesn't arise in the Nixpkgs case.

This is probably blocked on https://github.com/bazelbuild/bazel/pull/8888.

**Comment by aherrmann** [comment]
This issue seems to be fixed by now. Probably due to the `cc_wrapper` and recent refactoring of C library dependencies.
```
$ bazel test //tests/haskell_import
```
passes with GHC bindist. And the following demonstrates that the `RUNPATH` entry is correct.
```
$ readelf -d bazel-bin/tests/haskell_import/haskell_import
...
 0x0000000000000001 (NEEDED)             Shared library: [libffi.so.7]
...
 0x000000000000001d (RUNPATH)            Library runpath: [...:$ORIGIN/../../_solib_k8/_U_S_Shaskell_Ctoolchain-libraries___Uexternal_Srules_Uhaskell_Ughc_Ulinux_Uamd64_Slib_Srts]
...
$ ls bazel-bin/_solib_k8/_U_S_Shaskell_Ctoolchain-libraries___Uexternal_Srules_Uhaskell_Ughc_Ulinux_Uamd64_Slib_Srts
libffi.so.7  libHSrts_thr-ghc8.6.5.so
```
