### ISSUE TITLE
PATH environment variable for `actions.run` on nix

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1067]
**Describe the bug**

All the `ctx.actions.run` which call a python script in rules haskell are failing since the following change in nixpkgs bazel:  https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86

This change removes a hack: previously, the path of the `python` interpreter was selected from an hardcoded value: 

https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86#diff-9f6c1905e08b768cabebaa8921124660L9-L10

Since this patch, bazel from nixpkgs use bazel default behavior which is to find for `python` in the current `PATH`.

However it seems that `bazel` is cleaning the environment before executing a few of the actions needed in rules_haskell. At least `ls_module`, as shown in the following bazel incantation: 

```
[nix-shell:~/tweag/rules_haskell]$ bazel test //tests/library-with-sysdeps:bin -s
INFO: Analyzed target //tests/library-with-sysdeps:bin (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
SUBCOMMAND: # //tests/library-with-sysdeps:library-with-sysdeps [action 'HaskellLinkDynamicLibrary tests/library-with-sysdeps/libHStestsZSlibrary-with-sysdepsZSlibrary-with-sysdeps-ghc8.6.5.so']
(cd /home/guillaume/.cache/bazel/_bazel_guillaume/80819d925a91d7b49ed839165b536ee7/execroot/rules_haskell && \
  exec env - \
    LANG=en_US.UTF-8 \
    LOCALE_ARCHIVE=external/glibc_locales/lib/locale/locale-archive \
  bazel-out/host/bin/external/rules_haskell/haskell/ghc_wrapper bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/compile_flags_library-with-sysdeps_HaskellLinkDynamicLibrary bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/extra_args_library-with-sysdeps_HaskellLinkDynamicLibrary.and.library-with-sysdeps.dynamic.manifest)
SUBCOMMAND: # //tests/library-with-sysdeps:library-with-sysdeps [action 'Action tests/library-with-sysdeps/exposed-modules-library-with-sysdeps']
(cd /home/guillaume/.cache/bazel/_bazel_guillaume/80819d925a91d7b49ed839165b536ee7/execroot/rules_haskell && \
  exec env - \
  bazel-out/host/bin/external/rules_haskell/haskell/ls_modules False bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/testsZSlibrary-with-sysdepsZSlibrary-with-sysdeps/_iface bazel-out/host/bin/external/rules_haskell_ghc_nixpkgs_haskell_toolchain/ghc-global-pkgdb bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/hidden-modules-library-with-sysdeps bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/reexported-modules-library-with-sysdeps bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/exposed-modules-library-with-sysdeps)
ERROR: /home/guillaume/tweag/rules_haskell/tests/library-with-sysdeps/BUILD.bazel:9:1: Action tests/library-with-sysdeps/exposed-modules-library-with-sysdeps failed (Exit 1) ls_modules failed: error executing command bazel-out/host/bin/external/rules_haskell/haskell/ls_modules False bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/testsZSlibrary-with-sysdepsZSlibrary-with-sysdeps/_iface ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "bazel-out/host/bin/external/rules_haskell/haskell/ls_modules", line 340, in <module>
    Main()
  File "bazel-out/host/bin/external/rules_haskell/haskell/ls_modules", line 300, in Main
    raise AssertionError('Could not find python binary: ' + PYTHON_BINARY)
AssertionError: Could not find python binary: python
Target //tests/library-with-sysdeps:bin failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.274s, Critical Path: 0.09s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

FAILED: Build did NOT complete successfully
```

Here we observe a few interesting points:

- `exec env -` clean the environment
- `ls_modules`, a bazel provided wrapper to launch the python script `ls_modules.py` fails with `Could not find python binary: ' + PYTHON_BINARY
- By observing the logic of the path lookup:

https://github.com/bazelbuild/bazel/blob/123c68daed17b19927372e4df7f7a2256db6b80e/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L298-L300

and

https://github.com/bazelbuild/bazel/blob/123c68daed17b19927372e4df7f7a2256db6b80e/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L58-L72

and 

https://github.com/bazelbuild/bazel/blob/123c68daed17b19927372e4df7f7a2256db6b80e/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L45-L52

We observe that the python executable path is located inside the `PATH` environment variable. Exactly what was changed in https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86#diff-9f6c1905e08b768cabebaa8921124660L9-L10

With an empty `PATH`, my understanding is that `bazel` is looking by default in `/usr/bin:/bin`. I've hacked the `ls_modules` script with a `print(search_path)` and observed that result.

Is this a bug in rules_haskell, which must provide the path to the correct python interpreter?

Is a change to a correct python toolchain able to solve this issue? I recall that this change was postponed because it was not working on windows: https://github.com/tweag/rules_haskell/commit/3054e52a1f8e9f0a02e7eaf5d0d71f1ee9309f34

**To Reproduce**

- Use this commit: https://github.com/tweag/rules_haskell/commit/0882c7c36c6977448914e661cd1b2d5c86e90450#diff-f6076cddc2d13f5f59e91f49c7fcde60
- Disable the `env` hacked lines
- run `bazel test //...` in `nix-shell`.

**Expected behavior**

It should work without any failure. However I still don't know if it should be considered a rules_haskell issue or a nixpkgs issue, considering that rules_haskell works perfectly fine using a bazel provided by something else than nixpkgs.

**Environment**
 - OS name + version: any linux, using the nixpkgs provided bazel and no `python` in `/usr/bin`
 - Bazel version: any, as long as it is provided by nixpkgs and includes the following change: 
https://github.com/NixOS/nixpkgs/commit/c4813515ca34e7f2aef73280646c94c4c1b0eb86#diff-9f6c1905e08b768cabebaa8921124660L9-L10
 - Version of the rules: current master

**Comment by aherrmann** [comment]
AFAIK this is fixed with the use of python toolchains (`nixpkgs_python_configure` or `_configure_python_toolchain`). @guibou feel free to re-open if this is still an issue you're observing.

**Comment by robinp** [comment]
Just a note: if you see this, maybe you are stuck with an old `--incompatible_use_python_toolchains=false` (or equivalent `--noincompatible_use_python_toolchains`). Delete that, and use `nixpkgs_python_configure`.
