### ISSUE TITLE
haskell_doc fails if sub-package does not provide documentation

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1075]
**Describe the bug**

This is a new incarnation of #335.

If `haskell_doc` references a package which does not provide a `.haddock` file, it fails.

I bisected the regression to this commit: ff669231cf63fcbc631c91e694254cfb7d35db71

I think the logic of checking if the path exists was removed in that commit. I'll open a PR with the added check. @mboes, you did the commit, do you remember if there is any reason to remove the check?

**To Reproduce**

Build an `haskell_doc` which point to a library which does not have a `.haddock` file. I'll come with a repro later if the PR takes more time than expected.

**Comment by guibou** [comment]
I'm stupid. I indeed break something.

**Comment by Profpatsch** [comment]
https://github.com/tweag/rules_haskell/pull/1077 took a shot at this, but the bindists GHC haddocks are more different from the nixpkgs GHC haddocks than we thought, meaning more work is necessary.

**Comment by lunaris** [comment]
Is there any route to fixing this that I can help with? Not sure how it's affecting other codebases, but I think it's pretty important.

**Comment by mboes** [comment]
@lunaris I haven't heard this blocking any of our other many users, but this is apparently affecting at least Habito and Kitty Hawk. I don't anticipate that the fix is terribly hard to do. The relevant code is in `haskell/haddock.bzl` I believe. The commit mentioned above by @guibou should also give a clue as to what's happening.

**Comment by guibou** [comment]
@lunaris for info, #1077 works fine for KittyHawk. I think the fix is correct (for ghc bindist and ghc from nixpkgs), just the test are different.

**Comment by guibou** [comment]
I also applied #1077 at nova discovery with success to fix the same problem.
