### ISSUE TITLE
Changes in stack setup are not visible without bazel clean --expunge

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1079]
**Describe the bug**

When adding:

```
load("@rules_haskell//tools:repositories.bzl", "rules_haskell_worker_dependencies")
rules_haskell_worker_dependencies()
```

In my repository, `bazel fetch //...` tries to fetch the `stack` tool, succeed at fetching it, but does not do anything to patch the library loader to make it compatible with nixos, resulting in the classic "no such file or directory" error.

A workaround on nixos is to provide a working `stack` executable in the current `PATH`. However when adding `stack` in the environment, I need to `bazel clean --expunge` so that the change can be observed.

**To Reproduce**

Change the `stack` in your environment (e.g. `PATH`) (remove it, make it point to another binary) and observe that the next bazel call won't take that change into account.

**Comment by Profpatsch** [comment]
I don’t think we support stack on NixOS.
