### ISSUE TITLE
Globally set the `stack` executable for `stack_snapshot`

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1080]
**Is your feature request related to a problem? Please describe.**

`stack_snapshot` have a `stack` attribute to select the `stack` binary we want to use. However if the `stack_snapshot` call is hidden in another repository, we cannot override it.

In #1078 and #1079 I observed that a workspace using rules_haskell may implicitly depends on a `stack_snapshot` call, without any control on the `stack` argument, leading to the following cases:

- if `stack_snapshot` provides a `stack` argument, no way to change it
- if `stack_snapshot` does not provide a `stack` argument, `stack_snapshot` will try the following:
   - downloading a `stack` prebuilt binaries. It may not be a working solution (see #1079).
   - use the environment (i.e. `PATH`) `stack`. That's not a satisfying solution for hermetic build if we want to provide our `stack` binary as a bazel label.

**Describe the solution you'd like**

A way to register a `stack` binary as a bazel toolchain.

**Comment by mboes** [comment]
We only need Stack in repository rules, not build rules. So how would a toolchain help?

**Comment by aherrmann** [comment]
If the `stack` attribute is unset, then `stack_snapshot` will use the `stack` [provided by `@rules_haskell_stack`](https://github.com/tweag/rules_haskell/blob/1b69c2cc74eb90cf508351f21b418bd1bf68e274/haskell/cabal.bzl#L2562-L2564).

I think we can achieve what this issue requests by exposing a repository rule that takes a user provided stack and generates `@rules_haskell_stack`. A user would have to call that rule at the beginning of their WORKSPACE file to pick a given version of stack and avoid the default behavior of fetching a stack release.

This could use [`existing_rule`](https://docs.bazel.build/versions/main/skylark/lib/native.html#existing_rule) to raise an error if the user didn't place this function early enough in their WORKSPACE.
