### ISSUE TITLE
shellcheck all bash scripts in `rules_haskell`

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#1092]
https://github.com/tweag/rules_haskell/pull/1018 added a shellcheck target for the start script, which is run in the test suite. This helps us avoid common problems when writing shell scripts.

We have a bunch more shell scripts in `rules_haskell` (e.g. search for `*.sh` and `.sh.tpl`), it should be pretty easy to extend shellchecks to all of these targets.

**Comment by smelc** [comment]
Closed by #1264
