### ISSUE TITLE
Bazel 1.0 compatibility

### ISSUE THREAD

**Issue by laurentlb** [tweag/rules_haskell#1107]
Hi,

Can you make sure rules_haskell (and any other rule/project you care about) is compatible with Bazel 1.0? I've seen that @meisterT recently fixed an issue (https://github.com/tweag/rules_haskell/pull/1106). I'd like to make everything is up to date before the release.

Bazel 1.0 binaries are available here: https://releases.bazel.build/1.0.0/rc3/index.html

Thanks a lot.

**Comment by Profpatsch** [comment]
The [master bazelci pipeline is green at the moment](https://buildkite.com/bazel/rules-haskell-haskell/builds?branch=master), as long as that is the case, does that mean we are compatible with the 1.0.0 rc releases?

Do we need to flip any more flags in our [presubmit config](https://github.com/tweag/rules_haskell/blob/a8dc6f06e157a1ccaa1c388e57cf7caa5421fd0b/.bazelci/presubmit.yml#L1)?

**Comment by guibou** [comment]
Using bazel 1.0rc3 from nixpkgs (
https://github.com/NixOS/nixpkgs/pull/69252) I can see the following issue:


```
Traceback (most recent call last):
	File "/home/guillaume/tweag/rules_haskell_master/tests/haskell_proto_library/BUILD.bazel", line 6
		//haskell:protobuf.bzl%_haskell_proto_aspect(...)
	File "/home/guillaume/tweag/rules_haskell_master/haskell/protobuf.bzl", line 89, in _haskell_proto_aspect_impl
		target.proto
<target //tests/haskell_proto_library:zip_code_proto> (rule 'proto_library') doesn't have provider 'proto'
```

**Comment by mboes** [comment]
Why isn't this caught by the Bazel CI job for rules_haskell?

**Comment by guibou** [comment]
@mboes: `tags`, such as `--build_tag_filters=-requires_hackage`.

**Comment by guibou** [comment]
`bazel test //... --build_tag_filters=-requires_hackage` succeds with `bazel-1.0.0-rc3` for all tests but one which segfault. I'm investigating.

**Comment by guibou** [comment]
`.proto` issue fixed. I'll push a PR ASAP. I'm investingating the other test issue.

**Comment by guibou** [comment]
See #1109 

That's not a bazel issue.

**Comment by guibou** [comment]
@laurentlb all tests but 1 are ok with bazel 1.0.0 rc3, if we include the changes from #1109. There is a weird behavior with a (python dependent) test which segfault, but from my point of view, I think there is no regression in bazel 1.0.0.

But I don't have authority here, so @Profpatsch, @mboes  or @aherrmann will confirm.

**Comment by guibou** [comment]
For information, the test which fails is:

```
[nix-shell:~/tweag/rules_haskell_master]$ bazel test //tests:test-cc_haskell_import_python
INFO: Writing tracer profile to '/home/guillaume/.cache/bazel/_bazel_guillaume/bcf105a91a856e1c0e5f56e8c0e62ad7/command.profile.gz'
DEBUG: /home/guillaume/.cache/bazel/_bazel_guillaume/bcf105a91a856e1c0e5f56e8c0e62ad7/external/bazel_skylib/lib.bzl:30:1: WARNING: lib.bzl is deprecated and will go away in the future, please directly load the bzl file(s) of the module(s) needed as it is more efficient.
INFO: Analyzed target //tests:test-cc_haskell_import_python (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
FAIL: //tests:test-cc_haskell_import_python (see /home/guillaume/.cache/bazel/_bazel_guillaume/bcf105a91a856e1c0e5f56e8c0e62ad7/execroot/rules_haskell/bazel-out/k8-fastbuild/testlogs/tests/test-cc_haskell_import_python/test.log)
Target //tests:test-cc_haskell_import_python up-to-date:
  bazel-bin/tests/test-cc_haskell_import_python
INFO: Elapsed time: 0.493s, Critical Path: 0.35s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//tests:test-cc_haskell_import_python                                    FAILED in 0.3s
  /home/guillaume/.cache/bazel/_bazel_guillaume/bcf105a91a856e1c0e5f56e8c0e62ad7/execroot/rules_haskell/bazel-out/k8-fastbuild/testlogs/tests/test-cc_haskell_import_python/test.log

INFO: Build completed, 1 test FAILED, 2 total actions

[nix-shell:~/tweag/rules_haskell_master]$ cat /home/guillaume/.cache/bazel/_bazel_guillaume/bcf105a91a856e1c0e5f56e8c0e62ad7/execroot/rules_haskell/bazel-out/k8-fastbuild/testlogs/tests/test-cc_haskell_import_python/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tests:test-cc_haskell_import_python
-----------------------------------------------------------------------------
external/bazel_tools/tools/test/test-setup.sh: line 310:    14 Segmentation fault      (core dumped) "${TEST_PATH}" "$@" 2>&1
```

**Comment by mboes** [comment]
@guibou I don't know what "authority" you mean or lack thereof. The situation is simple: as far as Bazel 1.0 compatibility is concerned, either all our tests pass or they don't. Let's work on disabling fewer tests in the Bazel CI job, so that all compatibility problems are caught by that job.

**Comment by guibou** [comment]
https://github.com/tweag/rules_haskell/pull/1110 fix the python issue. So all tests are now passing with bazel 1.0.0.

**Comment by Profpatsch** [comment]
Great, I think we can close then.

**Comment by laurentlb** [comment]
Thanks a lot!
