### ISSUE TITLE
Contents of /usr/lib should not influence ghc invocations

### ISSUE THREAD

**Issue by mrkkrp** [tweag/rules_haskell#111]
While investigating #103, it was noticed that GHC looks for `.so` libraries in `/usr/lib` as well. Which means that contents of that directory may influence the building process, which is not desirable. There may be a way to tell GHC not to look there.

**Comment by mboes** [comment]
Do you have a repro?

**Comment by mrkkrp** [comment]
That was a while ago, I propose to close till this is "rediscovered" (if ever) through an actual build failure/problematic situation.
