### ISSUE TITLE
Absolute runpaths in ELF binaries

### ISSUE THREAD

**Issue by buchgr** [tweag/rules_haskell#1127]
On Bazel CI we found that running rules_haskell tests does not work well with remote caching. We traced the issue to be that your dynamically linked ELF binaries sometimes contain absolute paths. In particular this seems to be the case for external dependencies. See https://github.com/bazelbuild/bazel/issues/10038 for details.

**Comment by Profpatsch** [comment]
Specifically, we do something wrong with runpaths:

https://github.com/bazelbuild/bazel/issues/10038#issuecomment-543097460

**Comment by aherrmann** [comment]
This can be reproduced using the GHC bindist (not the nix-shell).
```
$ bazel build //tests/binary-with-lib-dynamic:binary-with-lib-dynamic
$ readelf -d bazel-bin/tests/binary-with-lib-dynamic/binary-with-lib-dynamic
...
 0x000000000000001d (RUNPATH)            Library runpath: [...:$ORIGIN/../../_solib_k8/_U@rules_Uhaskell_S_Shaskell_Ctoolchain-libraries___Uexternal_Srules_Uhaskell_Ughc_Ulinux_Uamd64_Slib_Srts:/home/aj/.cache/bazel/_bazel_aj/021cc9f0bfc60754963d997427e7eb3e/execroot/rules_haskell/external/rules_haskell_ghc_linux_amd64/bin/../lib/rts]
...
```
We find two entries for the `rts`, the latter leaking an absolute path into the artifact.

The `cc_wrapper` should already purge redundant `RUNPATH` entries so the absolute path should not be part in the list. However, the trouble is that we're not handling `libHSrts_thr` correctly.

The binary depends on 
```
 0x0000000000000001 (NEEDED)             Shared library: [libHSrts_thr-ghc8.6.5.so]
```
But the directory under `$ORIGIN/../../_solib_k8/_U@rules_Uhaskell_S_Shaskell_Ctoolchain-libraries___Uexternal_Srules_Uhaskell_Ughc_Ulinux_Uamd64_Slib_Srts` only contains
```
libffi.so  libHSrts-ghc8.6.5.so
```
So, that `RUNPATH` is not actually redundant. It seems to fix this we need to better handle the various `rts` flavors.
