### ISSUE TITLE
Remove special case for `-c dbg` and `-c opt`

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1129]
When building with `-c opt` or `-c dbg`, rules_haskell changes the behavior as following:

- `-c opt`: `-O2` flag is added
- `-c dbg`: a lot of stuffs are changed to enable Haskell debug.

I'm facing the following problems on a codebase with Haskell and C++ code.

- We want to build the C++ code with optimization (so `-c opt`) and suddenly the Haskell code takes 2x more time to build
- We want to build the C++ code with debug symboles (so `-c dbg`) and suddenly the Haskell code takes 15x more time to build (see #438 )

We can also imagine context where we want to build C++ or Haskell code with profiling and optimization, this is not easily doable today.

I propose the following changes:

- remove the special case for `-c opt`. If users want `-O2`, they can add it on `compiler_flags` based on configurations.
- remove the special case for `-c dbg` and replace this by a flag on the `haskell_toolchain` or on `haskell_library` / `haskell_binary`.

**Comment by mboes** [comment]
> We want to build the C++ code with optimization (so -c opt) and suddenly the Haskell code takes 2x more time to build

... and the C++ code likely also takes 2x more time to build. But isn't that exactly what you asked for in that case? i.e. "Ms compiler, please spend more time to generate better code"?

Today `-c opt` turns on `-O2` for C++. What do you suggest `-c opt` mean for Haskell? The same thing as `-c fastbuild`?

**Comment by guibou** [comment]
First of all, the increase of build time with `-O2` is not the same in C++ than it is in Haskell. For example, here I'm compiling a C++ file in `-O0` in 0.110s, and in `-O2` in 0.150s. In comparison a similar haskell file compiles in `-O0` in 0.4s and in `-O2` in 3.7s.

I propose to let the user choose based on configuration. Actually that's fine if you want to keep the `-c opt` and `-c dbg` behaviors, but we also need a way to do something different.

- What if I want to build with profiling enabled AND optimizations?
- What if I want to build my C++ with optimizations and debug symbols, but my Haskell without because I don't care about performances and I care more about my build time (in this context, I have 15 minutes build time transformed in 15x15minutes for a runtime of 5 seconds, 2 with optimizations).

**Comment by mboes** [comment]
The title of this issue is "Remove special case for `-c dbg` and `-c opt`". As far as I understand, concerning `-c opt` in particular, you are proposing to turn that into a no-op. Is that right? I find it hard to justify not having the same semantics as for C++ when these can be replicated exactly in the Haskell rules (as is the case for `-c opt`).

As for the questions in your previous comment, those sound like different feature requests to me.

**Comment by guibou** [comment]
Could you suggest a better title for the issue please?

**Comment by guibou** [comment]
Closed in favor of #1315 :

- #1315 discuss a way to enable / disable profiling per rule or globally for all the haskell rules. This solves the `-c dbg` issue I'm having here.
- Solving the `-c opt` issue is trivial: just pass `-O0` or `-O2` on the `compiler_flags`.
