### ISSUE TITLE
Support package database containing long module name in GHC 8.8

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1165]
**Describe the bug**

Since GHC 8.8 the package database format seems to have changed a bit and contains wrapped lines.

For example, here is a chunk of the entries for `data-default-instances-old-locale` in ghc `8.6.5` and `8.8.1`

Dump generation:

```
λ paddle ~ → nix-shell -p "haskell.packages.ghc865.ghcWithPackages(p: [p.data-default-instances-old-locale])"
[nix-shell:~]$ ghc-pkg dump > pkg865
```
```
λ paddle ~ → nix-shell -p "haskell.packages.ghc881.ghcWithPackages(p: [p.data-default-instances-old-locale])"
[nix-shell:~]$ ghc-pkg dump > pkg881
```

```
λ paddle ~ → cat pkg865| grep -A5 'name:.*data-default-instances-old-locale'                        
name: data-default-instances-old-locale
version: 0.0.1
id: data-default-instances-old-locale-0.0.1-GRzcBvmea5LLGj3CNDMpIw
key: data-default-instances-old-locale-0.0.1-GRzcBvmea5LLGj3CNDMpIw
license: BSD-3-Clause
maintainer: <l.mai@web.de>
```

```
λ paddle ~ → cat pkg881| grep -A5 'name:.*data-default-instances-old-locale'
name:                 data-default-instances-old-locale
version:              0.0.1
visibility:           public
id:
    data-default-instances-old-locale-0.0.1-26yQMJ7x0xCF8E8NsOHD2F
```

You can observe the newly introduced spaces and line break.

This breaks the assumptions done here: 

https://github.com/tweag/rules_haskell/blob/master/haskell/private/ls_modules.py#L30-L32

Especially, this file supposes that the content of the `id` field appears on the same line.

**To Reproduce**

I pushed in commit df22035013857f420df95e75a349617d1caa5a8d a reproduction.

**Expected behavior**

This is not supposed to crash.

**Additional context**

There are two solutions to fix the issue:

- Find a way to reset `ghc-pkg dump` to the old behavior. I haven't investigated yet.
- Write a more robust parser in `ls_modules.py`. I have a diff for that ready and running in production on a client codebase. I'll investigate the reasons of this change in `ghc-pkg dump` tomorrow and based on the results, I'll submit a PR.

**Comment by guibou** [comment]
I opened a bug report on GHC bugtracker: https://gitlab.haskell.org/ghc/ghc/issues/17546

I was not able to track the origin of the change, but I'm now convinced of a few things:

- a) the line wrapping was already there in GHC 8.6, just that it is now activated on smaller package id due to the newly added whitespace for alignment.
- b) there is no easy workaround (no option to disable wrapping) because this formatting is inside Cabal and uses the default `Text.PrettyPrint` settings for line wrapping. It means that we need to fix it.

PR will follow.

**Comment by guibou** [comment]
Do we care about this issue? It only happen to one client using a deprecated monolithique package database.

**Comment by Profpatsch** [comment]
I guess it depends on how intrusive the fix is.

**Comment by guibou** [comment]
> I guess it depends on how intrusive the fix is.

I'm closing. The discussion already took too long compared to the benefit.
