### ISSUE TITLE
Cache the stackage snapshot repository

### ISSUE THREAD

**Issue by jcpetruzza** [tweag/rules_haskell#1168]
**Is your feature request related to a problem? Please describe.**

We were trying to move from a setup where we use a `ghcWithPackages` with all our external dependencies plus invocations to `haskell_toolchain_library` to one based on `stackage_snapshot`. The main blocker we have at the moment is that fetching this repository takes either 1 or 5 minutes (depending on whether `~/.stack` already exists, I think), which is a bit too long. IIUC, the source of the slowness is `stack unpack` having to handle 450+ packages, and possibly doing it one at a time.

On the other hand, If I make a tarball of `external/stackage` it takes 45MB, which I can download in a few seconds.

**Describe the solution you'd like**

I'd like `stack_snapshot()` to try to download a content-indexed tarball of the repository from a WebDAV cache, given as an optional attribute (usually the same url used for bazel's remote cache). In case of a cache-miss, build the repository just like it is done now, but at the end make a tarball with its contents and try  to upload it to the cache.

For creating the hash to index the cache, most other inputs to the `stack_snapshot()` rule could be considered verbatim. The exceptions would be:  `local_snapshot`, whose content would have to be used; and `stack`, where the version is probably a better value than its location.

**Describe alternatives you've considered**

We are not aware of any good workarounds at the moment (oth, if we are the only ones experiencing this, maybe we are doing something wrong?)

**Additional context**

The reason this is an issue for us is because, IIUC, it means that every time we update any dependency, every developer will have to wait a few minutes for their next build to happen. With our current setup, all haskell targets get invalidated (which is also annoying, and what we were trying to improve), but at least one only pays for what you are building locally and we can let CI pre-populate bazel's remote cache. Additionally, the 5 minute delay is particularly problematic on CI, where it messes with timeouts we have for our builds there.

**Comment by mboes** [comment]
It's true that `stack unpack` is pretty slow. Even for just a handful of dependencies, it takes noticeable time. Is the slowness coming from downloading a full Hackage index, or from the downloading of each tarball? If the latter, making that as fast as an uber tarball should be as simple as adding HTTP pipelining upstream.

With an uber tarball, what would be the workflow if one of your engineers wants to add a new dependency?

**Comment by jcpetruzza** [comment]
> Is the slowness coming from downloading a full Hackage index, or from the downloading of each tarball? 

Good point. I can download `http://hackage.haskell.org/01-index.tar` from the same box in 1 minute, and get a 608MB tarball. That probably explains why forcing a fetch of a `stack_snapshot` repository takes 1 minute when reusing the `~/.stack` directory (where all package tarballs will be in the pantry already). If I force the fetch after a `rm -Rf ~/.stack`, this takes more than 5 minutes, so I expect 1 minute for downloading the index, 4 minutes for downloading 450+ packages, which sounds reasonable if they are done sequentially.

>  If the latter, making that as fast as an uber tarball should be as simple as adding HTTP pipelining upstream.

Makes sense, but there would still be a noticeable difference between downloading 45MB vs 600MB (few seconds vs a minute).

> With an uber tarball, what would be the workflow if one of your engineers wants to add a new dependency?

In our set-up, we have a remote-cache that is written on CI but can also be written from a dev box. So if an engineer updates a dependency, they'd pay the 1 to 5 minute penalty locally, but by the time the changes hit master (or even CI), a snapshot would be available on the remote-cache. Even if the cache can be written only by CI, as long as the branch is built on CI before merging to master, everything should run fast for the rest.
