### ISSUE TITLE
Repl targets fail with runfiles-related error

### ISSUE THREAD

**Issue by judah** [tweag/rules_haskell#1189]
**Describe the bug**
The repl targets don't work on my machine.
 
**To Reproduce**

```
$ bazel run tests/binary-simple:binary-simple@repl
INFO: Analyzed target //tests/binary-simple:binary-simple@repl (0 packages loaded, 3 targets configured).
INFO: Found 1 target...
Target //tests/binary-simple:binary-simple@repl up-to-date:
  bazel-bin/tests/binary-simple/binary-simple@repl
INFO: Elapsed time: 0.149s, Critical Path: 0.01s
INFO: 1 process: 1 local.
INFO: Build completed successfully, 6 total actions
INFO: Build completed successfully, 6 total actions
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/binary-simple/repl-package_env-binary-simple
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/binary-simple/repl-package_env-binary-simple
Traceback (most recent call last):
  File "bazel-out/host/bin/haskell/cc_wrapper-python", line 349, in <module>
    Main()
  File "bazel-out/host/bin/haskell/cc_wrapper-python", line 272, in Main
    module_space = FindModuleSpace()
  File "bazel-out/host/bin/haskell/cc_wrapper-python", line 111, in FindModuleSpace
    raise AssertionError('Cannot find .runfiles directory for %s' % sys.argv[0])
AssertionError: Cannot find .runfiles directory for bazel-out/host/bin/haskell/cc_wrapper-python
`cc_wrapper-python' failed in phase `gcc'. (Exit code: 1)
```
**Expected behavior**

**Environment**
 - Ubuntu Rodete
 - Bazel version 2.0.0
 - Version of the rules: 3fc77108396c99d89772170b040fb8ff65df8148
- Python 2.7.17rc1

**Comment by mboes** [comment]
@judah Could this be related to `--experimental_skip_runfiles_manifests`? The [release notes](https://blog.bazel.build/2019/12/19/bazel-2.0.html) for Bazel 2.0 imply it's an opt-in flag, but maybe I'm misunderstanding.

**Comment by judah** [comment]
Hm, I get the same error even when I pass `--noexperimental_skip_runfiles_manifests`.

I also don't see any runfiles generated (either with the flag or without); not sure if that's related:
```
$ ls -F bazel-out/host/bin/haskell/
cc_wrapper.py*  cc_wrapper-python*
```

**Comment by mboes** [comment]
The same test passes for me using Bazel 1.1. So I still suspect some breaking change in Bazel 2.0 or 1.2.

**Comment by judah** [comment]
Weirdly, I can also reproduce the error on my Mac with version 1.1.0 (from Homebrew).

**Comment by aherrmann** [comment]
@judah Does this only happen with the auto-generated `@repl` outputs, or also with `mutli_repl` targets? I.e. does `bazel run //tests/multi_repl:c_multi_repl` work?

The `@repl` script is not a proper target but just an additional output. So, it cannot define a `DefaultInfo` provider. But, AFAIK only `DefaultInfo` can declare proper runfiles dependencies. `@repl` tries to [force the generation](https://github.com/tweag/rules_haskell/blob/3fc77108396c99d89772170b040fb8ff65df8148/haskell/private/actions/repl.bzl#L165-L182) of runfiles and other dependencies, but that's a bit hacky and maybe Bazel changed something about the generation of runfiles for additional output files.

Maybe we should fully replace `@repl` (and probably also `@runghc`) by `multi_repl`. We could maintain backwards compatibility by turning `haskell_library` and friends into a macro that autogenerates `haskell_repl` targets. @mboes what do you think?

**Comment by judah** [comment]
`multi_repl` works for me.  Your analysis about runfiles and outputs makes sense with what I observed.

I also saw recently that the `outputs` attribute of `rule()` is deprecated, guarded by a flag `incompatible_no_rule_outputs_param`:
https://docs.bazel.build/versions/master/skylark/lib/globals.html#rule
https://github.com/bazelbuild/bazel/issues/7977
That would also break the `@repl`  approach.  Wrapping everything in a macro should work instead, though.

**Comment by mboes** [comment]
Shame that we can't make `@repl` an implicit target without hacks. In light of [https://github.com/google/hrepl](hrepl) coming to Earth, maybe we should just scrap it, and rely on hrepl for everything. If that solution works (unlike `@repl`, which apparently doesn't exactly like it used to).

**Comment by Profpatsch** [comment]
`multi_repl` works just fine and is a minor amount of boilerplate.
