### ISSUE TITLE
Import toolchain from Nixpkgs

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#12]
Bazel has a notion of "toolchain", which are typically specified by giving a URL via one of `new_http_archive`, `new_git_repository` etc. It would be great if we could furthermore specify a toolchain as an attribute in Nixpkgs. Reasons:

* It is wasteful to download a new toolchain, when this toolchain is likely already in the Nix store and can be shared across many Bazel repos.
* There does not exist GHC bindists that, when unpacked, work on NixOS, which has ELF loaders and system libraries in non-standard locations. On NixOS, only the GHC provided by Nixpkgs works.
* Nixpkgs can provide the strong reproducibility guarantees that Bazel requires. Given a Nixpkgs Git commit identifier, and an attribute name, the toolchain will always be byte-for-byte identical if it is downloaded now or in the future.

The problem is, I don't see how to achieve this with Bazel's current rule set. AFAIU, there is only a fixed set of primitive rules that are legal in a `WORKSPACE` file. What we'd want to define is a macro

```python
new_nixpkgs_package(
  name = "somepkg",
  sha256 = "...",
  build_file = "BUILD.somepkg",
  nixpkgs_version = "...", # optional
)
```

and have that expand to some invocation of `new_local_repository(path = somepkg_path, ...)`. But we can't hardcode such a path, which we don't know a priori. We can derive it after invoking some Nix CLI tools, however.

So what we'd need from Bazel is the ability to run arbitrary shell commands in a `WORKSPACE` file and allow fields of say `new_local_repository` to depend on the output of these commands. @jin any advice as to whether this is possible, or would make sense to add to the Bazel roadmap?

**Comment by mboes** [comment]
It looks like [`repository_rule`](https://docs.bazel.build/versions/master/skylark/lib/globals.html#repository_rule) might be just what we're looking for.

**Comment by jin** [comment]
Yes, defining a repository_rule is the only way to do non-hermetic
operations like network and filesystem access.

**Comment by mboes** [comment]
Got good initial success with the `repository_rule` approach in a new dedicated repository: https://github.com/tweag/rules_nixpkgs. Closing and will continue there.
