### ISSUE TITLE
repl-only dependencies

### ISSUE THREAD

**Issue by joprice** [tweag/rules_haskell#1206]
It would be nice to have dependencies available in a repl without having them be a dependency of the library. Stack's repl allows you to access dependencies installed via stack, even if they are not declared as a dependency of the current library being built. An example use case is debugging with pretty-simple, which is convenient for pretty printing data structures. 

As a workaround, I tried making a second library that has the dependency and depends on the original code, but then `:r` no longer works to reload code, since dependencies are not reloaded. Another solution is generating two rules in a macro:

```python
load(
    "@rules_haskell//haskell:defs.bzl",
    _haskell_library="haskell_library",
)

def haskell_library(name, deps, repl_deps = [], **kwargs):
  _haskell_library(
      name = name,
      deps = deps,
      **kwargs
  )
  _haskell_library(
      name = name + "_repl",
      deps = deps + repl_deps,
      **kwargs
  )
```

Then, you can use this macro in place of the normal one throughout the code base. The only unfortunate thing is now there are two repl targets, where one (without the extra deps) is not actually intended to be used.

**Comment by aherrmann** [comment]
@joprice You can achieve this using the more flexible `haskell_repl` rule. See [documentation](https://release.api.haskell.build/haskell/repl.html#haskell_repl).

For example:
```
load("@rules_haskell//haskell:defs.bzl", "haskell_library", "haskell_repl")
haskell_library(
    name = "some-lib",
    ...
)
haskell_repl(
    name = "repl",
    deps = [
        ":some-lib",
        "@stackage//:pretty-simple",
    ],
)
```
Assuming that you have a [`stack_snapshot`](https://release.api.haskell.build/haskell/cabal.html#stack_snapshot) named `stackage` that imports `pretty-simple`.
