### ISSUE TITLE
Build broken with Bazel at HEAD

### ISSUE THREAD

**Issue by laszlocsomor** [tweag/rules_haskell#1218]
**Describe the bug**

Build is broken on Bazel CI with Bazel at HEAD (https://github.com/bazelbuild/bazel/commit/f5b9d930a93fadd40295ffe38dec2bf80569e38b).

Log: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1360#b9e885da-048d-417f-b20f-7913c7567a8a

Other projects also broke with the same culprit: Maven no longer supports fetching from "http" URLs. Those projects just needed to upgrade their external repo dependencies, e.g. like so: https://github.com/bazelbuild/codelabs/pull/30

**To Reproduce**

Not sure. I couldn't set up the build locally.

**Expected behavior**

**Environment**
 - OS name + version: Linux
 - Bazel version: HEAD (https://github.com/bazelbuild/bazel/commit/f5b9d930a93fadd40295ffe38dec2bf80569e38b)
 - Version of the rules: 2f7e89006a5e602ce50d8cb2be66ab31f8ae59f5

**Additional context**

Possibly related: https://github.com/tweag/rules_haskell/issues/1217

**Comment by aherrmann** [comment]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1360#b9e885da-048d-417f-b20f-7913c7567a8a/628-649
```
ERROR: An error occurred during the fetch of repository 'org_apache_spark_spark_core_2_10':
  | java.io.IOException: Error downloading [http://central.maven.org/maven2/org/apache/spark/spark-core_2.10/1.6.0/spark-core_2.10-1.6.0.jar] to /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/b2c74d366118053922794e90182145d4/external/org_apache_spark_spark_core_2_10/spark-core_2.10-1.6.0.jar: GET returned 501 HTTPS Required
```

This has been fixed by https://github.com/tweag/rules_haskell/pull/1214 (which was merged after https://github.com/tweag/rules_haskell/commit/2f7e89006a5e602ce50d8cb2be66ab31f8ae59f5)

**Comment by laszlocsomor** [comment]
Cool, thanks for the quick response!
