### ISSUE TITLE
Test hrepl in rules_haskell CI

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#1221]
#1210 introduces support for [hrepl](https://github.com/google/hrepl) to `rules_haskell`. To avoid development on `rules_haskell` breaking this integration we should add tests to `rules_haskell`'s CI.

See https://github.com/tweag/rules_haskell/pull/1210#issuecomment-577256603
> The `hrepl` repo itself has tests which are (sort of) driven by `bazel`:
> https://github.com/google/hrepl/blob/master/hrepl/tests/run_tests.sh
> https://github.com/google/hrepl/blob/d946c54471fa5f1ca7dc5b8baf0db6a19429b319/hrepl/tests/BUILD.bazel#L5
> 
> They work by pointing `bazel` to the current directory but with `--output_base` pointing to a temporary directory. It uses `--test_env` to inject those values into a given `bazel test` invocation. However, because they need to download and install the GHC bindist, etc. in a new location (due to different `output_base`), they take ~10m to run on my laptop, and probably more in CircleCI.
> 
> I can think of a few possiblities:
> 
> 1. Run hrepl's tests in CI (or maybe a subset of them).
> 2. Run a simplified version of hrepl's tests in CI that doesn't try to be as hermetic, and reuses the same `output_base` as the rest of the build. It should be much faster as a result.  It would still miss testing some edge case situations, but we'd get that covered by the `hrepl` repo's own testing.
> 3. Do something much simpler, similar to what `RunTests.hs` does [now](https://github.com/tweag/rules_haskell/blob/d3ca7094c727d9dfda464c178bb0e4ae0171baa5/tests/RunTests.hs#L49).  For example, instead of `bazel run //...@repl -- ...` do `bazel build @hrepl//hrepl; bazel-bin/external/hrepl/hrepl/hrepl //... ...`

**Comment by aherrmann** [comment]
@judah Continuing the testing discussion here. Thanks for explaining the testing strategies.

Option 1 would certainly be the most complete, but I'd prefer not to introduce that much extra time into CI. @mkarpov is working on setting up a `--repository_cache` on CI. Do you think sharing a repository cache between the main pipeline and the `hrepl` tests would work to avoid fetching the bindist?

Otherwise, we could start with option 2. That sounds like a good start.

**Comment by judah** [comment]
In my testing the `--repository_cache` flag didn't significantly affect the runtime. For example, I tried `bazel build hrepl && bazel clean --expunge && bazel build hrepl` (with `--repository_cache in my `bazelrc`) and both runns took the same amount of time.

it seems like the repository cache might only cache the download, not the untar/configure/make-install steps of the bindist fetch which take the majority of the time.  But I had a hard time confirming this for sure from the Bazel docs.

I'll look into setting up Option 2.

**Comment by aherrmann** [comment]
@judah Is `hrepl` still relevant? A test-case for hrepl compatibility would still be very welcome.
We have recently added integration-test capabilities based on rules_go's go_bazel_test, see [here](https://github.com/tweag/rules_haskell/pull/1692/files#diff-69f9bc7014d1a7b075f49c73737e47aee16151bdd08b176514ffb57516f91516R123). Perhaps this would help with such an integration test.

I'll close for now due to inactivity, but, please feel free to re-open if this is still relevant.
