### ISSUE TITLE
Reverse order of `-fplugin` parameters

### ISSUE THREAD

**Issue by sellout** [tweag/rules_haskell#1255]
**Is your feature request related to a problem? Please describe.**
`plugins = [":foo", ":bar"]` results in `:bar` getting installed before `:foo`. rules_haskell is ostensibly doing the right thing (it creates the flags in the same order they are in the list). However, [GHC currently installs plugins in the reverse order that they're provided](https://gitlab.haskell.org/ghc/ghc/issues/17884), which is non-intuitive. The order is significant as plugins can affect each other during installation.

**Describe the solution you'd like**
It would be helpful if rules_haskell could ensure that the order of the list is the same as the order of installation. On GHC up to at least 8.8.2, that would mean passing them in reverse order, then when the GHC issue is hopefully fixed, pass the flagis in the same order as the list for future GHC versions.

**Describe alternatives you've considered**
Currently I just add a comment before each `plugins` list to explain that the behavior is the opposite of what's implied by the list.

**Comment by avdv** [comment]
FTR, this issue has been fixed upstream, and the fix is included in GHC >= 9.4.1. See https://downloads.haskell.org/ghc/9.4.1/docs/users_guide/extending_ghc.html#using-compiler-plugins 

> Plugins are loaded in order, with command-line and Cabal flags preceding those in OPTIONS pragmas which are processed in file order.
