### ISSUE TITLE
Bazel internal error (crash) when srcs of a dependency are empty

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#1258]
**Describe the bug**
A particular setup, with a particular set of packages, causes a crash. I have no idea what the circumstances are that conspire to cause this crash, but I can reproduce. It's a NullPointerException inside bazel.

**To Reproduce**
Will follow up with a repro case on Travis.

**Expected behavior**
Building a package (in the repro, I actually expect a compile error from GHC).

**Environment**
 - OS name + version: Debian Buster (probably also Ubuntu Xenial on Travis).
 - Bazel version: 2.1.1
 - Version of the rules: latest master

**Comment by iphydf** [comment]
Repro: https://travis-ci.com/iphydf/repro1258/jobs/293656022#L287
Github: https://github.com/iphydf/repro1258

**Comment by regnat** [comment]
Might be a false trail, but the stacktrace points in the direction of https://github.com/bazelbuild/bazel/issues/10580 − a regression of bazel 2.x that causes a `NullPointerException` in some edge-case. Hazel isn't used much nor officially part of `rules_haskell` anymore, so it's reasonably possible that it hits this very edge-case without anyone having noticed until now

**Comment by iphydf** [comment]
I'm not actually using hazel. I can reduce the repro to avoid hazel.

**Comment by iphydf** [comment]
I've reduced it to no longer import hazel. It's purely using rules_haskell now.

**Comment by iphydf** [comment]
Changing version here: https://github.com/iphydf/repro1258/blob/master/third_party/haskell/packages.bzl#L11 to 0.11.7.1 makes the error go away. This leads me to think that the large number (100) in the third position is what breaks it.

**Comment by iphydf** [comment]
Note that actually building the package itself (cryptohash-sha1) works fine, it's when you start depending on it that things break.

**Comment by iphydf** [comment]
Confirmed on 2.2.0 as well.

**Comment by iphydf** [comment]
Confirmed on 1.2.1 as well.

**Comment by iphydf** [comment]
And confirmed on 1.2.0. I can't (trivially) test earlier than that because of other dependencies.

**Comment by iphydf** [comment]
Turns out the problem was that between one version and the next, cryptohash-sha1 moved their sources to a "srcs" subdirectory, making the package empty. It might be good to error out when srcs is actually empty, or at least give a warning.

**Comment by iphydf** [comment]
Nothing to do here. Bazel will soon (and does now, with --all_incompatible_changes) error when a glob matches nothing.
