### ISSUE TITLE
Troubles building on AppVeyor

### ISSUE THREAD

**Issue by joneshf** [tweag/rules_haskell#1259]
**Describe the bug**

I've been trying to setup `rules_haskell` on Windows. I can't seem to progress past this error:

```
ERROR: C:/projects/purty/.bazel-cache/_bazel_appveyor/5rhby5jo/external/happy/BUILD.bazel:6:1: HaskellCabalBinary @happy//:happy failed (Exit 1)
Traceback (most recent call last):
  File "\\?\C:\Users\appveyor\AppData\Local\Temp\1\Bazel.runfiles_w5rfpqk5\runfiles\rules_haskell\haskell\cabal_wrapper.py", line 105, in <module>
    strip = find_exe("external/local_config_cc/wrapper/bin/msvc_nop.bat")
  File "\\?\C:\Users\appveyor\AppData\Local\Temp\1\Bazel.runfiles_w5rfpqk5\runfiles\rules_haskell\haskell\cabal_wrapper.py", line 56, in find_exe
    if not os.path.isfile(path) and "True" == "True":
  File "C:\Python37\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Target //:purty failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 123.181s, Critical Path: 0.91s
```

Since this is building on AppVeyor, it should have the [required dependencies](https://github.com/tweag/rules_haskell/blob/77cf42c30a424f7e701c72c5feb31f49b5230351/docs/haskell.rst#before-you-begin):
* The [python](https://www.appveyor.com/docs/windows-images-software/#python)s available.
* The [msys2](https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin)s available.

I'm a bit stumped as to what to do. Any suggestions?

**To Reproduce**

Sorry, I don't have a small example at the moment yet. For now, I have the [logs](https://ci.appveyor.com/project/joneshf/purty/builds/31226913#L111) of builds that are failing, and the [branch](https://gitlab.com/joneshf/purty/-/commits/164-use-bazel-for-majority-of-the-build-system) I've been working off of. There's a [comparison](https://gitlab.com/joneshf/purty/-/compare/master...164-use-bazel-for-majority-of-the-build-system) between that branch and the `master` branch.

**Expected behavior**

Bazel should build.

**Environment**
 - OS name + version: AppVeyor `Visual Studio 2019` image. Not entirely sure what the exact OS and version is.
 - Bazel version: 2.2.0
 - Version of the rules: 77cf42c30a424f7e701c72c5feb31f49b5230351

**Additional context**

The Linux [build](https://travis-ci.org/joneshf/purty/jobs/658056813)s seem to work okay. The macOS [build](https://travis-ci.org/joneshf/purty/jobs/658056814) has its own issues that I plan to get to later.

**Comment by aherrmann** [comment]
It looks like `external/local_config_cc/wrapper/bin/msvc_nop.bat` is your cc toolchain's entry for the `strip` command and for some reason it doesn't end up in the runfiles of the `cc_wrapper` and isn't found by `Rlocation`. The `cabal_wrapper`'s `find_exe` fails to guard for `None` before calling `os.path.isfile`. That's something we should fix in `rules_haskell`. However, that won't resolve the issue, only improve the error message.

It seems Bazel picked up a cc toolchain using MSVC, instead of the one bundled by GHC. Could you retry with the following `build` flag? (See `rules_haskell`'s `.bazelrc` for reference)
```
--crosstool_top=@rules_haskell_ghc_windows_amd64//:cc_toolchain
```
On Windows, `rules_haskell` will only work with the cc toolchain bundled with GHC, not with MSVC. I'm afraid the Windows use-case is not documented very well. I couldn't find this mentioned in the docs. Sorry about that.

**Comment by joneshf** [comment]
No worries! Even though this has been hard to figure out, it's forced me to learn more about bazel. I think it's a net positive.

I can throw together a PR to add this information to the troubleshooting section, if that's wanted.

---

Thanks for the suggestion! This got things compiling Haskell! For posterity, this was the [change](https://gitlab.com/joneshf/purty/-/commit/56abc82f3105a4ebfc3ff2e52723cb88b8031913) I made:

```diff
diff --git a/.bazelrc b/.bazelrc
new file mode 100644
index 0000000..0845363
--- /dev/null
+++ b/.bazelrc
@@ -0,0 +1,3 @@
+build:windows --crosstool_top=@rules_haskell_ghc_windows_amd64//:cc_toolchain
+
+test --test_output errors
\ No newline at end of file
diff --git a/appveyor.yml b/appveyor.yml
index 17790f5..ee461fd 100644
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -5,7 +5,7 @@ before_deploy:
 build_script:
   - set PATH=C:\Python37\;%PATH%
   - ps: Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1
-  - .build\bazel.exe build //:purty
+  - .build\bazel.exe build --config windows //:purty
   - stack setup
   - make test-golden BINARY=purty.exe
```

N.B. For anyone else that stumbles upon this issue, the `test --test_output errors` is not necessary for the fix suggested, but it was part of my `.bazelrc` that hadn't been committed yet. I probably should have left that out, but didn't.

---

It's now failing with:

```
ERROR: C:/projects/purty/.bazel-cache/_bazel_appveyor/5rhby5jo/external/stackage/BUILD.bazel:264:1: HaskellCabalLibrary @stackage//:microlens failed (Exit 1)
Traceback (most recent call last):
  File "\\?\C:\Users\appveyor\AppData\Local\Temp\1\Bazel.runfiles_80i4f85y\runfiles\rules_haskell\haskell\cabal_wrapper.py", line 211, in <module>
    for line in package_conf.readlines():
  File "C:\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 898: character maps to <undefined>
```

I'll play around with locales and see if I can't figure that out.

**Comment by aherrmann** [comment]
> Thanks for the suggestion! This got things compiling Haskell! 

That's great news!

> I can throw together a PR to add this information to the troubleshooting section, if that's wanted.

Yes, that would be wonderful, thank you!

> I'll play around with locales and see if I can't figure that out.

Indeed, we may need to default to `en_US.UTF-8` on Windows as well. See [here](https://github.com/tweag/rules_haskell/pull/1254/files#diff-85408e6f9e4818174d8baf3df5946e07R269).

**Comment by joneshf** [comment]
Hmm, that didn't seem to make any change on windows, but caused a different linux build (which I don't think I can link to) to fail in a different way:
```
 ERROR: /builds/joneshf/purty/.bazel-cache/_bazel_root/af644cc4dc9be69410cb8a86c21583c6/external/stackage/BUILD.bazel:260:1: HaskellCabalLibrary @stackage//:microlens failed (Exit 1) cabal_wrapper failed: error executing command bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper lib:microlens microlens-0.4.10 true external/stackage/microlens-0.4.10/Setup.hs external/stackage/microlens-0.4.10 ... (remaining 6 argument(s) skipped)
 Use --sandbox_debug to see verbose messages from the sandbox
 Traceback (most recent call last):
   File "/builds/joneshf/purty/.bazel-cache/_bazel_root/af644cc4dc9be69410cb8a86c21583c6/sandbox/linux-sandbox/9/execroot/com_gitlab_joneshf_purty/bazel-out/host/bin/external/rules_haskell/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 211, in <module>
     for line in package_conf.readlines():
   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
     return codecs.ascii_decode(input, self.errors)[0]
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 485: ordinal not in range(128)
```

Is there a way to set the locale with flags (akin to what you suggested above)?

---

Lemme also pop up above water and ask if there's a way to cross-compile Haskell binaries to Linux, macOS, and Windows from a single host (preferably a Linux host). The only reason I'm running multiple builds on different platforms is that I haven't found a way to cross-compile. That would simplify this whole expedition tremendously!

**Comment by mboes** [comment]
@joneshf cross compilation is one of the big promises of Bazel. It has a nice and uniform framework to handle that. However, we haven't attempted that yet. There is ticket about this: #32. It's unchartered territory as far as rules_haskell is concerned.

**Comment by aherrmann** [comment]
> Is there a way to set the locale with flags (akin to what you suggested above)?

Currently the locale is an option to `rules_haskell_toolchains` which is called in the `WORKSPACE`. AFAIK, there is no straight-forward way to affect it with a command-line flag. One could work around this with a dedicated repository rule, e.g. in `rules_haskell` we have [`os_info`](https://github.com/tweag/rules_haskell/blob/4fe7b3a4e1b87717f5f081a7f574a96cd91f213c/WORKSPACE#L10) to branch on the OS in the `WORKSPACE`.

> [...] caused a different linux build (which I don't think I can link to) to fail in a different way

Did you also change the locale for Linux?

> that didn't seem to make any change on windows

Googling around a bit it seems that `C.UTF-8` or `en_US.UTF-8` is not a valid Windows locale, though mingw seems to understand it. That seems to be why only Python fails, while GHC and gcc work fine. I was able to reproduce the issue on `rules_haskell`'s Azure CI, see [here](https://dev.azure.com/tweag/rules_haskell/_build/results?buildId=3951&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=a8035825-ecc2-53a4-dc8f-13b782b0dc20). The following patch works around the issue: https://github.com/tweag/rules_haskell/commit/469d2ec576806b63c8d1b3187ac43099d7f71f9e. Though this hard-codes the assumption that the generated package configuration is readable as UTF-8.

**Comment by joneshf** [comment]
Sounds like the locale in the GHC bindist is a bust then.

Since that code looks like it doesn't care about anything except what it's `sed`ing, what about using `error='surrogateescape'`? According to the documentation:

> `'surrogateescape'` will represent any incorrect bytes as code points in the Unicode Private Use Area ranging from U+DC80 to U+DCFF. These private code points will then be turned back into the same bytes when the `surrogateescape` error handler is used when writing data. This is useful for processing files in an unknown encoding.

It seems like it should leave things alone that it doesn't recognize. I tried it [on myproject](https://gitlab.com/joneshf/purty/-/commit/a3d005d8768a93d336e988347da44285e5400d27) and was able to [completely build](https://ci.appveyor.com/project/joneshf/purty/builds/31252853) :tada: :tada: :tada:! It failed in the end due to timeout, but that's fine. I don't know if this has other ramifications, but I'm more than happy to submit a PR if you'd like.

**Comment by aherrmann** [comment]
> Since that code looks like it doesn't care about anything except what it's `sed`ing, what about using `error='surrogateescape'`?

That's a nice idea. I've also [tried it on `rules_haskell` and dumped the patched package configuration](https://dev.azure.com/tweag/rules_haskell/_build/results?buildId=3958&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3) to be sure absolute paths are still relativized. It's working great.

> I'm more than happy to submit a PR if you'd like.

Yes that would be great, thanks for looking into this!

**Comment by joneshf** [comment]
Looks like that was the last bit to get this working completely. Thanks for the help!
