### ISSUE TITLE
Building test suite fails with --spawn_strategy=standalone

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#128]
Build fails in the following way with `standalone` mode (which is set in the `ci` configuration defined in `tools/bazel.rc`):

```
$ bazel build //... --spawn_strategy=standalone
[...]
[1 of 2] Compiling Lib              ( tests/library-with-sysdeps/Lib.hs, bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/objects-bin-1.0.0/Lib.o )
[2 of 2] Compiling Main             ( tests/library-with-sysdeps/Main.hs, bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/objects-bin-1.0.0/Main.o )
INFO: From Building textual-hdrs:
[1 of 1] Compiling Main             ( tests/textual-hdrs/Main.hs, bazel-out/k8-fastbuild/bin/tests/textual-hdrs/objects-textual-hdrs-1.0.0/Main.o )
Warning: the following files would be used as linker inputs, but linking is not being done: tests/textual-hdrs/include/main_definition.h
ERROR: /home/mboes/src/tweag/rules_haskell/tests/c-compiles/BUILD:21:1: Linking c-compiles failed (Exit 1)
bazel-out/k8-fastbuild/bin/tests/c-compiles/objects-c-compiles-1.0.0/Main.o: In function `s3xg_info':
(.text+0x45): undefined reference to `Lib_ten_closure'
bazel-out/k8-fastbuild/bin/tests/c-compiles/objects-c-compiles-1.0.0/Main.o: In function `s3xi_info':
(.text+0x491): undefined reference to `Lib_ten_closure'
bazel-out/k8-fastbuild/bin/tests/c-compiles/objects-c-compiles-1.0.0/Main.o: In function `S3z2_srt':
(.data.rel.ro+0x0): undefined reference to `Lib_ten_closure'
collect2: error: ld returned 1 exit status
`cc' failed in phase `Linker'. (Exit code: 1)
INFO: Elapsed time: 122.508s, Critical Path: 9.10s
FAILED: Build did NOT complete successfully
```

Additionally, I notice a `*_stub.h` file in the working directory after compilation in this mode, just like @iphydf noticed in #102.

**Comment by mrkkrp** [comment]
So far:

The problem is best reproduced this way:

* Run `bazel build --spawn_strategy=standalone //tests/library-with-sysdeps:library-with-sysdeps`. This will succeed and create under `bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps` something like this:

```
.
├── interfaces-library-with-sysdeps-1.0.0
│   ├── Lib.dyn_hi
│   └── Lib.hi
├── libHSlibrary-with-sysdeps-1.0.0-ghc8.2.2.so
├── libHSlibrary-with-sysdeps-1.0.0.a
├── library-with-sysdeps-1.0.0
│   ├── library-with-sysdeps-1.0.0.conf
│   ├── package.cache
│   └── package.cache.lock
├── libtests_Slibrary-with-sysdeps_Szlib_libz.so -> /nix/store/108i1xswxgmvrzrsrx277892gpw6ix53-zlib-1.2.11/lib/libz.so.1.2.11
├── objects-library-with-sysdeps-1.0.0
│   ├── Lib.dyn_o
│   └── Lib.o
└── registration-file-library-with-sysdeps-1.0.0
```

* The next step is to run `bazel build --subcommands --verbose_failures --spawn_strategy=standalone //tests/library-with-sysdeps:bin` which will build `bin` object files (`Main.o`) and then will fail on linking.

The command is roughly:

```
```

**Comment by mrkkrp** [comment]
OK, I think I know what happens here. When we use sandboxing this command (compiles `bin`, i.e. it produces `Main.o`):

```
external/ghc/nix/bin/ghc -c --make -fPIC -hide-all-packages
-odir bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/objects-bin-1.0.0
-hidir bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/interfaces-bin-1.0.0
-itests/library-with-sysdeps -package base -package library-with-sysdeps-1.0.0
-package-db bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/library-with-sysdeps-1.0.0
tests/library-with-sysdeps/Main.hs -main-is Main.main
```

Indeed produces just `Main.o`. Even though there is `Lib.hs` in the same directory as `Main.hs` the latter does not see it, so it has no way to grab it for compilation, in that case everything happens as expected.

However without sandboxing the same command (shown above) results in `Main.hs` referencing the module `Lib` and the file `Lib.hs` happens (in)conveniently present in the same directory. In that case two files are produced: `Lib.o` and `Main.o`. And guess what, the reference to `crc` happens to be statically linked to `Lib_crc_closure` symbol which is present in `Lib.o`:

```
00000000000000b0 D Lib_crc_closure
0000000000000340 T Lib_crc_info
0000000000000020 D Lib_zdtrModule_closure
0000000000000000 d S28F_srt
                 U _GLOBAL_OFFSET_TABLE_
0000000000000000 D __stginit_Lib
                 U base_ForeignziCziTypes_zdfNumCInt_closure
                 U base_ForeignziCziTypes_zdfNumCLong_closure
                 U base_GHCziNum_fromInteger_info
                 U base_GHCziPtr_nullPtr_closure
0000000000000168 t c29a_info
00000000000001a8 t c29g_info
00000000000001e8 t c29l_info
0000000000000310 t c29z_info
                 U crc32
                 U ghczmprim_GHCziTuple_Z0T_closure
                 U ghczmprim_GHCziTypes_Module_con_info
                 U ghczmprim_GHCziTypes_TrNameS_con_info
                 U integerzmgmp_GHCziIntegerziType_Szh_con_info
                 U newCAF
0000000000000000 d r27Y_closure
0000000000000005 r r27Z_bytes
0000000000000000 r r27c_bytes
0000000000000010 d r280_closure
0000000000000050 d r281_closure
0000000000000018 t r281_info
0000000000000080 d r282_closure
0000000000000098 t r282_info
00000000000000a0 d r283_closure
0000000000000120 t r283_info
                 U resumeThread
0000000000000040 d s28e_closure
0000000000000070 d s28f_closure
                 U stg_ap_p_info
                 U stg_bh_upd_frame_info
                 U suspendThread
```

`Main.o`:

```
                 U Lib_crc_closure <------ uh oh
0000000000000000 D Main_main_closure
0000000000000060 D Main_zdtrModule_closure
0000000000000000 d S2cB_srt
0000000000000020 D ZCMain_main_closure
0000000000000018 T ZCMain_main_info
                 U _GLOBAL_OFFSET_TABLE_
0000000000000000 D __stginit_Main
                 U base_GHCziTopHandler_runMainIO_closure
                 U ghczmprim_GHCziTypes_Module_con_info
                 U ghczmprim_GHCziTypes_TrNameS_con_info
                 U newCAF
0000000000000000 r r2ce_bytes
0000000000000040 d r2cm_closure
0000000000000005 r r2cn_bytes
0000000000000050 d r2co_closure
                 U stg_IND_STATIC_info
                 U stg_ap_p_fast
                 U stg_bh_upd_frame_info
```

With sandboxing, `Lib.hs` is not visible and `Main.o` does not reference it (well, not in the same way as if it's just another module along with `Main`):

```
0000000000000000 D Main_main_closure
0000000000000060 D Main_zdtrModule_closure
0000000000000000 d S14j_srt
0000000000000020 D ZCMain_main_closure
0000000000000018 T ZCMain_main_info
                 U _GLOBAL_OFFSET_TABLE_
0000000000000000 D __stginit_Main
                 U base_GHCziTopHandler_runMainIO_closure
                 U ghczmprim_GHCziTypes_Module_con_info
                 U ghczmprim_GHCziTypes_TrNameS_con_info
                 U libraryzmwithzmsysdepszm1zi0zi0_Lib_crc_closure
                 U newCAF
0000000000000000 r rTW_bytes
0000000000000040 d rU5_closure
0000000000000005 r rU6_bytes
0000000000000050 d rU7_closure
                 U stg_IND_STATIC_info
                 U stg_ap_p_fast
                 U stg_bh_upd_frame_info
```

Thinking about solution now.

**Comment by mrkkrp** [comment]
I tried a few workarounds, but GHC is not happy. Created a ticket: https://ghc.haskell.org/trac/ghc/ticket/14809#ticket.

Basically to handle boot files we need `-i` and `--make`, but in other cases this allows ghc see files which should not be visible (such as `Lib.hs` during compilation of the binary). With sandboxing it's OK, but without it it leads to unexpected behavior. I think the right thing so far is to leave the situation as is and recommend sandboxed execution.

**Comment by mboes** [comment]
Nice detective work.

**Comment by mboes** [comment]
IIUC your last comment, you're saying "{standalone execution, boot file handling}, choose 1"?

**Comment by mboes** [comment]
Bumping back up the priority of this one. It's not very important for Linux/macOS, but could get in the way of Windows support, where sandboxing is non-existant.

**Comment by mboes** [comment]
`//tests/c-compiles` and `//tests/library-with-sysdeps` tests now pass. Probably due to using a newer GHC. But `//tests/indirect-link:indirect-link-dynamic` and `//tests/binary-linkstatic-flag:test-binary-dynamic-symbols` fail.

**Comment by mboes** [comment]
The original tests now pass as a side effect of #383. Originally, the linking stage would fail, because in an unsandboxed build GHC picks up more source files than Bazel expects. Hence more object files produced, but not linked because unaccounted for. Now we link whatever object files we find in the output folder, so no linking error. This is unhermetic and as a result Bazel may well not notice targets going out of date. But this is a hard limitation in GHC.

We could work around this by copying files into isolated folders ourselves, but that's redundant with the sandboxing when that is enabled so an unnecessary pessimization in that case. Furthermore, Cabal behaves in the exact same way as the current status quo. At least Cabal warns that this is happening, by passing `-Wmissing-home-modules` to GHC. I think we should satisfy ourselves with that option, given that this is an upstream issue that sandboxing avoids entirely and is easy enough to work around for those folks who must be able to build unsandboxed.

I'd even make that warning an error, except that unfortunately we do get false positives when `.hs-boot` files are involved.

cc @nmattia @gdeest
