### ISSUE TITLE
Missing libHSrts-ghc8.6.5.so for haskell_binary rules that depend on a haskell_library that depends on a cc_library

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#1287]
**Describe the bug**
Linking a cc_library to a haskell_library and then depending on it in a haskell_test (or haskell_binary) causes `error while loading shared libraries: libHSrts-ghc8.6.5.so: cannot open shared object file: No such file or directory`

**To Reproduce**
https://github.com/iphydf/repro1258
https://travis-ci.com/github/iphydf/repro1258/builds/154125901#L290

**Expected behavior**
Test passing.

**Environment**
 - OS name + version: Debian Buster
 - Bazel version: 2.2.0
 - Version of the rules: d59ccf9e7785553fd392924fb083d926c7e01134

**Additional context**
If you link the test directly to the cc_library, it works.

**Comment by iphydf** [comment]
Regarding the workaround at the bottom: if you *only* link the binary against the cc_library, it works, but if you link against the haskell_library as well, the same error occurs.

**Comment by aherrmann** [comment]
@iphydf Thanks for reporting this and for the detailed repro.

I was able to reproduce the issue and found a fix in https://github.com/tweag/rules_haskell/pull/1288. Could you verify that this fixes the issue for you?

**Comment by iphydf** [comment]
Thanks for the quick fix. Yes, this fixes the issue.

**Comment by aherrmann** [comment]
Great to hear, thanks for verifying!
