### ISSUE TITLE
Support for GHC 8.8.

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1290]
I'm using rules_haskell with ghc 8.8 since its release, minor some gotchas such as #1169 that I fixed locally.

However the current rules_haskell test base is not ported to ghc 8.6.

I've opened a PR in december to fix this: #1170, but I never had the time to finish it / was never prioritized.

**Comment by aherrmann** [comment]
rules_haskell has been [upgraded to GHC 8.8](https://github.com/tweag/rules_haskell/pull/1331). Windows is still on 8.6, but this is due to an [upstream issue](https://gitlab.haskell.org/ghc/ghc/issues/17926) unrelated to rules_haskell.
