### ISSUE TITLE
Personalize API documentation appearance

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#130]
Currently, the API documentation reuses the Bazel green. Could personalize by replacing the green with Haskell purple. Also, the spacing around horizontal rulers is too big, and the height of the footer is too large as well. These last changes could be upstreamed.

To do this, it will be better to import the skydoc code into the third_party folder, like they do in Go, than to keep it in a separate repo in a separate org like we have now. Either that or push a PR upstream to make the CSS customizable. That should be a simple change.

**Comment by mrkkrp** [comment]
I also think that the link to docs should be more prominently placed in the readme.
