### ISSUE TITLE
Support library dependencies in custom Cabal setup scripts

### ISSUE THREAD

**Issue by joprice** [tweag/rules_haskell#1314]
When trying to build polysemy using snapshot lts-15.9, I get the following error

```
.../polysemy-1.2.3.0/Setup.hs:1:1: error:
    Could not find module ‘Distribution.Extra.Doctest’
    Perhaps you meant Distribution.Simple.Doctest (from Cabal-3.0.1.0)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
1 | import Distribution.Extra.Doctest (defaultMainWithDoctests)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I think this is do to custom Setup.hs logic that requires the extra dependency on doctest. Is there a way to provide that or is there missing logic in the rules?

Environment
 - OS name + version: OSX 10.15.3 
 - Bazel version: 2.0.0
 - Version of the rules: cf6beb4e3748dce6dc401a95ab8cacb803c5d944

**Comment by aherrmann** [comment]
Looking at [`polysemi`'s Cabal file](https://hackage.haskell.org/package/polysemy-1.2.3.0/polysemy.cabal) it does list [`cabal-doctest`](https://hackage.haskell.org/package/cabal-doctest-1.0.5) in `setup-depends`. It seems that those dependencies are not listed by `stack`, so `stack_snapshot` doesn't pick them up automatically. You can try to add `cabal-doctest` to the `extra_deps` attribute of `stack_snapshot` for `polysemi`. I.e.
```
stack_snapshot(..., extra_deps = {"polysemi": ["@cabal-doctest"]})
```
In that case `@cabal-doctest//:cabal-doctest` would be an `http_archive` defining a `haskell_cabal_library` for `cabal-doctest`.

**Comment by joprice** [comment]
I tried that out and get this error:

```
Setup.hs: Encountered missing or private dependencies:
Cabal >=1.10 && <2.1, base >=4.3 && <4.11
```

Here are the relevant rules from my WORKSPACE:

```python
cabal_doctest_version = "1.0.6"

http_archive(
    name = "cabal-doctest",
    build_file_content = """
load(
  "@rules_haskell//haskell:cabal.bzl",
  "haskell_cabal_binary",
  "haskell_cabal_library",
)
load(
    "@rules_haskell//haskell:defs.bzl",
    "haskell_toolchain_library",
)
load("@stackage//:packages.bzl", "packages")

haskell_toolchain_library(name = "base")
haskell_toolchain_library(name = "Cabal")

haskell_cabal_library(
  name = "cabal-doctest",
  package_name = "cabal-doctest",
  srcs = glob(["**"]),
  visibility = ["//visibility:public"],
  version = "{version}",
  deps = packages["cabal-doctest"].deps,
)
    """.format(version = cabal_doctest_version),
    strip_prefix = "cabal-doctest-{}".format(cabal_doctest_version),
    sha256 = "decaaa5a73eaabaf3c4f8c644bd7f6e3f428b6244e935c0cf105f75f9b24ed2d",
    urls = [
        "https://hackage.haskell.org/package/cabal-doctest-{version}/cabal-doctest-{version}.tar.gz"
            .format(version = cabal_doctest_version)
    ],
)

stack_snapshot(
    name = "stackage",
    packages = [
        "base",
        "text",
        "Cabal",
        "directory",
        "filepath",
        "polysemy",
    ],
    vendored_packages = {"cabal-doctest": "@cabal-doctest"},
    snapshot = "lts-15.9",
    extra_deps = {"polysemy": ["@cabal-doctest"]}
)
```

**Comment by joprice** [comment]
I checked those constraints and tried building with lts-11.22, which seems to have the right ones, but I got the same error.

**Comment by joprice** [comment]
I updated cabal-doctest to 1.0.8 and now it builds, but the original error is back. It seems that extra_deps is not having any effect.

**Comment by mboes** [comment]
`extra_deps` is not sufficient. To support library dependencies in custom setup scripts, we would need to pass appropriate `-package-id` arguments to GHC when building the script. Otherwise GHC fails to build the setup script itself.

**Comment by patrickt** [comment]
This would be really good to have, as I can’t build http://github.com/tclem/lingo-haskell without it, which blocks http://github.com/github/semantic. Let me know if there’s anything I (a newbie to Bazel in general) can help.

**Comment by aherrmann** [comment]
@mboes IIUC then we would need to extend the calls to `runghc` [here](https://github.com/tweag/rules_haskell/blob/59200ae766f9efa63ad3a2dbd32694d24f0429b1/haskell/private/cabal_wrapper.py.tpl#L138) with additional `--ghc-arg=-package-id...` flags for such setup dependencies. We could add a `setup_deps` attribute to `haskell_cabal_binary|library` and `stack_snapshot` to let users define such setup dependencies.
