### ISSUE TITLE
Allow building GHC from source

### ISSUE THREAD

**Issue by hanshoglund** [tweag/rules_haskell#1319]
**Is your feature request related to a problem? Please describe.**

Allow using arbitrary commits from GHC repository (or forks) to pick compiler version. 

**Describe the solution you'd like**

Build GHC by invoking standard build system or Hadrian (or defer this to Nix).

Starting points:
- https://github.com/alpmestan/ghc.nix
- https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/ghc

**Describe alternatives you've considered**

**Additional context**

**Comment by mboes** [comment]
Could you describe how Nixpkgs doesn't already cover this case well? See e.g. https://github.com/tweag/asterius/blob/dba369825de8c14774aaf9bd1fe6af7c5f791ad7/WORKSPACE#L67-L79 for an example. The issue description as-is doesn't describe a problem. Another alternative, as yet unimplemented, which should be useful for the RBE case, is `ghc_register_host()`, which would use any toolchain provided by the host (like the native rules do by default and like rules_go allows). We should have a ticket for that.

I'm loath to hardcode in rules_haskell knowledge of Hadrian. GHC build systems come and go.

**Comment by mboes** [comment]
Created https://github.com/tweag/rules_haskell/issues/1320.

**Comment by hanshoglund** [comment]
If `haskell_register_ghc_nixpkgs` can build GHC from source that should cover everything I had in mind. Of course _someone_ needs to consume the GHC build system, but I'm more than happy to defer that work to nixpkgs :wink:.

Let's close this and discuss the RE case on the new ticket.
