### ISSUE TITLE
GHC > 8.6. Profiling build error with -optP-traditional

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1323]
**Describe the bug**

Profiling build with GHC 8.8 and 8.10 are not working anymore on my codebase.

`build build -c dbg //...` fails with the following:

```
cc1: error: command line option ‘-traditional’ is valid for the driver but not for C
cc1: error: command line option ‘-Xpreprocessor -DPROFILING’ is valid for the driver but not for C
`cc_wrapper-python' failed in phase `C Compiler'. (Exit code: 1)
```

**To Reproduce**

I rebased my `wip-ghc88` branch on top of `rules_haskell` master, I'm observing different errors, as well as the one depicted here:

```
$ git checkout wip-ghc88
$ nix-shell
$ bazel build -c dbg //tests/target-name/...
INFO: Analyzed 6 targets (0 packages loaded, 0 targets configured).
INFO: Found 6 targets...
ERROR: /home/guillaume/tweag/rules_haskell/tests/target-name/BUILD.bazel:17:1: HaskellBuildLibrary //tests/target-name:lib0-a_Aa failed (Exit 1) ghc_wrapper failed: error executing command bazel-out/host/bin/haskell/ghc_wrapper bazel-out/k8-dbg/bin/tests/target-name/compile_flags_lib0-a_Aa_HaskellBuildLibraryProf ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
cc1: error: command line option ‘-traditional’ is valid for the driver but not for C
cc1: error: command line option ‘-Xpreprocessor -DPROFILING’ is valid for the driver but not for C
`cc_wrapper-python' failed in phase `C Compiler'. (Exit code: 1)
INFO: Elapsed time: 0.368s, Critical Path: 0.28s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I'm also observing:

```
$ bazel build -c dbg @haskell_package_repository_dummy//:library-with-cbits
INFO: Analyzed target @haskell_package_repository_dummy//:library-with-cbits (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/guillaume/.cache/bazel/_bazel_guillaume/80819d925a91d7b49ed839165b536ee7/external/haskell_package_repository_dummy/BUILD:12:1: HaskellBuildLibrary @haskell_package_repository_dummy//:library-with-cbits failed (Exit 1) ghc_wrapper failed: error executing command bazel-out/host/bin/haskell/ghc_wrapper bazel-out/k8-dbg/bin/external/haskell_package_repository_dummy/compile_flags_library-with-cbits_HaskellBuildLibraryProf ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: fatal error: cannot specify ‘-o’ with ‘-c’, ‘-S’ or ‘-E’ with multiple files
compilation terminated.
`cc_wrapper-python' failed in phase `C Compiler'. (Exit code: 1)
Target @haskell_package_repository_dummy//:library-with-cbits failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.373s, Critical Path: 0.27s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

And 

```
bazel build -c dbg //tests:lz4
INFO: Analyzed target //tests:lz4 (0 packages loaded, 932 targets configured).
INFO: Found 1 target...
ERROR: /home/guillaume/tweag/rules_haskell/tests/BUILD.bazel:347:1: HaskellBuildLibrary //tests:lz4 failed (Exit 1) ghc_wrapper failed: error executing command bazel-out/host/bin/haskell/ghc_wrapper bazel-out/k8-dbg/bin/tests/compile_flags_lz4_HaskellBuildLibraryProf bazel-out/k8-dbg/bin/tests/extra_args_lz4_HaskellBuildLibraryProf

Use --sandbox_debug to see verbose messages from the sandbox
gcc: error: external/nixpkgs_lz4: No such file or directory
`cc_wrapper-python' failed in phase `C Compiler'. (Exit code: 1)
Target //tests:lz4 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.450s, Critical Path: 0.28s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

Last one: I had to kill `bazel build -c dbg //tests/library-empty/...` after 5 minutes.

Neither of these failures happen without `-c dbg`.

**Expected behavior**

I'd like it not to fail.

**Environment**
 - OS name + version: Linux NixOS nixos-unstable
 - Bazel version: the one with master: 2.1.0
 - Version of the rules: `master` + patchs: `d5428077ff503373b86f7d7009d0f205a707845f` (i.e. branch `wip-ghc88`.

**Additional context**

It may be related to upstream: https://gitlab.haskell.org/ghc/ghc/issues/17185 which details that the use of `-optP-traditional` generate part of the error. We are using `-optP-traditional` in rules_haskell. Removing `-optP-traditional` from here: https://github.com/tweag/rules_haskell/blob/827d654235189242b0a9d45df8bc8754469b4579/haskell/cc.bzl#L190 solves the first issue, but not the error about `-Xpreprocessor -DPROFILING`, I don't know what is the origin of this issue.

For the other issues, I don't know either, may be related to my poor patching of rules_haskell or may be something else.

**Comment by guibou** [comment]
I'm letting `//tests/library-empty/...` build for as long as it want to see if this is a kind of infinite loop, or if this is a just a huge regression on build time performances (such as #438 )

**Comment by guibou** [comment]
`[1 / 5] HaskellBuildBinary //tests/library-empty:library-empty; 42944s linux-sandbox`

Let assume that it is an infinite loop.

**Comment by aherrmann** [comment]
I can reproduce the issue locally. I tried to simply drop the `-Xpreprocessor` flags in the `cc_wrapper` in https://github.com/tweag/rules_haskell/compare/tweag:d542807...tweag:fb6fedc. With that I can successfully build all the four cases you list in debug mode:
```
bazel build -c dbg //tests/target-name/...
bazel build -c dbg @haskell_package_repository_dummy//:library-with-cbits
bazel build -c dbg //tests:lz4
bazel build -c dbg //tests/library-empty/...
```

I'm not saying dropping the flags is the right thing to do, but I'm not sure in which cases these preprocessor flags are needed, the following command succeeds with the preprocessor flags being dropped:
```
bazel build //tests/... -- -//tests/haskell_doctest/...
```

And the doctest failure seems unrelated
```
ERROR: /home/aj/tweag.io/da/bazel-projects/rules_haskell_ghc88/tests/haskell_doctest/BUILD.bazel:64:1: error executing shell command: '/nix/store/xrbcmmz7hssapnc13dmjds3x05z9lada-bash/bin/bash -c
        export LANG="C.UTF-8"
export LOCALE_ARCHIVE="external/glibc_locales/lib/locale/locale-archive"
        external/doctest/bin/doc...' failed (Exit 1)
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/haskell_doctest/compile-package_env-bin
doctest: <command line>: cannot satisfy -package-id testsZShaskellZUdoctestZSlib-a:
    testsZShaskellZUdoctestZSlib-a is unusable due to missing dependencies:
      base-4.13.0.0
```

It looks like this is more of a GHC issue than a `rules_haskell` issue. Not all `-Xpreprocessor` flags that cause issues are generated by `rules_haskell`. E.g.
```
cc1: error: command line option ‘-Xpreprocessor -DPROFILING’ is valid for the driver but not for C
```
which I don't see being generated in the `rules_haskell` repo.

**Comment by regnat** [comment]
> And the doctest failure seems unrelated

It's probably because your doctest is still built with ghc 8.6. I had a similar error because of that

**Comment by mboes** [comment]
I suggest that the next step is to minimize the issue to confirm that it's an upstream issue, and open a ticket there.

**Comment by guibou** [comment]
Note that support for profiling in rules_haskell for GHC 8.8 is important because slow profiling (described in #438) is not the case with GHC 8.8 (I just discovered that and I'm really happy).
