### ISSUE TITLE
GHC > 8.6: coverage build never terminate

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#1324]
**Describe the bug**

` bazel coverage //tests/two-libs/...` using the GHC 8.8 build depicted in #1323 never terminate.

**To Reproduce**

Checkout the ghc 8.8 rules_haskell depicted in #1323 and run `bazel coverage //tests/two-lib/...`.

**Expected behavior**

It should terminate (with hopefully a coverage report).

**Comment by aherrmann** [comment]
I can reproduce the issue locally. I tried the same patch as in https://github.com/tweag/rules_haskell/issues/1323, i.e. dropping `-Xpreprocessor` flags in `cc_wrapper` https://github.com/tweag/rules_haskell/compare/tweag:d542807...tweag:fb6fedc. With this patch `bazel coverage //tests/two-lib/...` terminates quickly and produces a coverage report in the test-log. It looks like this is the same underlying issue.

**Comment by aherrmann** [comment]
I've found a minimal reproduction with `ghc` outside of `rules_haskell` and reported it upstream: https://gitlab.haskell.org/ghc/ghc/issues/18177.

**Comment by guibou** [comment]
@aherrmann your diff + #1323 allows me to build my codebase with `-c dbg` and coverage without failure. I'll check if the resulting build are correct ASAP
