### ISSUE TITLE
bazel-runfiles package doesn’t return results correctly when invoked from Template Haskell

### ISSUE THREAD

**Issue by patrickt** [tweag/rules_haskell#1337]
**Describe the bug**
I’m trying to build [some source](https://github.com/github/semantic/blob/master/semantic-python/src/Language/Python/AST.hs) that accesses filesystem locations and generates code based on these files. (Gnarly, I know.) I ran into https://github.com/tweag/rules_haskell/issues/1246, which interfered with our approach up until now (using cabal’s `data-files`), so I thought I’d try the `haskell_library` function’s `data` field, accessing the paths with the `bazel-runfiles` package. Unfortunately, though this works inside REPLs and executables, it doesn’t appear to work from Template Haskell splices. The call to `getExecutableName` [here](https://github.com/tweag/rules_haskell/blob/master/tools/runfiles/src/Bazel/Runfiles.hs#L104) returns the path to the relevant `ghc` executable, which interferes when lookup up runfiles and their manifests.

**To Reproduce**
Call `Runfiles.rlocation` from a Template Haskell splice and observe the resulting error message.

**Expected behavior**

**Environment**
 - OS name + version: macOS catalina
 - Bazel version: 3.10
 - Version of the rules: 0.12

**Additional context**
I’m probably going to work around this with `file-embed` for the time being, but I figured I’d file it for posterity.

**Comment by aherrmann** [comment]
This is an interesting use-case. With `haskell_library|binary|test` you can use the [`extra_srcs`](https://api.haskell.build/haskell/defs.html#haskell_library-extra_srcs) attribute to make data files available during compile time. The test-suite contains an [example](https://github.com/tweag/rules_haskell/blob/59200ae766f9efa63ad3a2dbd32694d24f0429b1/tests/extra-source-files/BUILD.bazel) that uses such an extra source file with template Haskell. The example hard-codes the source file path for simplicity, however you can avoid that using Bazel's [location expansion](https://docs.bazel.build/versions/master/be/make-variables.html#predefined_label_variables) and `CPP`. E.g. something along the lines of

`BUILD.bazel`
```
haskell_library(
    name = "lib",
    srcs = ["Lib.hs"],
    extra_srcs = ["data-file"],
    compiler_flags = ['-DDATA_FILE="$(execpath :data-file)"'],
)
```

`Lib.hs`
```
{-# LANGUAGE CPP #-}
{-# LANGUAGE TemplateHaskell #-}

module Lib where

import Language.Haskell.TH
import Language.Haskell.TH.Syntax

embedFile :: Q Exp
embedFile path = do
  str <- runIO (readFile DATA_FILE)
  addDependentFile DATA_FILE
  [| str |]
```

The runfiles mechanism as it is currently implemented does not work for template Haskell at compile time. As you point out `getExecutableName` points to the compiler, but also the runfiles tree of `deps` is not an input to the compilation action. We wouldn't want to change this for the `deps` attribute as it would introduce (in most cases) unnecessary build dependencies, and even break some use-cases.

An idea that has been floating around is to have a separate attribute for template Haskell dependencies `th_deps`. This would allow us to not include `.a`/`.so` of regular `deps` into the build action, thereby thinning the dependency graph, and we could potentially include runfiles of `th_deps` into the build action similar to how we already do for preprocessors or plugins. That could make it possible to use runfiles in template Haskell at compile time.

However, given the current state, I would recommend `extra_srcs` for `haskell_library|binary|test` and `file-embed` for Cabal packages.

**Comment by patrickt** [comment]
Using the preprocessor trick worked great!

I think a `th_deps` attribute would be pretty neat, especially given our very specific TH requirements.

**Comment by aherrmann** [comment]
> Using the preprocessor trick worked great!

I'm glad to hear it :tada: 

> I think a `th_deps` attribute would be pretty neat, especially given our very specific TH requirements.

I've opened a tracking issue in https://github.com/tweag/rules_haskell/issues/1382.

**Comment by mboes** [comment]
Thanks @patrickt for helping us document in this issue tracker yet another reason for `thdeps` / `compile_deps` being a thing we want. :)

Should we close this issue in favour of #1382, or is there shorter term fix we could shoot for?

**Comment by patrickt** [comment]
I think we can close this in favor of #1382!
