### ISSUE TITLE
ghcide doesn't work for repl targets that use `experimental_from_binary`

### ISSUE THREAD

**Issue by regnat** [tweag/rules_haskell#1342]
I have an issue with this setup when trying to use ghcide with
1. A target that loads some `haskell_library` targets from binary (rather than from source)
2. When the given library targets haven't already been built (so might need to `bazel clean` first)

In that case I get an error about a missing `.so` file for the dependent library.

Running the repl target directly works fine otoh.

## To reproduce:

```shell
# Change the hie-bios target to one that loads a library from binary
sed -i 's#//tests:hie_bios#//tests/multi_repl:c_only_repl#' .hie-bios
# Clean the build as a dirty state might prevent the bug from happening
bazel clean
# Try to run ghcide (with a haskell file as argument as otherwise it hangs trying to list all the files in the bazel workspace)
./.ghcide tests/RunTests.hs
```

You should see an error of the form 

```
ghcide: <command line>: can't load .so/.DLL for: libHStestsZSmultiZUreplZSbcZSb.so (libHStestsZSmultiZUreplZSbcZSb.so: cannot open shared object file: No such file or directory)
```

Now if you run

```
# Build all the dependencies of the repl target
bazel build //tests/multi_repl/...
# Run ghcide again. That time it properly display errors in the file
./.ghcide tests/RunTests.hs
```

then everything works

## More context

I tried to debug this, it looks like the `.so` file is here, but has a `-ghc8.6.5` suffix which confuses ghcide (but not ghci apparently).
According to strace, the fact that it works if the dependent library has been built seems to be an impurity due to the fact that building the library yields a static library that doesn't have the `-ghc8.6.5` suffix (and so ghcide finds the static library and is happy with it).

Possibly this is liked to #1334 as the symptoms are quite similar

**Comment by regnat** [comment]
(note that all this is on top of #1262 as otherwise ghcide isn't setup for the repository)

**Comment by aherrmann** [comment]
I can reproduce this issue locally. Prefixing the `ghcide` invocation with the following `strace` command
```
/usr/bin/strace -s 10000 -f -A -o /tmp/ghcide.strace -e trace=%file
```
shows that `ghcide` is indeed not looking for a file with the `-ghc8.6.5` suffix. It's also not looking for a `.so` file in the expected locations:

```
31172 stat("bazel-out/k8-fastbuild/bin/tests/multi_repl/bc/HStestsZSmultiZUreplZSbcZSb.o", 0x420152c8b0) = -1 ENOENT (No such file or directory)
31172 stat("bazel-out/k8-fastbuild/bin/tests/multi_repl/bc/libHStestsZSmultiZUreplZSbcZSb.a", 0x420152cb10) = -1 ENOENT (No such file or directory)
31172 stat("bazel-out/k8-fastbuild/bin/tests/multi_repl/bc/HStestsZSmultiZUreplZSbcZSb.a", 0x420152cd80) = -1 ENOENT (No such file or directory)
31172 stat("bazel-out/k8-fastbuild/bin/tests/multi_repl/bc/libHStestsZSmultiZUreplZSbcZSb", 0x4201559010) = -1 ENOENT (No such file or directory)
31172 stat("bazel-out/k8-fastbuild/bin/tests/multi_repl/bc/HStestsZSmultiZUreplZSbcZSb", 0x4201559280) = -1 ENOENT (No such file or directory)
31447 openat(AT_FDCWD, "/nix/store/js28swbiimjvd139x6kr7nc68s81fdg6-gmp-6.2.0/lib/libHStestsZSmultiZUreplZSbcZSb.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31447 openat(AT_FDCWD, "/nix/store/dfs0i8z58m64zak8102hf7g0w9skhdw6-libffi-3.3/lib/libHStestsZSmultiZUreplZSbcZSb.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31447 openat(AT_FDCWD, "/nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libHStestsZSmultiZUreplZSbcZSb.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31447 openat(AT_FDCWD, "/nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
31447 openat(AT_FDCWD, "/nix/store/an6bdv4phxsz14q2sk57iscl2dc7bnj1-glibc-2.30/lib/libHStestsZSmultiZUreplZSbcZSb.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

> Possibly this is liked to #1334 as the symptoms are quite similar

I've tried adding the [`resolved_symlink_dynamic_library`](https://docs.bazel.build/versions/master/skylark/lib/LibraryToLink.html#resolved_symlink_dynamic_library) to the [`inputs`](https://github.com/tweag/rules_haskell/blob/6c0ed78eb4a78df9b55c4cf65fbc6174dc7257c8/haskell/repl.bzl#L281) but it didn't change the outcome.

**Comment by aherrmann** [comment]
The issue here seems to be that `ghcide` is built as a static binary and so uses the static RTS. In the static RTS GHCi's linker will not look for dynamic libraries of the form `libHSfoo-ghc8.6.5.so`, but only for static libraries of the form `libHSfoo.a`. Oddly enough it also looks for `libHSfoo.so`.

Providing static archives for `hie_bios` outputs solves the issue. See https://github.com/tweag/rules_haskell/commit/bf5f00afaeeff7cd1f6b520aea31be29ed64d815

**Comment by regnat** [comment]
Awesome, I confirm that this fixes it for me too :fireworks: 

Thanks. I'll wait for #1262 to be merged and then close this
