### ISSUE TITLE
make-style variables don’t appear to be expanded in repl_ghci_args 

### ISSUE THREAD

**Issue by patrickt** [tweag/rules_haskell#1377]
**Describe the bug**
In order to pass a file path to the C preprocessor, I define it using a `-D` style macro in `compiler_flags`, containing an invocation of `$(rootpath ...)`. This works fine when building the standard target, but the expansion doesn’t seem to take place with `repl_ghci_args`, even though the docs say that Make-style substitution occurs on `repl_ghci_args`, and I’m [specifying it here](https://github.com/github/semantic/blob/aa11f3630dbbb8221cff51278543713c8f809eb7/build/common.bzl#L57-L62).

**To Reproduce**
1. Check out `git@github.com:github/semantic.git` and the `bazel-experiments` branch.
2. Run `bazel build //semantic-python:lib` and observe everything working.
3. Run `bazel run //semantic-python:lib@repl` and observe that the preprocessor macro `NODE_TYPES_PATH` has not expanded its `rootpath`.

**Expected behavior**
The given macro should not be `../../../../$(rootpath @tree-sitter-python//:src/node-types.json)`
I looked through `haskell_impl.bzl` in this repo and observed that `expand_make_variables` exists; is it a matter of calling that? Is it possible for me to do that manually from my build script?

**Environment**
 - OS name + version: macOS Catalina
 - Bazel version: 3.1.0
 - Version of the rules: 0.12

**Comment by aherrmann** [comment]
@patrickt Thanks for reporting this and for the detailed issue description. This is indeed a bug in `haskell_repl`, #1381 should fix it.

> I looked through `haskell_impl.bzl` in this repo and observed that `expand_make_variables` exists; is it a matter of calling that? Is it possible for me to do that manually from my build script?

That's exactly right, `haskell_repl` wasn't calling `expand_make_variables` on `ghci_repl_args`. This cannot be done externally from the BUILD file but has to be done in the implementation in rules_haskell. #1381 addresses this.

**Comment by patrickt** [comment]
@aherrmann You are so awesome. Thanks a ton.
