### ISSUE TITLE
`haskell_lint_aspect` is not exported

### ISSUE THREAD

**Issue by patrickt** [tweag/rules_haskell#1378]
**Describe the bug**
The documentation says that an invocation of this shape should enable linting:

```
bazel build //my/haskell:target \
    --aspects @rules_haskell//haskell:defs.bzl%haskell_lint_aspect
```

But running it on my repo, I encounter

```
ERROR: haskell_lint_aspect is not exported from @rules_haskell//haskell:repl.bzl
ERROR: Analysis of aspect '@rules_haskell//haskell:repl.bzl%haskell_lint_aspect of //semantic-source:semantic-source' failed; build aborted: haskell_lint_aspect is not exported from @rules_haskell//haskell:repl.bzl
```

In addition, the docs mention the `haskell_lint` rule, which doesn’t appear to be present (in v0.12, at least). 

I feel like I might be missing something obvious—sorry if this is the case!

**Comment by aherrmann** [comment]
Unfortunately, the documentation is out-of-date in that aspect, sorry about that. The old lint aspect and rule was removed in https://github.com/tweag/rules_haskell/pull/931. As described there it had several issues, mainly that it was a build target when it should have been a test target. The same effect as that rule can be achieved with the `compiler_flags` attribute.

I've opened a PR that updates the documentation https://github.com/tweag/rules_haskell/pull/1384
