### ISSUE TITLE
bazel run @stackage-unpinned//:pin doesn’t create output JSON

### ISSUE THREAD

**Issue by patrickt** [tweag/rules_haskell#1397]
**Describe the bug**
Hey all 👋 I hope I’m not missing something really obvious here, but I’ve been trying to use a stack snapshot in the Semantic repository, and I’ve run into a curious behavior—running `bazel run @stackage-unpinned//:pin` doesn’t generate the `stackage_snapshot.json` output I was expecting. I do see a lot of `SHA256` info calls from the script, and according to Bazel the `pin` script is being run:

```
INFO: Build completed successfully, 2 total actions
INFO: Running command line: bazel-bin/external/stackage-unpinned/pin
INFO: Build completed successfully, 2 total actions
```

But beyond that there doesn’t seem to be any JSON generated, and as such specifying `stack_snapshot_json` in my `WORKSPACE` fails.

As I mentioned, I feel like I’m missing something really obvious, so please forgive me if so!

**To Reproduce**
Check out `https://github.com/github/semantic.git` and run the above command.

**Expected behavior**
I expected to see some stackage_snapshot.json file emerge.

**Comment by aherrmann** [comment]
Hi @patrickt,
I'm afraid I can't reproduce the issue locally. I checked out https://github.com/github/semantic/commit/6fb75b78b7fdd9d7d6bb03e5a11a04f287a7f4e2 (`master` at the time of writing) and ran the following command which produced the shown output
```
$ bazel run @stackage-unpinned//:pin
...
INFO: SHA256 (https://api.github.com/repos/commercialhaskell/all-cabal-hashes/git/ref/heads/hackage) = 07416960e43a66b1e49c78422d483a02296e53eed2a7d771c49e69f002c34b79
...
INFO: SHA256 (https://raw.githubusercontent.com/commercialhaskell/all-cabal-hashes/17d8ea9ec20e36cc6033020673f92f6cb0801f42/yaml/0.11.4.0/yaml.cabal) = 2583bfc6ea297290fa1bae47242627898896e2647aaaf7662d6d7df9a2dac0b2
INFO: Analyzed target @stackage-unpinned//:pin (24 packages loaded, 62 targets configured).
INFO: Found 1 target...
Target @stackage-unpinned//:pin up-to-date:
  bazel-bin/external/stackage-unpinned/pin
INFO: Elapsed time: 146.553s, Critical Path: 0.04s
INFO: 0 processes.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
Successfully pinned resolved artifacts for @stackage in stackage_snapshot.json.
This file should be checked in your version control system.

Next, please update your WORKSPACE file by adding the stack_snapshot_json attribute.
For example:

=============================================================

stack_snapshot(
    packages = ...,
    snapshot = ...,
    stack_snapshot_json = "//:stackage_snapshot.json",
)

=============================================================

To update stackage_snapshot.json, run this command to re-pin the unpinned repository:

    bazel run @stackage-unpinned//:pin

```
The file `stackage_snapshot.json` was created as expected and configuring the `stack_snapshot_json` attribute yields the expected behavior.

I tested this on Ubuntu 19.10 with Bazel version 3.1.0, AFAIK that's the Bazel version that's used on semantic's CI.

---

Did it produce any additional output for you beyond the following?
```
INFO: Build completed successfully, 2 total actions
INFO: Running command line: bazel-bin/external/stackage-unpinned/pin
INFO: Build completed successfully, 2 total actions
```

To debug this issue further, could you edit `bazel-bin/external/stackage-unpinned/pin`, introduce `set -x` in the top of the script, execute the following command from the repository root and share the output here?
```
$ BUILD_WORKSPACE_DIRECTORY="$PWD" bazel-bin/external/stackage-unpinned/pin
```

**Comment by patrickt** [comment]
Good news: I got it working! I took your advice and ran 

`bazel-bin/external/stackage-unpinned/pin`

(By the way, this is on macOS Catalina, with bash 3.2.57. I’m running fish as my main shell but I don’t think that’s relevant.)

And what I noticed, looking at the source, was that the code that should explain an unset `BUILD_WORKSPACE_DIRECTORY` did not run. Instead, I got this error:

`line 4: BUILD_WORKSPACE_DIRECTORY: unbound variable`

I found this pretty mysterious, so in a spirit of experimentation, I tried removing the `set -euo pipefail` on line 3, in case it would make the check for an unbound variable less stringent. And at that point it just… started working! Could this be a byproduct of the fact that macOS ships a criminally-old version of bash by default?

**Comment by aherrmann** [comment]
Good catch! That line was left at the beginning of the script in error and should only be present after the runfiles library discovery. This seems to be a MacOS (or rather bash 3.2.57) peculiarity. On MacOS `set -e` causes runfiles discovery to fail on `source /dev/null/bazel_tools/...` despite the following `||`, on Linux (bash version 5.0.3) it doesn't fail. #1398 removes that line.
