### ISSUE TITLE
Supported versions range from 2.1.0 to 2.1.0, but found: 3.3.1

### ISSUE THREAD

**Issue by teto** [tweag/rules_haskell#1400]
**Describe the bug**
In an attempt to fix a docker issue, I bumped various packages (including bazel) and see this warning:
`bazel version is too recent. Supported versions range from 2.1.0 to 2.1.0, but found: 3.3.1`

So far it looks fine, but I wonder if there was anything to be wary of ?

**Comment by Profpatsch** [comment]
> So far it looks fine, but I wonder if there was anything to be wary of ?

It just means we haven’t tested `rules_haskell` with 3.3.1 yet. However, upstream informs us if `rules_haskell` does not build against bazel `master`, so in practice `rules_haskell` master should always be mostly compatible with the latest bazel release. Maybe we should remove the warning for the upper version bound.

**Comment by teto** [comment]
thats what I thought. I will report back if I see any issue
