### ISSUE TITLE
Test multiple Bazel versions on CI

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#1402]
**Is your feature request related to a problem? Please describe.**
Currently rules_haskell CI only tests one Bazel version. If we claim to support a range of Bazel versions, then we should test this on CI.

**Describe the solution you'd like**
The CI pipelines (or at least a relevant subset of them) should be tested with multiple Bazel versions to ensure that the claimed supported range of versions is indeed supported. 

**Describe alternatives you've considered**
We could stick to what we're doing right now. Only test one version on CI and view the range of supported versions that is checked against as a range of versions without known issues.

We could only officially support the one Bazel version that we are testing on CI. However, in this case the version range warning doesn't provide much value anymore and is likely to be a nuisance to many users.

**Additional context**
The discussion in https://github.com/tweag/rules_haskell/pull/1395.

**Comment by mboes** [comment]
Something that's left implicit above: we only need to test multiple *major* versions of Bazel. So long as we trust Bazel developers to not introduce any breaking changes in minor releases (I think that's a fair assumption to make).
