### ISSUE TITLE
Trouble getting autoexporter plugin to work

### ISSUE THREAD

**Issue by codygman** [tweag/rules_haskell#1448]
I believe this is just user error and not a bug, but would appreciate help.

I have the following code that uses the [autoexporter plugin](https://www.stackage.org/package/autoexporter):

```bazel
ghc_plugin(
    name = "autoexporter_plugin",
    module = "Autoexporter",
    deps = ["@stackage//:autoexporter"],
)

haskell_library(
    name = "mylib",
    srcs = glob(['library/*.hs']),
    plugins = [":autoexporter_plugin"],
```

Modules call autoexporter like this:

```haskell
{-# OPTIONS_GHC -F -pgmF autoexporter #-}
```

After browsing through issues it seems that the `deps = ["@stackage//:autoexporter"],` piece in my ghc_plugin stanza should be valid but I'm most suspicious of it.

At some point while trying things I got a `plugin does not export 'plugin'` error. This is true, autoexporter exports the function `Autoexporter.autoexporter` and not `Autoexporter.plugin`. 

Could that be the problem?

**Comment by codygman** [comment]
I just reproduced this in https://github.com/codygman/ichor/commit/1f254c3555e33fa7c59405f064253a7bcf43dcec and here is the [associated github action run](https://github.com/codygman/ichor/runs/1455463535?check_suite_focus=true)

The error is:

```

[cody@nixos:~/code/ichor]$ nix-shell --pure --run "bazel build ..."
/nix/store/frh7ir9rcv19b3ym33ck64s813yr3xrr-stdenv-linux/setup: line 99: /nix/store/rilgkl1dzrzlh8fn846wr2p7xzv1xlv6-bazel-3.3.1/share/bash-completion/completions/bazel: No such file or directory
Loading: 
Loading: 0 packages loaded
Analyzing: 4 targets (1 packages loaded, 0 targets configured)
Analyzing: 4 targets (4 packages loaded, 12 targets configured)
INFO: Analyzed 4 targets (5 packages loaded, 84 targets configured).
INFO: Found 4 targets...
[0 / 5] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[63 / 69] HaskellCabalLibrary @stackage//:autoexporter; 1s linux-sandbox
[64 / 69] [Prepa] action 'SolibSymlink _solib_k8/external_Sstackage/libHSautoexporter-1.1.18-ghc8.10.1.so'
ERROR: /home/cody/code/ichor/BUILD.bazel:15:15: HaskellBuildBinary //:ichor failed (Exit 1) ghc_wrapper failed: error executing command bazel-out/host/bin/external/rules_haskell/haskell/ghc_wrapper bazel-out/k8-fastbuild/bin/compile_flags_ichor_HaskellBuildBinary bazel-out/k8-fastbuild/bin/extra_args_ichor_HaskellBuildBinary

Use --sandbox_debug to see verbose messages from the sandbox
<command line>: The module Autoexporter did not export the plugin name Autoexporter.plugin
INFO: Elapsed time: 4.229s, Critical Path: 2.95s
INFO: 1 process: 1 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

Can I specify something other than `plugin`?

**Comment by codygman** [comment]
I guess this isn't a valid plugin since it doesn't export `plugin` per [the docs](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/extending_ghc.html#writing-compiler-plugins).

Is there another way to use this preprocessor or should I just make an issue there to rename autoexporter to plugin? I'm not sure if this issue is common enough for rules_haskell to worry about.

**Comment by mboes** [comment]
It appears that autoexporter is not a GHC plugin. It's a pre-processor. Those are handled using the `tools` attribute. See https://github.com/tweag/rules_haskell/blob/master/tests/binary-with-tool/BUILD.bazel#L18-L19 for an example. If you're comfortable with running `autoexporter` as a pre-processor on all source files, then you don't need a per-file `OPTIONS_GHC` pragma, and you also don't need `{-# LANGUAGE CPP #-}`. In that case, you could simply:

```python
haskell_binary(
  name = "ichor",
  compiler_flags = ["-F", "-pgmF", "$(location @stackage-exe//autoexporter)"],
  tools = ["@stackage-exe//autoexporter"],
  ...
)
```

Notice that `autoexporter` is an executable. See the [documentation](https://api.haskell.build/haskell/cabal.html#stack_snapshot) for `stack_snapshot` for how to build executables from Stackage snapshot.

Note: I do get an obscure error when running `autoexporter` as a pre-processor, but that one appears to be application-specific:

```
autoexporter: library/Mod1: getDirectoryContents:openDirStream: does not exist (No such file or directory)

library/Mod1.hs:1:1: error:
    `autoexporter' failed in phase `Haskell pre-processor'. (Exit code: 1)
```

**Comment by codygman** [comment]
> It appears that autoexporter is not a GHC plugin. It's a pre-processor. Those are handled using the `tools` attribute. See https://github.com/tweag/rules_haskell/blob/master/tests/binary-with-tool/BUILD.bazel#L18-L19 for an example. If you're comfortable with running `autoexporter` as a pre-processor on all source files, then you don't need a per-file `OPTIONS_GHC` pragma, and you also don't need `{-# LANGUAGE CPP #-}`. In that case, you could simply:
> 
> ```python
> haskell_binary(
>   name = "ichor",
>   compiler_flags = ["-F", "-pgmF", "$(location @stackage-exe//autoexporter)"],
>   tools = ["@stackage-exe//autoexporter"],
>   ...
> )
> ```
> 
> Notice that `autoexporter` is an executable. See the [documentation](https://api.haskell.build/haskell/cabal.html#stack_snapshot) for `stack_snapshot` for how to build executables from Stackage snapshot.
> 
> Note: I do get an obscure error when running `autoexporter` as a pre-processor, but that one appears to be application-specific:
> 
> ```
> autoexporter: library/Mod1: getDirectoryContents:openDirStream: does not exist (No such file or directory)
> 
> library/Mod1.hs:1:1: error:
>     `autoexporter' failed in phase `Haskell pre-processor'. (Exit code: 1)
> ```

Thank you! You are correct about assuming application error. I'll try this out as soon as I can, closing for now.
