### ISSUE TITLE
GHC 7.6.3 not supported

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#146]
https://travis-ci.org/iphydf/repro139/jobs/343824600#L639

`ghc: unrecognised flags: -dynamic-too -this-unit-id`

**Comment by Fuuzetsu** [comment]
I don't think there's a plan to support 7.6.3. It's soon going to be 5 years old. I think it wouldn't be too hard if we wanted to though, we have the version in bazel.

**Comment by iphydf** [comment]
The main advantage for me is that it comes with Ubuntu Trusty, which is the latest version available on Travis. Downloading newer versions from launchpad takes 2-3 minutes of extra time, which really hurts when the total build time is 2-3 minutes. For my repro cases for #140 and #139, I had to add sudo (+45 seconds build time) and hvr-ghc (+3 minutes build time). The rest of the build time is about 1-2 minutes, so it's dominated by downloads that could be 10 seconds if it were ghc 7.6.3.

**Comment by mboes** [comment]
That makes sense. We're unlikely to work on this short term, but feel free to have a crack at it.

**Comment by iphydf** [comment]
haskell_bindist made this not very important. Travis cache works fine for this.
