### ISSUE TITLE
regarding src_strip_prefix and IDE configuration (haskell-language-server)

### ISSUE THREAD

**Issue by teto** [tweag/rules_haskell#1473]
Follow up of https://github.com/mpickering/hie-bios/issues/275 

src_strip_prefix is marked as deprecated (thus it's undocumented https://api.haskell.build/haskell/defs.html#haskell_binary-src_strip_prefix) but it is really useful when interfacing with haskell-language-server.

Is there any replacement ?
I've noticed that due to a bug in our project, we could end up with inexistant paths in the final exported flag `-iproject/a/b/c/a/b` when only project/a/b exists.

I am not familiar enough with haskell to understand how bazel can get rid of the haskell conventions regarding module naming: like our project has plenty of haskell modules A.B that are for instance in folders A/X/B (so they should be named A.X.B). While this works with rule_haskells it generates issues with haskell-language-server. Any way to enforce the same behavior in rules_haskell ?

Thanks @aherrmann for saving

**Comment by teto** [comment]
closing as a duplicate (github 404)

**Comment by aherrmann** [comment]
> closing as a duplicate (github 404)

Looks like something went wrong with the reference. The duplicate seems to be https://github.com/tweag/rules_haskell/issues/1474
