### ISSUE TITLE
src_strip_prefix and IDE configuration (haskell-language-server)

### ISSUE THREAD

**Issue by teto** [tweag/rules_haskell#1474]
Follow up of https://github.com/mpickering/hie-bios/issues/275 

src_strip_prefix is marked as deprecated (thus it's undocumented https://api.haskell.build/haskell/defs.html#haskell_binary-src_strip_prefix) but it is really useful when interfacing with haskell-language-server.

Is there any replacement ?
I've noticed that due to a bug in our project, we could end up with inexistant paths in the final exported flag `-iproject/a/b/c/a/b` when only project/a/b exists.

I am not familiar enough with haskell to understand how bazel can get rid of the haskell conventions regarding module naming: like our project has plenty of haskell modules A.B that are for instance in folders A/X/B (so they should be named A.X.B). While this works with rule_haskells it generates issues with haskell-language-server. Any way to enforce the same behavior in rules_haskell ?

Thanks @aherrmann for saving my a** more than once :)

EDIT:  also I always get the src folder twice, when is the 2nd one useful ? 
+-iproject/core/test
+-ibazel-out/k8-fastbuild/bin/project/core/test
EDIT2: you explained it already in my first link: `Generated files are found under the bin dir, e.g. bazel-out/k8-fastbuild/bin/src/Some/Module.hs. Some Haskell source files could be generated, so we add both types of paths to the import dirs, see here (src_root).`

**Comment by aherrmann** [comment]
> Is there any replacement ?

We don't have a replacement for the hls/ghcide use-case in place at the moment. A possible alternative approach is proposed in  https://github.com/tweag/rules_haskell/pull/1281. That PR does not touch on `src_strip_prefix` and the IDE use-case, yet. But it enforces strict rules on how filenames and module names need to correspond and can be used to infer correct `-i` flags for the IDE use-case.

For the REPL use-case we have recently removed the need for `src_strip_prefix` as it was causing issues with targets with overlapping `src_strip_prefix`. See https://github.com/tweag/rules_haskell/pull/1345.

**Comment by teto** [comment]
thanks for the help, we fixed our issue here.
