### ISSUE TITLE
curl https://haskell.build/start | sh doesn't support Bazel v0.10.0

### ISSUE THREAD

**Issue by jystic** [tweag/rules_haskell#148]
When I try to follow the readme instructions using the latest bazel I get this error message:
```
$ curl https://haskell.build/start | sh
Need at least Bazel v0.8.0. v0.10.0 detected.
```

Looks like string comparison maybe? /rampant speculation

**Comment by mboes** [comment]
The comparison is a little smarter than just string comparison, but clearly it's not understanding how numbers work well enough yet. :)
