### ISSUE TITLE
Build Event Protocol upload failed

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#1498]
We're occasionally encountering [build event log upload timeouts](https://github.com/tweag/rules_haskell/pull/1493/checks?check_run_id=1887763034#step:7:720) of the form:

```
ERROR: The Build Event Protocol upload failed: All retry attempts failed. DEADLINE_EXCEEDED: DEADLINE_EXCEEDED: deadline exceeded after 14999958197ns DEADLINE_EXCEEDED: DEADLINE_EXCEEDED: deadline exceeded after 14999958197ns
```

These end up failing the build. A rerun typically fixes those.

These issues have been encountered on different Bazel versions:

- [Bazel version 3.3.1](https://github.com/tweag/rules_haskell/pull/1493/checks?check_run_id=1887763034#step:7:720)
  The [closest streaming URL](https://github.com/tweag/rules_haskell/pull/1493/checks?check_run_id=1887763034#step:7:299) shows [Invocation not found!](https://app.buildbuddy.io/invocation/d2b02f59-1064-40f4-8adc-f5f6a63e1ed3)
- [Bazel version 3.7.2](https://github.com/tweag/rules_haskell/runs/1927331499#step:7:737)
  The [closest streaming URL](https://github.com/tweag/rules_haskell/runs/1927331499#step:7:313) shows [Invocation not found!](https://app.buildbuddy.io/invocation/e30a7022-9c84-4b1b-9ffe-84d9f6c59b5f).
- [Bazel version 4.4.0](https://github.com/tweag/rules_haskell/pull/1497/checks?check_run_id=1937093005#step:7:743)
  The [closest streaming URL](https://github.com/tweag/rules_haskell/pull/1497/checks?check_run_id=1937093005#step:7:317) shows [Invocation not found!](https://app.buildbuddy.io/invocation/3832fd8b-f0b7-41f0-b040-cc52937b7ec2)

The issue was previously discussed around https://github.com/tweag/rules_haskell/pull/1493#issuecomment-778324601.

The instances listed above and others I found at a cursory look only occurred on the Linux nixpkgs CI pipeline. It may be that this issue is specific to Nix provided Bazel. Please report if you encounter an instance on a different configuration, e.g. a bindist or macOS pipeline.

**Comment by aherrmann** [comment]
@siggisim I encountered another instance of `deadline exceeded after 14999958197ns DEADLINE_EXCEEDED`, this time on Bazel 4.0.0. (Previously discussed on https://github.com/tweag/rules_haskell/pull/1493#issuecomment-778324601). I've created this dedicated issue to not spread the discussion around too much. See details above.

A noteworthy point: In all instances the closest streaming URL I find by scrolling up in the build log leads to an "Invocation not found!" page. (Our CI pipeline has multiple Bazel invocations, so we end up with multiple streaming URLs in one CI log)

**Comment by siggisim** [comment]
The multiple Bazel invocation datapoint is very interesting, specifically that it always seems to fail on the second invocation. When I previously searched server logs for the invocations - I was searching the first invocation. The second invocation never seems to hit our servers. 

By default, Bazel will try to re-use the build event stream connection across invocations - which could be leading to the issues we're seeing here. You can disable this behavior with the bazel flag `--keep_backend_build_event_connections_alive=false`. I suspect that might solve this issue.

**Comment by aherrmann** [comment]
@siggisim Thank you for the suggestion. That flag seems to resolve the issue for us. At least I got three consecutive runs of the previously failing pipeline without the issue occurring.
