### ISSUE TITLE
Support Cabal named libraries

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#1506]
**Is your feature request related to a problem? Please describe.**
Recent versions of Cabal support defining multiple libraries in a package. These additional libraries must be named. Compiling packages with named libraries fails. See #1439 for an example.

**Describe the solution you'd like**
Make it possible to build packages that define multiple libraries. Unclear how to do this without substantial changes to [`haskell/cabal.bzl`](https://github.com/tweag/rules_haskell/blob/master/haskell/cabal.bzl). If Stack can give us a list of *components*, rather than a list of packages when constructing a build plan, then we could add a `component` attribute to `haskell_cabal_library` and make each `haskell_cabal_library` (each with a separate value for `component`) depend on each other.

**Additional context**
See #1439.

**Comment by aherrmann** [comment]
> If Stack can give us a list of _components_, rather than a list of packages when constructing a build plan, then we could add a `component` attribute to `haskell_cabal_library` and make each `haskell_cabal_library` (each with a separate value for `component`) depend on each other.

Relevant upstream feature request from a while ago: https://github.com/commercialhaskell/stack/issues/5275

**Comment by ylecornec** [comment]
Yes I think. Choosing the component we want to build with `haskell_cabal_library` is possible with the `sublibrary_name` attribute.
And if using `stack_snapshot`, the components and their dependencies can be manually specified via the `components` and `components_dependencies` attributes.
