### ISSUE TITLE
Support for (commit version or other build-time info) stamping?

### ISSUE THREAD

**Issue by stevana** [tweag/rules_haskell#1520]
I'd like to include the git commit at build-time of my binary, so that I can see it at run-time when the `--version` flag passed.

In `rules_go` there's [x_defs](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#defines-and-stamping) which makes this possible.

Is there a way to achieve this with `rules_haskell`?

**Comment by aherrmann** [comment]
@stevana There's no direct support for stamping in `compiler_flags`. However, there are ways to achieve this. E.g. you could write a rule that reads the stable-status file and generates a Haskell source file that exposes the git revision as a constant.

**Comment by stevana** [comment]
Thanks for the pointer. I managed to make some progress with:

```python
genrule(
    name = "version",
    srcs = [],
    outs = ["src/Version.hs"],
    cmd = ";".join([
        "( echo 'module Version where'",
        "echo 'version :: String'",
        "echo -n 'version = \"'",
        "awk '/STABLE_GIT_COMMIT/ { printf $$2 }' bazel-out/stable-status.txt",
        "echo '\"'",
        ") > \"$@\"",
    ]),
    stamp = True,
    message = "Generating version file",
    visibility = ['//visibility:public'],
)
```

and adding `":version"` to `"deps"` of my `haskell_library`.

While this works in `bazel`, it will break `cabal` because that module is missing there. I tried add the `Version.hs` to the source tree so that it compiles with `cabal` as well, but then `bazel` complains saying it cannot write that file because it already exists. I tried looking into patching the file rather than writing it from `bazel` but that wasn't easy either without changing its name.

And then tried to write the version to a `data/version.txt` file instead and use `getDataFileName` to retrieve it version, but when compiling with `bazel` `ghc` complains that the `Paths_...` module (where `getDataFileName` lives) doesn't exist.

First of all, is this the approach you had in mind? Second, does one need to do something special with the `Paths_` module, or is there a better way to deal with this entirely?

Cheers!

**Comment by stevana** [comment]
In the end, I solved it as follows:

```haskell
-- When building with Bazel we generate a module containing the git commit hash
-- at compile-time.
#ifdef __BAZEL_BUILD__
import Version
-- When building with cabal/nix we expect the git commit hash to be passed in via
-- CPP flags, i.e. `--ghc-option=-D__VERSION__=\"X\"`.
#elif defined __VERSION__
version :: String
version = __VERSION__
#else
version :: String
version = "unknown"
#endif
```
In `haskell_binary` in bazel set `compiler_flags = ["-D__BAZEL_BUILD__"]` and in nix set `configureFlags = [ "--ghc-option=-D__VERSION__=\"${nixpkgs.lib.commitIdFromGitRepo ./../../.git}\"" ];`.

**Comment by aherrmann** [comment]
> First of all, is this the approach you had in mind?

Yes, that's what I had in mind.

> Second, does one need to do something special with the `Paths_` module, or is there a better way to deal with this entirely?

The `Paths_` module is a Cabal specific feature. rules_haskell's `haskell_library|binary|test` rules do not generate such a module since data file dependencies are managed differently under Bazel. I.e. using the `data` attribute and the runfiles library.

The solution you found looks perfectly valid to me. Another option would be to have two different versions of the same module, `cabal/Version.hs` and `bazel/Version.hs` and only include the `cabal/` one in the Cabal build and only the `bazel/` one in the Bazel build. It's essentially moving the `#ifdef __BAZEL_BUILD__` switch from CPP into your Cabal pacakge/Bazel build definition.
