### ISSUE TITLE
Using remote caching in CI when cross-compiling slows downs the builds

### ISSUE THREAD

**Issue by facundominguez** [tweag/rules_haskell#1524]
**Describe the bug**

Using remote caching in the Cross CI job grows the build time from 8 minutes to 40!

**To Reproduce**

Have the Cross job in CI use remote-caching. At the time of this writing, this can be achieved by changing `--config=ci-common` to `--config=ci` in the [job configuration](https://github.com/tweag/rules_haskell/blob/24049177bc8da2fb0c0bdc15f88f11f49f8bbdda/.github/workflows/workflow.yaml#L80).

**Expected behavior**

Remote caching would take only marginally more time to build or less than without remote caching.

**Additional notes**

Enabling build events reporting (`--bes_*` flags) already slows down the cross job some three minutes, but perhaps this is acceptable (the 8 minutes above already include build events reporting).

**Comment by aherrmann** [comment]
@facundominguez Do you have a link to a GH actions run where this took long? Would be interesting to see what the corresponding buildbuddy logs look like.

**Comment by facundominguez** [comment]
I just tried to reproduce it and failed: https://github.com/tweag/rules_haskell/compare/fd/remote-caching-cross
Here's a link to the behavior I was seeing a couple of weeks ago: https://github.com/tweag/rules_haskell/runs/2250613866?check_suite_focus=true

**Comment by aherrmann** [comment]
@facundominguez If I understand those logs right, then [the step `HaskellPackageDatabaseDump`](https://github.com/tweag/rules_haskell/runs/2250613866#step:7:680) (which just does `{ghc_pkg} dump --global > {output}`) alone took about 16min, I'd expect that to be in the sub-second range. Looking at BuildBuddy the build seems to [still be reported as "Build is in progress..."](https://app.buildbuddy.io/invocation/0bf12c09-5bfd-4ce8-aec0-7888e54c4e20#timing). Perhaps there was some connection issue that was making this slow as well?

This was not the first run with remote caching enabled, right? So, it's not just that uploading to remote cache slowed things down?

> I just tried to reproduce it and failed: https://github.com/tweag/rules_haskell/compare/fd/remote-caching-cross

It's possible that this was some transient network issue, or perhaps something on BuildBuddy's side? Cc @siggisim

**Comment by facundominguez** [comment]
> This was not the first run with remote caching enabled, right? So, it's not just that uploading to remote cache slowed things down?

I think jobs before and after were already slow.

> It's possible that this was some transient network issue, or perhaps something on BuildBuddy's side?

It sounds as a plausible reason.

**Comment by aherrmann** [comment]
@facundominguez Let's assume for now that this was transient and try to re-enable remote caching for cross builds. If it works we can close this issue. If it turns out to be slow again in the future we can still re-open and investigate then.

**Comment by aherrmann** [comment]
Closed by #1548
