### ISSUE TITLE
Test use-cases docs on CI

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#1540]
Build use-cases documentation on CI to avoid issues like #1538.
And render use-cases documentation on netlify to make it easier to avoid issues like #1539.

**Comment by mboes** [comment]
Should be fixed now. All I did was follow the instructions on this page: https://docs.readthedocs.io/en/latest/pull-requests.html. @ylecornec please confirm.

**Comment by mboes** [comment]
I can add "maintainers" to readthedocs. But anyone I add needs to create an readthedocs account first.

**Comment by ylecornec** [comment]
The preview build of pull requests on readthedocs seems to work.

For pull request #1543 for instance, the doc can be previewed here:
https://rules-haskell--1543.org.readthedocs.build/en/1543/

**Comment by aherrmann** [comment]
Closed by https://github.com/tweag/rules_haskell/pull/1543
Docs are rendered on readthedocs instead of netlify.
