### ISSUE TITLE
Could the packages created by stack_snapshot all have public visibility, even the packages not directly specified?

### ISSUE THREAD

**Issue by andremarianiello** [tweag/rules_haskell#1571]
**Describe the bug**

When creating a vendored package, I use the `packages["split"].deps` pattern from the use-cases doc. However, this fails with 
```
ERROR: <bazelpath>/external/twee-lib/BUILD.bazel:4:22: in haskell_cabal_library rule @twee-lib//:twee-lib: target '@stackage//:transformers' is not visible from target '@twee-lib//:twee-lib'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

**To Reproduce**
Vendor a package using the pattern in haskell-use-cases.rst (the package must have deps that are not explicitly listed in the stack_snapshot rule)

**Expected behavior**
I would expect transitive packages in stack_snapshot to have public visibility so that vendored packages can depend on them, thus allowing the `package["split"].deps` idiom to work. 

**Environment**
 - ubuntu 18.04
 - 4.1.0
 - current master (e65211d3)

**Comment by aherrmann** [comment]
I'd prefer not to make all `stack_snapshot` packages publicly visible by default. One of Bazel's design goals is to be explicit. Declaring external dependencies explicitly is part of that: If the project depends on a certain Stackage package, then that should be declared explicitly.
If users don't have to list all direct Stackage dependencies explicitly in the `packages` attribute of `stack_snapshot` then it would be easy to end up in a situation where changes to the `packages` attribute have unintended consequences. For example, let's say `hspec` is in that list. That makes `QuickCheck` an indirect dependency. If indirect dependencies were also publicly visible, then it would be easy to define a new target in the project that depends directly on `QuickCheck` but forget to update the `packages` attribute accordingly. If, in future, `hspec` is removed as dependency, then `QuickCheck` would vanish as well and the target depending only on `QuickCheck` would suddenly fail to build.

That said, I agree that it is inconvenient to have to specify dependencies of vendored packages. Arguably, these types of dependencies are also not really direct dependencies of the project, especially if the vendored package is imported using `http_archive` or similar. These dependencies are also included automatically by stack_snapshot based on the Cabal file of the vendored package. So, the argument above doesn't really apply in this case.

`stack_snapshot` knows the dependency graph. So, I think it would be possible to generate `visibility` declarations for these dependencies that include something like `@vendored//package:__pkg__`, i.e. generate fine grained visibility that only exposes these packages to the vendored packages that depend on them. `stack_snapshot` could construct a reverse dependency graph and then generate such visibility entries for any package that is a dependency of a vendored package. @andremarianiello would such an approach work for your use-case?

**Comment by andremarianiello** [comment]
Thanks!
