### ISSUE TITLE
MacOS Nixpkgs CI fails on MacOS 11.6

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#1607]
**Describe the bug**
CI fails on [macOS 11.6 (`macos-latest` at the time of writing)](https://github.com/tweag/rules_haskell/runs/3882589783#step:7:271).
```
Setup.hs: Missing dependency on a foreign library:
* Missing (or bad) C library: z
```
This failure seems directly related to the OS version: Rerunning a [previously passing](https://github.com/tweag/rules_haskell/actions/runs/1311276221/attempts/1) CI run on `master` [fails with the later macOS version](https://github.com/tweag/rules_haskell/runs/3882685272#step:7:274).

**To Reproduce**
Run the macOS nixpkgs CI pipeline on macOS 11.6.

**Expected behavior**
CI should pass

**Environment**
 - OS name + version: macOS 11.6
 - Bazel version: 4.1.0
 - Version of the rules: master (a70f161b891c610b66cfa740fe27adaeb07333de)

**Additional context**
https://github.com/tweag/rules_haskell/pull/1606#issuecomment-942285370

**Comment by avdv** [comment]
Closing, as we upgraded to macos-11 in the meantime (see #1824) and this didn't turn up.
