### ISSUE TITLE
Documentation: haskell_toolchain docs are unclear

### ISSUE THREAD

**Issue by katre** [tweag/rules_haskell#161]
Love the new rules! A few points on your toolchain docs:

- The haskell_toolchain docs refer to `@ghc`, but the code snippet defines `@my_ghc`: https://github.com/tweag/rules_haskell/blob/21ecb711d8b8ee4fe3d93945afe2983b53411bbe/haskell/toolchain.bzl#L64
- The register_toolchain call references `//:sys_ghc`, but the actual target is `//:my_ghc`: https://github.com/tweag/rules_haskell/blob/21ecb711d8b8ee4fe3d93945afe2983b53411bbe/haskell/toolchain.bzl#L73
- Wrapping the _haskell_toolchain and the native.toolchain call in a macro is definitely helpful for users, but are there any cases where someone will try to use these rules on a non-linux or non-x86_64 system? https://github.com/tweag/rules_haskell/blob/21ecb711d8b8ee4fe3d93945afe2983b53411bbe/haskell/toolchain.bzl#L88

Thanks!

**Comment by jin** [comment]
Also, there's a reference of `new_local_package` repository rule in the README as an alternative to `nixpkgs_package`. Is this supposed to be `new_local_repository`?

**Comment by mrkkrp** [comment]
> Wrapping the _haskell_toolchain and the native.toolchain call in a macro is definitely helpful for users, but are there any cases where someone will try to use these rules on a non-linux or non-x86_64 system?

> FWIW, with some local modifications on macOS, I got a simple binary to compile, but not link - it complained that external/local_config_cc/wrapped_ar was not found. I don't have the logs now, will update later.

We only support Linux so far, afaik.

**Comment by Fuuzetsu** [comment]
We want to support multiple platforms ultimately. @jin if you have some experience reports from trying to get it to work on OSX, that'd be very useful.

**Comment by stoltene2** [comment]
I tried getting it to work yesterday on OSX and I was unsuccessful as well. Perhaps we can add the supported platforms in the README.
