### ISSUE TITLE
ability to use prebuilt packages

### ISSUE THREAD

**Issue by johnynek** [tweag/rules_haskell#162]
@jmillikin has some rules that fetch ghc as a built package instead of using nix.

https://github.com/jmillikin/rules_haskell/blob/master/haskell/private/ghc_repository.bzl

it would be nice to be able to use either approach for cases where we don't want to require nix to be installed on the building machine.

**Comment by mrkkrp** [comment]
I'll take a look, but a quick question: how this is different from this functionality we already provide: http://haskell.build/haskell/ghc_bindist.html?

**Comment by johnynek** [comment]
It looks like it is no different. My mistake. I did not know about that (I thought Nix was the only way to set up a toolchain).
