### ISSUE TITLE
Asterius integration

### ISSUE THREAD

**Issue by ylecornec** [tweag/rules_haskell#1634]
Now that the initial support for asterius is merged, here is an issue to track things that are not working yet.

- [ ]  No stardoc for asterius rules.
Because of the following issue: https://github.com/bazelbuild/rules_nodejs/issues/2874.
And for now stardoc always try to explore third party dependencies https://github.com/bazelbuild/stardoc/issues/93.

- [ ] `haskell_module` integration.
See PR #1629 which contains the asterius tests using the `haskell_module` rule.

- [x] We use an [hardcoded list of toolchain libraries](https://github.com/tweag/rules_haskell/blob/eec33928e7ee2337a8d01ab964cb556353345696/haskell/cabal.bzl#L985) for the cabal rules, so they may fail if we depend on toolchain libraries provided by ghc but not asterius.

- [ ] `//tests/haskell_cabal_package`
This test imports its main function from Lib, and it is not visible as such in the asterius generated javascript files. This example also fails when calling ahc-cabal directly.

- [ ] `//tests/binary_with_main`
This test is a bit similar because it makes use of the main_function attribute.

- [ ] The asterius bundle should be generated by asterius CI, and (if possible) for other platforms than Linux.

- [ ] When C interrop is supported by asterius, it should be tested here.

**Comment by avdv** [comment]
Closing, since asterius is deprecated and we don't plan to work on it further.

**Comment by avdv** [comment]
See https://github.com/tweag/rules_haskell/issues/2249 which tracks work to replace Asterius with GHC WASM.
