### ISSUE TITLE
Add support for non-nix users to install 3rd party cabal libraries from source

### ISSUE THREAD

**Issue by stoltene2** [tweag/rules_haskell#164]
Reading through the code for [toktok-stack](https://github.com/TokTok/toktok-stack). I noticed they are using a custom macro like the following in their workspace file and defined [like this](https://github.com/TokTok/toktok-stack/blob/master/third_party/haskell/haskell.bzl)

```
new_cabal_package(
    package = "aeson-1.2.4.0",
    sha256 = "3401dba4fddb92c8a971f6645b38e2f8a1b286ef7061cd392a1a567640bbfc9b",
)
```

The downside is having to define a [custom build file](https://github.com/TokTok/toktok-stack/blob/master/third_party/haskell/BUILD.aeson) for all library dependencies. It does seem like an alternative for non-nix users.

**Comment by mboes** [comment]
You might be interested in the [Hazel project](https://github.com/FormationAI/hazel).

We don't intend to have first-class support for Cabal packages in rules_haskell itself, but instead rely on add-on projects like Hazel to get that functionality. As such, perhaps this is a downstream ticket? We could point to Hazel in the README though.

**Comment by stoltene2** [comment]
That works for me.
