### ISSUE TITLE
Release 0.14

### ISSUE THREAD

**Issue by Xophmeister** [tweag/rules_haskell#1651]
- [x] Fix minimal bazel version in [the `start` script](./start),
  [haskell/private/versions.bzl](./haskell/private/versions.bzl), and
  [the README](./README.md); add to the [`CHANGELOG`](./CHANGELOG.md)
  if it changed.
- [x] Remove any feature that is still too experimental to go into a
  release, by cherry-picking reverts (or by manually deleting the
  feature).
  - Check the list below for PRs to remove.
- [x] Write `CHANGELOG` by going through all pull requests since last
  release (https://github.com/tweag/rules_haskell/is%3Apr+merged%3A>%3DYYYY-MM-DD)
  replacing YYYY-MM-DD by the date of the last release.
  - Add Highlights section for major improvements/changes
  - `Added`, `Removed`, `Changed`, `Fixed` as necessary
  - If relevant, add corresponding PRs to the changes
- [x] Open a PR from the release branch, go through review and merge
  - If there is changes on the release branch that should not go to
    master, you create a second branch `release-<major>.<minor>-master`
    on master and cherry-pick all relevant commits from the release
    branch. Open a pull request with that branch, go through review
    and push changes back to the release branch.
- [x] Verify that the final version of the release branch is green
- [x] Create release tag (`v<major>.<minor>`) on the release branch and
  push it: `git push origin v<major>.<minor>`
- [x] Go to the [release page](https://github.com/tweag/rules_haskell/releases)
    - click on “Draft a new release”
    - name `v<major>.<minor>`
    - select the tag you created in the previous item, it should be in
      github's dropdown list
    - copy the changelog section into the description
    - you don't need to provide the source `.zip` and `.tar.gz` archives,
      github does it automatically.
    - release
- [x] Update the tag name and checksum in `docs/haskell-use-cases.rst`
- [x] Push `rules_haskell` version in start script to new release tag,
      test it in a temporary directory, create PR against master
  - [x] Once PR has been merged, publish start script and website
        by checkouting the `release` branch and merging master into it.
        Then push the `release` branch, to trigger deployment.
  - [x] Check whether https://haskell.build/start has the newest start
        script (netlify has problems sometimes).
- [x] Announce the new version (on Twitter) by asking someone with Twitter
      rights.

**Comment by Xophmeister** [comment]
Refactored `start` script in 2fbbe95 to make it easier to follow/maintain. It still needs to be updated to correspond with the release.

**Comment by Profpatsch** [comment]
fyi: I wrote the original release checklist, if you have any questions I might be able to elaborate.

**Comment by Profpatsch** [comment]
One thing I learned in the meantime is that you can skip the “create release version tag locally and push” step, instead Github creates the tag when you make a new release.

**Comment by Xophmeister** [comment]
* [ ] Document profiling in user guide (per #1664)

**Comment by Xophmeister** [comment]
There's a race condition wrt the release tag and its tarball's hash, which is [referenced in the `start` script](https://github.com/tweag/rules_haskell/blob/03ea1531ecac042e9679cb1357beed944b8c24e3/start#L199-L205), verses the CI: The CI can't pass until this reference is updated; the tag, which creates the reference, cannot be made without the CI passing. Similarly, the tarball's hash cannot be known ahead of time and updating the hash in the script will of course unpredictably change the tarball's hash.

@aherrmann @Profpatsch I suppose there needs to be an intermediary "release candidate" tag, with a switcheroo once as much as can be satisfied is satisfied...

**Comment by aherrmann** [comment]
> Similarly, the tarball's hash cannot be known ahead of time

The hash can be known. `git archive`, which GH uses, is deterministic. You can use the following command to produce the same tarball hash
```
git archive --format=tar.gz --prefix=rules_haskell-$REV/ $REV | sha256sum
```

**Comment by Xophmeister** [comment]
TIL thanks

**Comment by Profpatsch** [comment]
Yeah, iirc there was an unfortunate loop, but I can’t remember how I broke it exactly. I think I usually updated the `start` script after the fact.
