### ISSUE TITLE
The user's guide gives no hint on how to build with profiling

### ISSUE THREAD

**Issue by facundominguez** [tweag/rules_haskell#1664]
The only hint I found was in the [changelog](https://github.com/tweag/rules_haskell/blob/a7241fa64c7cd36462a1f6ac4c660d1247d5e07b/CHANGELOG.md?plain=1#L352)

Probably this feature should be easier to find, like with a section in the user guide.

**Comment by aherrmann** [comment]
Yes, a mention in the user guide would be great.

**Comment by facundominguez** [comment]
Thanks @Xophmeister!
