### ISSUE TITLE
Haddock cannot see library's prebuilt_dependencies

### ISSUE THREAD

**Issue by gdeest** [tweag/rules_haskell#172]
I am observing the following error when trying to build documentation for a library:

```
ERROR: /home/huginn/code/mylib/BUILD:64:1: Haddock mylib failed (Exit 1)
<command line>: cannot satisfy -package binary-orphans
    (use -v for more information)
```

where `binary-orphans` is one of the library's prebuilt dependences (provisioned via Nix):

```
haskell_library(
    name = "mylib",
    src_strip_prefix = "src",
    srcs = glob(['src/**/*.hs']),
    prebuilt_dependencies = ["binary-orphans", ...]
)
```

The library compiles just fine. My call of `haskell_doc` is simply:

```
haskell_doc(
  name = "mylib-doc",
  deps = [":mylib"],
)
```

**Comment by gdeest** [comment]
Note: getting this bug fixed is a high priority for us. We currently disabled doc generation on CI until a fix is released.

**Comment by mrkkrp** [comment]
Opened https://github.com/haskell/haddock/issues/777, let's see what Haddock maintainers say.

**Comment by mrkkrp** [comment]
Opened https://github.com/NixOS/nixpkgs/issues/36976, let's see what Nixpkgs maintainers say.

**Comment by mrkkrp** [comment]
It looks like this issue will be soon resolved in NixOS side: https://github.com/NixOS/nixpkgs/pull/37132.

**Comment by mrkkrp** [comment]
@gdeest Can you check if this is fixed now? The NixOS PR has been merged.

**Comment by gdeest** [comment]
@mrkkrp We just tried on `nixpkgs`'s master: no luck, exact same behavior.

**Comment by mrkkrp** [comment]
So I spent some time today and it works for me. See this repo: https://github.com/mrkkrp/haddock-extra-pkgs-demo. Clone it, then execute:

```
$ bazel build :mylib-doc
...
Warning: Foo: could not find link destinations for:
    Int
Target //:mylib-doc up-to-date:
  bazel-bin/doc-mylib-1.0.0
  bazel-bin/doc-mylib-1.0.0/mylib-1.0.0.haddock
  bazel-bin/doc-mylib-1.0.0/mylib.txt
  bazel-bin/doc-mylib-1.0.0/doc-index.html
  bazel-bin/doc-mylib-1.0.0/haddock-util.js
  bazel-bin/doc-mylib-1.0.0/hslogo-16.png
  bazel-bin/doc-mylib-1.0.0/index.html
  bazel-bin/doc-mylib-1.0.0/minus.gif
  bazel-bin/doc-mylib-1.0.0/ocean.css
  bazel-bin/doc-mylib-1.0.0/plus.gif
  bazel-bin/doc-mylib-1.0.0/synopsis.png
  bazel-bin/doc-mylib-1.0.0/Foo.html
INFO: Elapsed time: 55.382s, Critical Path: 0.98s
INFO: Build completed successfully, 12 total actions
```

I browsed the docs, they look OK.

Maybe you used older nixpkgs?

**Comment by gdeest** [comment]
This seems to be fixed now.
