### ISSUE TITLE
Help build gi-gtk

### ISSUE THREAD

**Issue by nishanthkarthik** [tweag/rules_haskell#1752]
**Describe the bug**
I am not able to build `@stackage//:gi-gtk`. I am not sure what I am doing wrong here. Any help is appreciated :)

**To Reproduce**

```bzl
rules_haskell_toolchains(
    version = "8.10.7",
)

stack_snapshot(
    name = "stackage",
    packages = [
        "base",
        "random",
        "mtl",
        "gi-gtk",
        "haskell-gi-base",
    ],
    verbose = True,
    snapshot = "lts-18.18",
    stack_snapshot_json = "//tooling:stackage_snapshot.json",
)
```

Running `bazel build @stackage//:gi-gtk` errors out

```
ERROR: /home/x/.cache/bazel/x/598407688b5c09d02ba743fe2c7b1b19/external/stackage/BUILD.bazel:492:22: output 'external/stackage/haskell-gi-overloading-1.0/_install/lib/libHShaskell-gi-overloading-1.0.a' was not created
ERROR: /home/x/.cache/bazel/x/598407688b5c09d02ba743fe2c7b1b19/external/stackage/BUILD.bazel:492:22: output 'external/stackage/haskell-gi-overloading-1.0/_install/haskell-gi-overloading-1.0_haddock/haskell-gi-overloading.haddock' was not created
ERROR: /home/x/.cache/bazel/x/598407688b5c09d02ba743fe2c7b1b19/external/stackage/BUILD.bazel:492:22: output 'external/stackage/haskell-gi-overloading-1.0/_install/lib/libHShaskell-gi-overloading-1.0-ghc8.10.7.so' was not created
ERROR: /home/x/.cache/bazel/x/598407688b5c09d02ba743fe2c7b1b19/external/stackage/BUILD.bazel:492:22: HaskellCabalLibrary @stackage//:haskell-gi-overloading failed: not all outputs were created or valid
```

**Expected behavior**
Building `gi-gtk` should finish. I am not sure if I am building this package correctly with rules_haskell. 

**Environment**
 - OS name + version: ArchLinux
 - Bazel version: 5.1.1
 - Version of the rules: a7241fa64c7cd36462a1f6ac4c660d1247d5e07b

**Comment by avdv** [comment]
It seems [`haskell-gi-overloading`](https://github.com/haskell-gi/haskell-gi/tree/master/overloading) is a bit weird library since it contains no source files as it is only used as a marker to enable / disable overloading. Hence cabal does not build any libraries which is something rules_haskell relies on.

You could work around that by replacing the library with your own version using the `vendored_packages` attribute for `stack_snapshot`. If you still need help with this (after all this time), just write here and I can fill in more details.

**Comment by aherrmann** [comment]
@avdv Thanks for looking into this. IIUC this means that that package would belong into the empty packages list: https://github.com/tweag/rules_haskell/blob/267933e4f0bebbd76742f26477db5b8a397f938e/haskell/cabal.bzl#L129
Does that make sense?

**Comment by avdv** [comment]
Oh, yes. Thank you, @aherrmann that looks like a sensible thing to do. I'll prepare a PR.
