### ISSUE TITLE
Quick start example fails on darwin/aarch64 with: no matching toolchains for types @rules_sh//sh/posix:toolchain_type

### ISSUE THREAD

**Issue by d-s-d** [tweag/rules_haskell#1753]
**Describe the bug**
Quick start example fails on darwin/aarch64 with: no matching toolchains for types @rules_sh//sh/posix:toolchain_type

**To Reproduce**
1. Install homebrew and then `bazel` via homebrew,
2. In a temp directory, execute `curl https://haskell.build/start | sh`
3. run `bazel run //:example`

```
Starting local Bazel server and connecting to it...
DEBUG: /<...>/external/rules_haskell/haskell/private/versions.bzl:60:10: WARNING: bazel version is too recent. Supported versions range from 4.0.0 to 4.2.1, but found: 5.1.1-homebrew
ERROR: /<...>/BUILD.bazel:29:15: While resolving toolchains for target //:example: no matching toolchains found for types @rules_sh//sh/posix:toolchain_type
ERROR: Analysis of target '//:example' failed; build aborted:
INFO: Elapsed time: 2,107s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (40 packages loaded, 135 targets configured)
FAILED: Build did NOT complete successfully (40 packages loaded, 135 targets configured)
```

**Expected behavior**
If there is a fundamental version incompatibility of rules_haskell version `0.14` with version `>5.0.0` of bazel, this should be an error. Otherwise, the target `//:example` should be executed successfully.

**Environment**
 - OS name + version: macOS monterey (12.4), `Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64`
 - Bazel version: `bazel 5.1.1-homebrew`
 - Version of the rules: `0.14`

**Additional context**
* sha256 of the start script at the time of filing the bug:
```
$ curl https://haskell.build/start | shasum -a 256 -

41108afefb5fc8dc2144b28717b8e67b9ea97767705381c741422b35bc148ced  -
```

**Comment by avdv** [comment]
Hi @d-s-d,

since you reported the bug, we released a new version of rules_haskell. Could you re-try your command and report back with the output. Please include the `--toolchain_resolution_debug` flag when calling bazel.

**Comment by avdv** [comment]
Closing, the `start` script for rules_haskell 0.17 works fine for me on aarch64 Darwin.
