### ISSUE TITLE
Implement unused_inputs_list for haskell_module

### ISSUE THREAD

**Issue by facundominguez** [tweag/rules_haskell#1760]
`rules_haskell` provides the interface file of a module M as input to the action that builds every module that imports it transitively. This is because the compiler might need to read the interface file for M, and the build system can't predict reliably whether it will be needed or not.

If the interface file of M changes, then Bazel will arrange to rerun all those actions whether the interface files of the modules along the path in the dependency graph are needed or not. A remedy for this could be to use [unused_input_list](https://bazel.build/rules/lib/actions#run) to report to bazel the interface files that don't affect the output. This might be possible to do if we can get the compiler to report which interface files have been actually read during compilation.

It needs to be investigated whether this is possible to implement with GHC as it is today, or perhaps with the GHC API, or perhaps by using `strace`.

Related https://github.com/tweag/rules_haskell/issues/1552

**Comment by GuillaumeGen** [comment]
#1771 also introduces small example: `basic_modules`. It contains 3 files:

A.hs:
```haskell
module A (f, g, T, a) where

data T = T0 | T1

a :: T
a = T1

f :: a -> b -> a
f x y = x

g :: T -> T
g T0 = a
g T1 = T1
```

B.hs:
``` haskell
module B where

import qualified A (f, g, T)

f :: A.T -> A.T
f x = A.f (A.g x) x

g :: a -> a -> a -> a
g x y = A.f (A.f x) (A.f x)
```

and C.hs:
```haskell
module C where

import qualified B

data N = Z | S N

f :: a -> a -> a
f x = B.g x x
```

There are then quite a lot of changes one can make to `A.hs` or `B.hs` which changes the interface file `B.hi` but do not affect the `ABI` hash of `B` avoiding to trigger the recompilation of `C.hs`.

Changing the export list of `A`:
```diff
- module A (f, g, T, a) where 
+ module A (f, g, T) where 
```

Change the type of a function of `A`:
```diff
- f :: a -> b -> a
- f x y = x
+ f :: a -> b -> b
+ f x y = y
```

Inline a function of `A`:
```diff
+ {-# INLINE f #-}
f :: a -> b -> a
```

Modify the import list of `B`:
```diff
- import qualified A (f, g, T)
+ import qualified A (f, g, T, a)
```

All those modifications affects the part of the interface file of `B` regarding imports, hence it changes `B.hi` but not `B.abi`, so without #1771 it triggers a recompilation of `C`, it is not the case anymore.

**Comment by aherrmann** [comment]
That approach in #1771 is really clever. IIUC it's essentially projecting out the minimal data that we want to take into account for cache invalidation and telling Bazel to ignore the rest.

That said, I don't have a good understanding of what the ABI hash actually represents. @GuillaumeGen can you point to some documentation, or add a note to your PR to explain it?

> Inline a function of `A`:
> 
> ```diff
> + {-# INLINE f #-}
> f :: a -> b -> a
> ```

This is an interesting example. Does the addition of an `INLINE` pragma change `A.abi`? If not, that could be an issue, because it may mean that `B` does not get rebuild when it should take new inlinings into account.

**Comment by GuillaumeGen** [comment]
Yes, adding an `{-# INLINE #-}` pragma modifies the ABI file. Furthermore, if both `A` and `B` are compiled with optimizations (the `-O` option), then a modification of the implementation of `f` in `A` modifies both the ABI hash of `A` and `B`.

**Comment by GuillaumeGen** [comment]
Regrading the description of the ABI hash and how it works, all this is explained in https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/compiler/recompilation-avoidance#how-does-it-work
You are right that I should write a comment about it in the code.

**Comment by aherrmann** [comment]
> > Could dep_direct_mods and potentially dep_direct_pks be used to identify unused direct module dependencies?
> 
> How would you determine then which interface files are unused?

I was thinking of something along the lines of "Set of unused modules = Set of module deps - dep_direct_mods".

**Comment by aherrmann** [comment]
Yes, as I understand this could only be used to determine unused direct module dependencies.

**Comment by avdv** [comment]
Is here something left to do or can we close this with #1771 having been merged?

**Comment by GuillaumeGen** [comment]
I think we can close.
