### ISSUE TITLE
GHC versions supported for Bindist

### ISSUE THREAD

**Issue by GuillaumeGen** [tweag/rules_haskell#1789]
Some versions of GHC are listed in `haskell/gen_ghc_bindist.py` whereas the current implementation of `rules_haskell` does not support them.

After @avdv suggestion, I set up an Actions to test the patches we apply to versions of GHC downloaded for Windows or MacOS. The result of this action shows that some versions of GHC are not supported by `rules_haskell`, even on Ubuntu. https://github.com/tweag/rules_haskell/actions/runs/2705098555

I suggest to completely delete the support for those versions.

**Comment by avdv** [comment]
Fixed by #1790
