### ISSUE TITLE
Haskell toolchain libraries (e.g. `base`) cannot be found on `darwin_arm64` with GHC 9.2

### ISSUE THREAD

**Issue by fwcd** [tweag/rules_haskell#1809]
**Describe the bug**
When using GHC 9.2 on arm64 macOS (M1), after applying the fix from #1808, building the tutorial still errors with:

```
Error in fail: 
base is not a toolchain library.
Check that it ships with your version of GHC.
The following toolchain libraries are available:
{}
```

**To Reproduce**
Apply #1808 and update the GHC version in `tutorial/WORKSPACE:23`:

```diff
- rules_haskell_toolchains(version = "8.10.7")
+ rules_haskell_toolchains(version = "9.2.1")
```

Then run `bazel build //..` in `tutorial`.

**Expected behavior**

**Environment**
 - OS name + version: macOS 12.5.1 on arm64
 - Bazel version: 5.2.0
 - Version of the rules: 5b3eb6922d683217ee38bc7d723ed58e2dcf196d

**Additional context**
From what I can tell the issue is that the location of toolchain libraries (e.g. `base`) moved from

```
<ghc install root>/lib/ghc-8.10.7/base-4.14.3.0
```

in GHC 8.10 to

```
<ghc install root>/lib/ghc-9.2.1/lib/aarch64-osx-ghc-9.2.1/base-4.16.0.0
```

in GHC 9.2. (notice the additional `aarch64-osx-ghc-9.2.1` directory)

**Comment by avdv** [comment]
Could you try GHC 9.2.3 instead? This does not seem to have the extra `aarch64-osx-ghc-9.2.*` directory.

**Comment by avdv** [comment]
Could you please  try PR #1825 and see if it fixes this problem for you?

**Comment by tsiq-aaronh** [comment]
It got past that step! Thanks! We're hitting an issue where llvm needs to be installed... but that's a separate issue. Feel free to close this one.
