### ISSUE TITLE
example of using prebuilt packages and threaded-rts package

### ISSUE THREAD

**Issue by ghorn** [tweag/rules_haskell#189]
I can't figure out how to create a library such as the `threaded-rts`: https://github.com/tweag/rules_haskell/blob/4736c92c6ffe206892f395f3b6e187279505ceb2/WORKSPACE#L30-L34

while also using prebuilt nix haskell packages such as:
https://github.com/ghorn/rules_haskell/blob/aec65488faf4ed8a929c93127f7c17bf882ab535/examples/library_with_nix_dependencies/WORKSPACE#L26-L42

Is this possible? An example would be appreciated.

**Comment by Fuuzetsu** [comment]
@gdeest you had this working no?

**Comment by mboes** [comment]
The code you cite is from a `build_file_content` attribute of a `nixpkgs_package` entry. The trick is to also change the `attribute_path` or `nix_file_content` entry to customize the GHC that you want. E.g. if you use a `nix_file_content` like in https://github.com/tweag/rules_haskell_examples/blob/master/WORKSPACE#L20-L29, then you can set a GHC that provides whatever `prebuilt_dependencies` you desire.

I have added a new example in https://github.com/tweag/rules_haskell_examples illustrating this.

**Comment by ghorn** [comment]
Thank you!
