### ISSUE TITLE
Publish `rules_haskell` on the Bazel central registry

### ISSUE THREAD

**Issue by ylecornec** [tweag/rules_haskell#1896]
```[tasklist]
### Tasks
- [x] Add rules_haskell to https://github.com/bazelbuild/bazel-central-registry
- [ ] https://github.com/tweag/rules_haskell/issues/2026
```

**Comment by avdv** [comment]
I created a PR to the BCR here: https://github.com/bazelbuild/bazel-central-registry/pull/1029

I'll add automation for future releases with the Publish to BCR app once the the PR is accepted.
