### ISSUE TITLE
can't run tests/c-compiles:c-compiles

### ISSUE THREAD

**Issue by ghorn** [tweag/rules_haskell#192]
I get an error that it can't find `libstdc++.so.6`

```
$ git rev-parse HEAD
525eba2b4eaf39b4c59ab8d311108678a3573b9a
```
It builds fine:
```
$ bazel build //tests/c-compiles:c-compiles
INFO: Analysed target //tests/c-compiles:c-compiles (1 packages loaded).
INFO: Found 1 target...
INFO: From Compiling hs-lib:
[1 of 1] Compiling Lib              ( tests/c-compiles/Lib.hs, bazel-out/k8-fastbuild/bin/tests/c-compiles/objects-hs-lib-1.0.0/Lib.o )
INFO: From SkylarkAction tests/c-compiles/hs-lib-1.0.0:
Reading package info from "bazel-out/k8-fastbuild/bin/tests/c-compiles/registration-file-hs-lib-1.0.0" ... done.
INFO: From Building c-compiles:
[1 of 1] Compiling Main             ( tests/c-compiles/Main.hs, bazel-out/k8-fastbuild/bin/tests/c-compiles/objects-c-compiles-1.0.0/Main.o )
Target //tests/c-compiles:c-compiles up-to-date:
  bazel-bin/tests/c-compiles/c-compiles
INFO: Elapsed time: 1.665s, Critical Path: 1.54s
INFO: Build completed successfully, 11 total actions
```
But if you try to run it you get an error that it can't find `libstdc++.so.6`
```
$ bazel run //tests/c-compiles:c-compiles
INFO: Analysed target //tests/c-compiles:c-compiles (0 packages loaded).
INFO: Found 1 target...
Target //tests/c-compiles:c-compiles up-to-date:
  bazel-bin/tests/c-compiles/c-compiles
INFO: Elapsed time: 0.083s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/tests/c-compiles/c-compiles
/home/greghorn/.cache/bazel/_bazel_greghorn/77e3915c454b3032673133047c952be3/execroot/io_tweag_rules_haskell/bazel-out/k8-fastbuild/bin/tests/c-compiles/c-compiles: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
ERROR: Non-zero return code '127' from command: Process exited with status 127
```
The foreign object links to `libstdc++.so.6` and can find it as it sits in `bazel-out`
```
$ ldd bazel-out/k8-fastbuild/bin/tests/c-compiles/libc-lib.so
	linux-vdso.so.1 (0x00007fffd89fb000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe867993000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe867648000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe867292000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe867d18000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe86707a000)
```

**Comment by ghorn** [comment]
In my work project I came across the same error but during a `bazel build`. I came across the above example while trying to produce a minimal example. Any ideas about this error during a `bazel build`?

**Comment by ghorn** [comment]
Not sure if this is related - you also can't run the binary directly:
```
$ bazel build //tests/c-compiles:c-compiles
INFO: Analysed target //tests/c-compiles:c-compiles (0 packages loaded).
INFO: Found 1 target...
Target //tests/c-compiles:c-compiles up-to-date:
  bazel-bin/tests/c-compiles/c-compiles
INFO: Elapsed time: 0.091s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
```
```
$ ./bazel-bin/tests/c-compiles/c-compiles
./bazel-bin/tests/c-compiles/c-compiles: error while loading shared libraries: libtests_Sc-compiles_Sc-lib_libc-lib.so: cannot open shared object file: No such file or directory
```
```
$ ldd ./bazel-bin/tests/c-compiles/c-compiles
	linux-vdso.so.1 (0x00007ffe2fca4000)
	libm.so.6 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libm.so.6 (0x00007f1b57b4f000)
	libtests_Sc-compiles_Sc-lib_libc-lib.so => not found
	libgmp.so.10 => /nix/store/8qfd8gx0j3yzamkrbrfz5kc00h4cqd1q-gmp-6.1.2/lib/libgmp.so.10 (0x00007f1b578bd000)
	librt.so.1 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/librt.so.1 (0x00007f1b576b5000)
	libdl.so.2 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libdl.so.2 (0x00007f1b574b1000)
	libc.so.6 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6 (0x00007f1b570ff000)
	libpthread.so.0 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libpthread.so.0 (0x00007f1b56ee1000)
	/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007f1b57e9b000)
```

**Comment by mboes** [comment]
Can't reproduce. Would be useful to see a minimal example. Also, what distro are you on? Are you using Nixpkgs? Your first comment suggests you are not, but the last one suggests that you are.

**Comment by ghorn** [comment]
I'm on debian unstable and I have nix-build installed. I thought that whether or not I'm using nix packages is determined by `WORKSPACE`, so I'm using whatever the `rules_haskell` repo is using. I'm not running nix-os if that's what you're asking.

Here's a pretty minimal example that fails for me based on the `rules_haskell_example` repo: https://github.com/ghorn/c-compile-stdcxx-thing. Clone it and try `bazel build //...; bazel run //c-compiles:c-compiles`

I tried to get travis-ci to run it but I'm getting a seemingly unrelated shared library failure: https://travis-ci.org/ghorn/c-compile-stdcxx-thing/builds/356098774

**Comment by mrkkrp** [comment]
OK, there are several things here, so let's go through them in order:

* The target `//tests/c-compiles:c-lib` is linked against `libstdc++.so.6` which is a system-level lib, so it should be just visible if it's installed on your system. This is not very hermetic but that's how stock cc rules work anyway. Bazel ~~cannot~~ should not influence visibility of this, because it cannot touch things outside of its working tree. Why this library is not visible when you do `bazel run` is not clear, I cannot reproduce it either. Please post output of the following command:

  ```
  $ objdump -x libc-lib.so | grep RUNPATH
  ```

  This will tell where `libc-lib.so` searches for the library at run time (in my experience there may be slight deviations from what `ldd` shows and what happens in reality).

* > Not sure if this is related - you also can't run the binary directly

  You're supposed to make that library component visible somehow (meaning you should put it in someplace that is searched for .so libraries), packaging story is not very polished with Bazel.

* [This](https://travis-ci.org/ghorn/c-compile-stdcxx-thing/builds/356098774) looks like a bug to me, but I can't reproduce it. In particular `ERROR: /home/travis/build/ghorn/c-compile-stdcxx-thing/c-compiles/BUILD:14:1: output 'c-compiles/libc-compiles_Sc-lib_libc-lib.so' was not created` indicates that `ln` failed to create the symbolic link [here](https://github.com/tweag/rules_haskell/blob/master/haskell/actions.bzl#L102-L107).

What system do they use on Travis? Would be handier if we could reproduce in a docker container so I could play with it. Maybe I could try with debian or ubuntu image.

**Comment by ghorn** [comment]
There seem to be 9 files that match `*libc-lib.so`:
```
$ find -L . -iname '*libc-lib.so'
./bazel-c-compile-stdcxx-thing/bazel-out/k8-fastbuild/bin/c-compiles/libc-lib.so
./bazel-c-compile-stdcxx-thing/bazel-out/k8-fastbuild/bin/c-compiles/c-compiles.runfiles/io_tweag_rules_haskell_examples/c-compiles/libc-compiles_Sc-lib_libc-lib.so
./bazel-c-compile-stdcxx-thing/bazel-out/k8-fastbuild/bin/c-compiles/libc-compiles_Sc-lib_libc-lib.so
./bazel-bin/c-compiles/libc-lib.so
./bazel-bin/c-compiles/c-compiles.runfiles/io_tweag_rules_haskell_examples/c-compiles/libc-compiles_Sc-lib_libc-lib.so
./bazel-bin/c-compiles/libc-compiles_Sc-lib_libc-lib.so
./bazel-out/k8-fastbuild/bin/c-compiles/libc-lib.so
./bazel-out/k8-fastbuild/bin/c-compiles/c-compiles.runfiles/io_tweag_rules_haskell_examples/c-compiles/libc-compiles_Sc-lib_libc-lib.so
./bazel-out/k8-fastbuild/bin/c-compiles/libc-compiles_Sc-lib_libc-lib.so
```
None of them have a `RUNPATH` according to `objdump -x`

I've also reproduced the `libstdc++.so.6` error and lack of `RUNPATH` on ubuntu 17.10 also.

As for the symbolic link fail, travis-ci was running on Ubuntu 14.04 LTS. I don't know an easy way to use a later version. Want me to open a separate issue?

**Comment by ghorn** [comment]
I noticed a discrepancy between the executable `c-compiles` and the library `libc-lib.so`'s linked libraries:

`c-compiles`:
```
greghorn@goatbox:~/hslibs/c-compile-stdcxx-thing (master)$ ldd bazel-bin/c-compiles/c-compiles
	linux-vdso.so.1 (0x00007ffd9c7f3000)
	libm.so.6 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libm.so.6 (0x00007fe879e09000)
	libc-compiles_Sc-lib_libc-lib.so => not found
	libgmp.so.10 => /nix/store/8qfd8gx0j3yzamkrbrfz5kc00h4cqd1q-gmp-6.1.2/lib/libgmp.so.10 (0x00007fe879b77000)
	librt.so.1 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/librt.so.1 (0x00007fe87996f000)
	libdl.so.2 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libdl.so.2 (0x00007fe87976b000)
	libc.so.6 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libc.so.6 (0x00007fe8793b9000)
	libpthread.so.0 => /nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/libpthread.so.0 (0x00007fe87919b000)
	/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007fe87a155000)
```
`libc-lib.so` (or `libc-compiles_Sc-lib_libc-lib.so`)
```
greghorn@goatbox:~/hslibs/c-compile-stdcxx-thing (master)$ ldd bazel-bin/c-compiles/libc-lib.so
	linux-vdso.so.1 (0x00007ffe5cbc8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f081d44e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f081d0bb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f081cd01000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f081d7d3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f081cae9000)
```

The executable is linking to nix libraries except for `libc-compiles_Sc-lib_libc-lib.so` which is not found while the shared library is linking to system libraries.

Is my `WORKSPACE` or `BUILD` misconfigured? Is the missing `RPATH` supposed to change this behavior?

**Comment by ghorn** [comment]
I just realized that it works if you use `ghc_bindist` instead of the nixpkgs ghc.

**Comment by mrkkrp** [comment]
It's good at least `ghc_bindist` works for you :) What OS are you on? Can you reproduce this either in a docker container or using Circle CI so I could run with SSH and investigate? Today I tried to compile the project you link to (in connection to #193), https://github.com/ghorn/c-compile-stdcxx-thing, in Ubuntu 14.04 LTS docker image and succeeded.

**Comment by mboes** [comment]
Is this still an issue or can we close?

**Comment by ghorn** [comment]
irrelevant to me now
