### ISSUE TITLE
X is not a toolchain library

### ISSUE THREAD

**Issue by aveltras** [tweag/rules_haskell#1920]
Hi,

I have upgraded a project to use GHC 9.6.2 (from 9.2.5).
I'm using nix to provide haskell dependencies using `ghcWithPackages` like so:

```nix
ghc = final.haskellPackages.ghcWithPackages (p:
  with p; [
     aeson
     aeson-pretty
    ...etc
```

I have a `BUILD` file with many targets and I have all the nix provided libraries declared as `haskell_toolchain_library`:

```bzl
haskell_toolchain_library(name="aeson")
haskell_toolchain_library(name="aeson-pretty")
haskell_toolchain_library(name="amazonka")
haskell_toolchain_library(name="amazonka-cognito-idp")
haskell_toolchain_library(name="amazonka-core")
haskell_toolchain_library(name="amazonka-dynamodb")
...etc
```

This used to work previously but now I can't load REPL or build library because of the following error:

```sh
ERROR: /home/romain/Code/matryo-product/backend/BUILD.bazel:58:26: in haskell_toolchain_library rule //backend:aeson-pretty:
Traceback (most recent call last):
        File "/home/romain/.cache/bazel/_bazel_romain/7404dc8029ea6151e966016273940d3d/external/rules_haskell/haskell/private/haskell_impl.bzl", line 801, column 13, in haskell_toolchain_library_impl
                fail(
Error in fail:
aeson-pretty is not a toolchain library.
Check that it ships with your version of GHC.
The following toolchain libraries are available:
{}
```

The library specified in the error (here `aeson-pretty`) changes with each try so i think it's a more general issue.
The libraries are available with the nix provided GHC according to `ghc-pkg list`

```sh
ghc-pkg list | grep aeson-pretty
    aeson-pretty-0.8.9
```

I'm using latest commit for `rules_haskell` and `rules_nixpkgs`.

Has something changed in the way we should use rules_haskell with Nix recently ?

**Comment by avdv** [comment]
Hi aveltras,

thanks for the bug report. I know there have been some changes to GHC 9.6 that might be causing this and we have to adapt rules_haskell for that. I'll have a deeper look later.

**Comment by avdv** [comment]
Hi @aveltras ,

I figured out why the pkg db was empty with GHC 9.6.x and I have created a draft PR here: #1921 

It would be nice if you could test if this works for you. I want to add a test case for this, but that won't happen until after I am back from vacation.

**Comment by aveltras** [comment]
Hi @avdv,
I tested using your PR but encountered other issues while trying to build.
Not sure if those were before or after the initial issue since this was related to bazel code that I'm not familiar with.
I won't have the time to pursue updating in the near future but I'll be returning to this eventually.
Maybe #1918 will change something when doing so.

**Comment by avdv** [comment]
Thanks for trying, @aveltras.

I'll try to get proper support for GHC 9.4 and 9.6 ready as part of #1878 - currently we don't thoroughly test GHC versions other than 9.2.5. (I could reproduce the issue also with 9.2.8 BTW - e.g. [here](https://github.com/avdv/replay/actions/runs/5703580973/job/15456374331))

**Comment by aveltras** [comment]
@avdv seems to be working, i could enter the repl with the full project now
