### ISSUE TITLE
simple example running on travis-ci fails to symlink shared library

### ISSUE THREAD

**Issue by ghorn** [tweag/rules_haskell#193]
(Splitting this issue from #192)

I stumbled across a build failure that only happens when using travis-ci: https://travis-ci.org/ghorn/c-compile-stdcxx-thing/builds/356098774#L863.

`ERROR: /home/travis/build/ghorn/c-compile-stdcxx-thing/c-compiles/BUILD:14:1: output 'c-compiles/libc-compiles_Sc-lib_libc-lib.so' was not created`

Travis-ci is running on Ubuntu 14.04 LTS. @mrkkrp suspects the issue is specific to this OS. I distrust travis-ci itself but don't know how to run on another OS using travis.

Copied from https://github.com/tweag/rules_haskell/issues/192#issuecomment-374909041:
> [This](https://travis-ci.org/ghorn/c-compile-stdcxx-thing/builds/356098774) looks like a bug to me, but I can't reproduce it. In particular ERROR: /home/travis/build/ghorn/c-compile-stdcxx-thing/c-compiles/BUILD:14:1: output 'c-compiles/libc-compiles_Sc-lib_libc-lib.so' was not created indicates that ln failed to create the symbolic link [here](https://github.com/tweag/rules_haskell/blob/master/haskell/actions.bzl#L102-L107).

Standalone repo here https://github.com/ghorn/c-compile-stdcxx-thing

**Comment by mrkkrp** [comment]
It may be a good idea to have a CI job running using another image (such as Ubuntu).

**Comment by mrkkrp** [comment]
Can't reproduce it with Ubuntu 14.04 LTS docker image. Does Travis allow building with SSH so I could login after build and investigate?

**Comment by mboes** [comment]
Closing for now. Reopen if you see this again.
