### ISSUE TITLE
is it possible to run doctests?

### ISSUE THREAD

**Issue by ghorn** [tweag/rules_haskell#194]

**Comment by mrkkrp** [comment]
I guess this, in its core, the same sort of thing as linting we've discussed in #181. I did some progress on linting, but so far there is a problem with aspect-based approach: a rule must have outputs (files), and such rules typically do not have outputs (in fact having outputs is undesirable in this case).

**Comment by mboes** [comment]
Right. So the short answer is, "not yet". Once we have #181 sorted out (on which we do know the path forward), the same approach should work here.
