### ISSUE TITLE
Core libraries visible even when dependency not declared

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#20]
Minimal repro:

```haskell
import Language.Haskell.TH

main = return ()
```

with following `BUILD` file:

```bzl
haskell_binary(
  name = "binary-with-prebuilt",
  srcs = ["Main.hs"],
  prebuilt_dependencies = ["base"],
)
```

Expected a build failure, because `"template-haskell"` not in deps, but the build succeeds.

**Comment by Fuuzetsu** [comment]
We need `-hide-all-packages` in binary builds, haskell_binary is a bit neglected in comparison to haskell_library.

**Comment by mboes** [comment]
I noticed the duplication of logic between `haskell_binary` and `haskell_library` when working on #25. An outcome of any fix to this ticket should be to factor out more of the logic between these two rules.
