### ISSUE TITLE
Is there any way to let haskell_library access some data files at compile time?

### ISSUE THREAD

**Issue by neongreen** [tweag/rules_haskell#207]
I want to [`file-embed`](https://hackage.haskell.org/package/file-embed) a file at compile time. I tried adding it to `src`, but Bazel told me that only *.hs, *.hsc, etc are allowed there, and my file is a .txt. Is there some baked-in way to solve this, or does it require rules_haskell to be modified?

**Comment by mboes** [comment]
Well hold on, don't we have the http://haskell.build/haskell/haskell.html#haskell_library.data attribute?

**Comment by mrkkrp** [comment]
But these are to be included in runfiles. They probably won’t be available at compile time anyway.

**Comment by mboes** [comment]
> But these are to be included in runfiles. They probably won’t be available at compile time anyway.

Yes, but worth a try. Note that we do have support for non-compilable sources in `srcs`, but the file has to be a `.h`. We even have a test for this, see https://github.com/tweag/rules_haskell/blob/master/tests/textual-hdrs/BUILD. Caveat: file extension has to be `.h`. I'm loath to allow arbitrary files in `srcs` - this has the potential to make files added by mistake to `srcs` silently be ignored.

**Comment by mboes** [comment]
@neongreen what's your use case for `file-embed`?

**Comment by neongreen** [comment]
This is related to my adventure of building Pandoc. In this particular case I could just strip it out (though then I need to work around not having `Paths_` modules), but in the past I've had more convincing usecases for reading files at compile time (e.g. in Cardano we were reading _and parsing_ some configs at compile time).

**Comment by mboes** [comment]
Could #211 work for you?

**Comment by neongreen** [comment]
I guess #211 is exactly as powerful as `file-embed`, yeah. Not saying I'm a huge fan of re-inventing `file-embed`, though (I'd basically have to either reimplement [literal-generating code](https://hackage.haskell.org/package/file-embed-0.0.10.1/docs/src/Data-FileEmbed.html#bsToExp) by myself, or call file-embed and then pretty-print the generated code).

**Comment by Profpatsch** [comment]
In the [documentation for runfiles](https://docs.bazel.build/versions/master/skylark/rules.html#runfiles) there’s this sentence:

> Also note that if an action uses an executable, the executable's runfiles can be used when the action executes.

So maybe there is a way to add arbitrary files to the build input?

**Comment by mrkkrp** [comment]
I actually think we should close this one, because indeed this is solved by `extra_srcs` completely.
