### ISSUE TITLE
[Bazel CI] Unrecognized option incompatible_struct_has_no_methods  in bazel command


### ISSUE THREAD

**Issue by sgowroji** [tweag/rules_haskell#2170]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3807#018f03f8-cd2b-4215-b25c-6e3a40b9fa2c

 Platform: Ubuntu

 Logs: 
```
ERROR: --incompatible_struct_has_no_methods :: Unrecognized option: --incompatible_struct_has_no_methods
``` 
 
 CC Greenteam @wyverald

**Comment by sgowroji** [comment]
Above issue is still not fixed.  https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3826#018f378a-885f-4964-bb40-2e2ddbb3a323

```
ERROR: --incompatible_struct_has_no_methods :: Unrecognized option: --incompatible_struct_has_no_methods
Traceback (most recent call last):
  File "bazelci.py", line 4434, in <module>
    sys.exit(main())
  File "bazelci.py", line 4412, in main
    bazel_version=task_config.get("bazel") or configs.get("bazel"),
  File "bazelci.py", line 1328, in execute_commands
    PrepareRepoInCwd(True, initial_setup=True)
  File "bazelci.py", line 1316, in PrepareRepoInCwd
    os.environ["OUTPUT_BASE"] = get_output_base(bazel_binary)
  File "bazelci.py", line 2081, in get_output_base
    print_output=False,
  File "bazelci.py", line 2690, in execute_command_and_get_output
    universal_newlines=True,
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bazel', 'info', 'output_base']' returned non-zero exit status 2.
🚨 Error: The command exited with status 1
```

**Comment by avdv** [comment]
IIRC, the bazel HEAD + downstream CI job uses the last green commit from the downstream project, right?

Even though the badge on our README says buildkite is green, it is broken and thus the last green commit hasn't been updated in a while...

[![Build status](https://badge.buildkite.com/1de3270f1df070a99978adb6efa180d0c32eac58e0fd1938d1.svg?branch=master)](https://buildkite.com/bazel/rules-haskell-haskell)

**Comment by sgowroji** [comment]
CC @meteorcloudy
