### ISSUE TITLE
FR: Import external toolchains (e.g., from ghcup, stack, ...)

### ISSUE THREAD

**Issue by jashank** [tweag/rules_haskell#2240]
(I imagine the answer to this is "why would you want that", but I may as well ask...)

**Is your feature request related to a problem? Please describe.**
Both GHCup and Stack can manage manage GHC installations (as can system package managers, but I'll ignore those for now). To my eye, it seems wasteful to have _another_ GHC installation on my development machine. I don't particularly want to download (or, worse, compile!) more copies of the same toolchains.

**Describe the solution you'd like.**
Alongside `rules_haskell_toolchains` and `haskell_register_ghc_nixpkgs`, `rules_haskell` should provide a means to import a toolchain already available on a system.  This would be analogous to Stack's `system-ghc` flag; or to the magic `local_jdk` toolchain supported for Java.  (Bonus points for integration with GHCup or Stack to import toolchains automatically.)

**Describe alternatives you've considered.**
(I've tried shoehorning this into `rules_haskell`'s innards, and had no joy; and I don't understand Bazel's or `rules_haskell`'s innards well enough to be confident in  from scratch. I'd prefer not to end up with Yet Another GHC on my development machine.)

**Additional context.**
(I have the same objection to other `rules_...`-defined toolchains which are hermetic-only.)

**Comment by aherrmann** [comment]
Thanks for raising this issue! If I understand it correctly, I think this issue asks for the same thing as https://github.com/tweag/rules_haskell/issues/1320. See also https://github.com/tweag/rules_haskell/issues/1423#issuecomment-698266377 for a discussion around different approaches to importing GHC toolchains.

**Comment by jashank** [comment]
Aha! Yes, those issues are what I'm thinking of — I hadn't dug back far enough (and didn't have enough search-keyword-fu) to find them. I'll close this and go follow those instead. Thanks!

**Comment by aherrmann** [comment]
No worries, thank you for raising this and for responding so quickly!
