### ISSUE TITLE
Haddock fails on parallel executions

### ISSUE THREAD

**Issue by dleprovost** [tweag/rules_haskell#229]
If `haskell_doc` is called with more than one job, the related instances of Haddock will concurrently try to create the same temporary directory, and fail the job.

By now `-j 1` has to be passed to `bazel build`. It should be handled by default in `haskell_doc` (until `haddock` evolution on parallel executions).

Note: We noticed this behavior with bazel version 0.12.0, but not with 0.11.0.

**Comment by thumphries** [comment]
Looks like this code is involved https://github.com/haskell/haddock/blob/ef16b9f8f73e6a4d639919152925ab83d9b1024f/haddock-api/src/Haddock/Interface.hs#L140 (I'm unsure how PIDs are managed in Bazel)

**Comment by regnat** [comment]
We've also been hit by that, but can't manage to reproduce it :/

Probably setting `TMP` to a fresh directory in https://github.com/tweag/rules_haskell/blob/master/haskell/private/haddock_wrapper.sh would fix that, @dleprovost do you have an example which reliably triggers this?

**Comment by ghorn** [comment]
```haskell
    withTempOutputDir :: Ghc a -> Ghc a
    withTempOutputDir action = do
      tmp <- liftIO getTemporaryDirectory
      x   <- liftIO getProcessID
      let dir = tmp </> ".haddock-" ++ show x
      modifySessionDynFlags (setOutputDir dir)
      withTempDir dir action
```
If bazel is invoking these in parallel, why do they have the same process ID?

**Comment by thumphries** [comment]
This occurs on every execution for me, using Fedora 27 and bazel-0.15.0

I have no working theory as to how, but the PIDs are always 6 or 8, apparently.

**Comment by mboes** [comment]
@dleprovost Is there an upstream issue we can reference? We'll have to workaround in the meantime.

**Comment by Profpatsch** [comment]
There doesn’t seem to be an upstream issue. @dleprovost or @thumphries, can one of you create one [here](https://github.com/haskell/haddock/issues)? We need the output of the failing haddock build and a minimal reproducible example (maybe two, one for `rules_haskell` and then one that provokes the issue with only a bash script).

**Comment by Profpatsch** [comment]
Okay, opened an upstream PR.
