### ISSUE TITLE
Bazel sometimes needs a full clean to locate `ar`

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#244]
# Updated Issue

It seems that some state about where bazel expects `ar` is not updated on `build`, but requires a `bazel clean --expunge` to be refreshed. This is considered a bug according to https://github.com/tweag/rules_haskell/issues/244#issuecomment-389079777 below.

If `ar` is not in `$PATH` then `bazel build` fails with the following error message.
```
ERROR: /path/to/project/BUILD:16:1: output 'visible-binaries/ar' is a dangling symbolic link
```
After installing binutils `nix-env -iA nixos.binutils`, such that `ar` is in `$PATH`, `bazel build` still fails with the same error message.
Running `bazel clean --expunge` fixes the issue. Afterwards `bazel build` succeeds. (`bazel clean` is not sufficient, the `--expunge` flag is required.)
Uninstalling `binutils` again causes the same failure of `bazel build`. However, reinstalling `binutils` makes `bazel build` succeed without the need for `bazel clean --expunge`.

In summary:
- `ar` not in `$PATH`
- `bazel build` fails
- install `binutils` (`ar` in `$PATH`)
- `bazel build` fails
- `bazel clean --expunge`
- `bazel build` succeeds
- uninstall `binutils`
- `bazel build` fails
- reinstall `binutils`
- `bazel build` succeeds (no need for `bazel clean --expunge`)
- uninstall `binutils`
- `bazel clean --expunge`
- `bazel build` fails
- install `binutils`
- `bazel build` still fails

# Original Issue

Bazel fails to locate `ar` when trying to build a project or its tests.
E.g.
```
$ bazel test //test/unit
INFO: Analysed target //test/unit:unit (0 packages loaded).
INFO: Found 1 test target...
ERROR: /path/to/project/BUILD:16:1: output 'visible-binaries/ar' is a dangling symbolic link
ERROR: /path/to/project/BUILD:16:1: not all outputs were created or valid
Target //test/unit:unit failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.303s, Critical Path: 0.04s
FAILED: Build did NOT complete successfully

Executed 0 out of 1 test: 1 fails to build.
```

This happens, both, when `ar` is in `$PATH` (installed via `nix-env -iA nixos.binutils`) and when it is not.

I'm testing this on NixOS 18.03. The above command was last working when tested on NixOS 17.09.

**Comment by aherrmann** [comment]
Installing `ar` such that it is in `$PATH` and running `bazel clean --expunge` solves the issue.

**Comment by mboes** [comment]
Hold on. Having to run `bazel clean --expunge` to unstick any situation is a bug. Can you confirm that `clean` was necessary and if so reopen with a different description?

**Comment by aherrmann** [comment]
@mboes Yes, I can confirm that the `clean --expunge` is necessary. I'm reopening with a new issue description.
