### ISSUE TITLE
Linking error when using a Template Haskell library with external C++ deps

### ISSUE THREAD

**Issue by gdeest** [tweag/rules_haskell#250]
We are seeing a linking error against `libstdc++.so.6` with the following setup:

- A `WORKSPACE` file declaring an external repository with:
  - A C++ library.
  - A Haskell library depending on the C++ library and exposing Template Haskell functions.
- In the main workspace: a Haskell library including a TH splice the Template Haskell library.

I have pushed a reproducible test case here:
https://github.com/gdeest/repro_link_error

(Note that you will need to change the path to the `other-repo` directory in `repro-bug/WORKSPACE`. That is because `new_local_repository` requires absolute paths.)

Here is the error message we get:
```
ERROR: /home/damien/workspace/repro-archive/repro-bug/BUILD:14:1: Compiling lib failed (Exit 1)
<command line>: can't load .so/.DLL for: bazel-out/k8-fastbuild/bin/external/other_repo/libHSexternalZSotherZUrepoZShslib-1.0.0-ghc8.2.2.so (libstdc++.so.6: cannot open shared object file: No such file or directory)
INFO: Elapsed time: 3.458s, Critical Path: 1.01s
FAILED: Build did NOT complete successfully
```
Apparently, the transitive runtime deps required by the Template Haskell library can't be seen at compile-time when those deps come from an external location. Removing the TH splice makes the failure disappear.

Additional data points:
- The problem occurs on Ubuntu 18.04 LTS, but not on NixOS. 
- The behavior is the same on 0.4 and latest master. 

cc @dleprovost

**Comment by ghorn** [comment]
https://github.com/tweag/rules_haskell/issues/192 also has a linking error on `libstdc++.so.6`. Not sure if related.

**Comment by mboes** [comment]
This issue is due to the fact that `cc_library` is picking up the system GCC, while GHC hardcodes using `gcc` from Nixpkgs. So you're not using the same compiler versions across the board. We either need to tell GHC to use the GCC that Bazel finds, or tell Bazel to use the same GCC that GHC knows about.

**Comment by mboes** [comment]
```
$ nix why-depends nixpkgs.ghc nixpkgs.gcc
nix why-depends nixpkgs.ghc nixpkgs.gcc
/nix/store/mmhdqindrpvg91a2vnrr76vxcn5a4n0x-ghc-8.2.2
╚═══lib/ghc-8.2.2/settings: … compiler command", "/nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0/bin/cc"),. ("…
    => /nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0
```

Whereas

```
$ bazel build -s //...
[...]
/usr/bin/gcc ...
[...]

**Comment by mboes** [comment]
Workaround: run Bazel inside a nix-shell:

```
$ nix-shell -I nixpkgs=./nixpkgs.nix -p gcc
$ bazel build //...
```

where `nixpkgs.nix` imports a version of Nixpkgs matching what the `WORKSPACE` says. This will ensure that the `gcc` command available is the same one as used by GHC.

**Comment by mboes** [comment]
So here's how to do it. Bazel has a a rule and a macro for autoconfiguring the 
 CC toolchain: https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_configure.bzl#L84. We can tweak the autoconfiguration by setting the `CC` environment variable explicitly, but that's a clunky solution. Instead, we need to call the rule ourselves, supplying an appropriate value for the `overridden_tools` argument, mapping command names to locations in nixpkgs.

**Comment by gdeest** [comment]
I can confirm that the `nix-shell` workaround "fixes" this issue.

**Comment by judah** [comment]
An example (I think) of a custom CC configuration: https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_configure.bzl

**Comment by guibou** [comment]
Isn't just a miss configured CC toolchain ? Bazel uses the "system" gcc, but it may be more correct to provide a well configured cc toolchain using the gcc from nixpkgs?

**Comment by mrkkrp** [comment]
That's what my fix does essentially: https://github.com/tweag/rules_nixpkgs/pull/16. The toolchain that Bazel infers in not misconfigured per se.

**Comment by guibou** [comment]
I can confirm that:

- I cannot reproduce the bug on NixOS using the provided repository
- I can reproduce the bug on ubuntu (within docker) using the provided repository
- `nix-shell -p gcc` as a workaround works
- #304 does not fix the bug on ubuntu. I tried the following changes in `WORKSPACE`:

```
diff --git a/repro-bug/WORKSPACE b/repro-bug/WORKSPACE
index 48526b1..10a9ab2 100644
--- a/repro-bug/WORKSPACE
+++ b/repro-bug/WORKSPACE
@@ -1,11 +1,12 @@
 workspace(name= "repro_link_error")
 
-other_repo_path="/path/to/repro-archive/other-repo"
+other_repo_path="/repro_link_error/other-repo/"
 
 http_archive(
   name = "io_tweag_rules_haskell",
-  strip_prefix = "rules_haskell-e1eba61f145b5203c748fc53e77e0862e2fc2554",
-  urls = ["https://github.com/tweag/rules_haskell/archive/e1eba61f145b5203c748fc53e77e0862e2fc2554.tar.gz"]
+  strip_prefix = "rules_haskell-abe0d4b3945184da28fcab0aec2727b30cfc9aae",
+  urls = ["https://github.com/tweag/rules_haskell/archive/abe0d4b3945184da28fcab0aec2727b30cfc9aae.tar.gz"]
+  # This is #304, repo tweag/rules_haskell branch link-hs-cc-toolchains on 25 june 2018, 9:00 CEST
 )
 
 load("@io_tweag_rules_haskell//haskell:repositories.bzl",
@@ -68,7 +69,7 @@ register_toolchains("//:ghc-nix-packages-toolchain")
 
 new_local_repository(
     name="other_repo",
-    path=other_repoo_path,
+    path=other_repo_path,
     build_file_content = """
 package(default_visibility = ["//visibility:public"])
 load(
```
