### ISSUE TITLE
gcc: error trying to exec 'cc1': execvp: No such file or directory

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#259]
https://travis-ci.org/iphydf/repro259/jobs/381693316#L1434

Repro: https://github.com/iphydf/repro259

**Comment by ruuda** [comment]
I was able to work around this issue by using GHC from Nixpkgs rather than the bindist.

**Comment by mboes** [comment]
I cannot reproduce. Steps followed:

```
$ docker run -it ubuntu
[...] # install Bazel (as per https://docs.bazel.build/versions/master/install-ubuntu.html#install-on-ubuntu) and make
$ cd /path/to/repro259
$ bazel build //...
$ echo $?
0
```

**Comment by iphydf** [comment]
On Travis it's 100% reproducible: https://travis-ci.org/iphydf/repro259 (e.g. https://travis-ci.org/iphydf/repro259/jobs/393087508#L1382). I can give you push access to that repro repo if it helps?

**Comment by iphydf** [comment]
@ruuda what system are you using where it's reproducible? Do you have a docker image in which it's reproducible?

**Comment by guibou** [comment]
@iphydf I'm interested by the commit right on the repository "iphydf/repro259". I tested on ubuntu / arch linux and I couldn't reproduce the error. However I had to install a few packages on these systems (such as `build-essential` on ubuntu) and perhaps that's just what is missing in your setup.

**Comment by iphydf** [comment]
I added you to the repo as collaborator (you should have received an invitation) yesterday.

The Travis install likely has build-essential. My local install does have that. It has gcc, as, ld, etc.

**Comment by iphydf** [comment]
My local install is Debian 9.

**Comment by iphydf** [comment]
Is there anything I can help with?

**Comment by iphydf** [comment]
It may be related but that pr doesn't fix this issue (I tested this a while ago because I hoped it would). I'll try to reproduce it on a Debian docker image.

**Comment by iphydf** [comment]
I can't do that today. The Travis docker images are here: https://hub.docker.com/u/travisci/ maybe that helps?

**Comment by guibou** [comment]
Full repro at home with this docker file, I will be able to investigate more:

```
FROM travisci/ci-garnet:packer-1512502276-986baf0

RUN apt-get install realpath

RUN git clone https://github.com/iphydf/repro259.git repro259

# install bazel
RUN wget https://github.com/bazelbuild/bazel/releases/download/0.14.1/bazel-0.14.1-installer-linux-x86_64.sh
RUN chmod u+x ./bazel-0.14.1-installer-linux-x86_64.sh
RUN ./bazel-0.14.1-installer-linux-x86_64.sh --user

# preload GHC. This is done separatly from `build @haskell_clock` to cache the GHC fetch and install
RUN cd ./repro259; /root/bin/bazel build @ghc//...

# this is the failing command
CMD cd ./repro259; /root/bin/bazel build @haskell_clock//:clock
```

**Comment by ruuda** [comment]
I was able to reproduce on Ubuntu 16.04 inside a systemd-nspawn container:

```
$ sudo machinectl pull-tar 'https://cloud-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64-root.tar.xz' xenial
$ sudo systemd-nspawn           \
    --machine xenial            \
    --capability CAP_NET_ADMIN  \
    --bind-ro /etc/resolv.conf
root@xenial:~# echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
root@xenial:~# curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
root@xenial:~# sudo apt update
root@xenial:~# sudo apt install bazel build-essential
root@xenial:~# cd /tmp
root@xenial:/tmp# git clone https://github.com/channable/vaultenv --branch bazel
root@xenial:/tmp# cd vaultenv
root@xenial:/tmp/vaultenv# bazel build :vaultenv
```

```
ERROR: /root/.cache/bazel/_bazel_root/c020352ee403395ac8c8b31cb08322ca/external/hackage_memory/BUILD.bazel:8:1: HaskellCppDefines external/hackage_memory/ghc-defs-dump-basement.hspp failed (Exit 1)
gcc: error trying to exec 'cc1': execvp: No such file or directory
`gcc' failed in phase `C pre-processor'. (Exit code: 1)
Target //:vaultenv failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /tmp/vaultenv/BUILD:26:1 HaskellCppDefines external/hackage_memory/ghc-defs-dump-basement.hspp failed (Exit 1)
INFO: Elapsed time: 339.848s, Critical Path: 2.10s
INFO: 93 processes: 93 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by ruuda** [comment]
> [Let's continue both these discussions in #259.](https://github.com/tweag/rules_haskell/pull/304#issuecomment-401694087)

I tested #304 on Ubuntu 18.04, and there it does work! I don’t get [the missing `as` error](https://github.com/tweag/rules_haskell/pull/304#issuecomment-401637425), the build completes successfully.

I’ll try again on 16.04 with `-s` later today or tomorrow.

**Comment by iphydf** [comment]
Repro: build with `bazel build -c dbg`. I get a different error on my system than on travis though.

Travis: https://travis-ci.org/iphydf/repro259/jobs/399246609#L1392
My Debian system:
```
external/haskell_clock/BUILD.bazel:3:1: HaskellBuildLibrary @haskell_clock//:clock failed (Exit 1)

<no location info>: error:
    Warning: Couldn't figure out linker information!
             Make sure you're using GNU ld, GNU gold or the built in OS X linker, etc.
collect2: fatal error: cannot find 'ld'
compilation terminated.
`cc' failed in phase `Linker'. (Exit code: 1)
Target @haskell_clock//:clock failed to build
```

**Comment by ruuda** [comment]
When passing `-s`, on Ubuntu 16.04 in a systemd-nspawn container:

```
root@xenial:/tmp/vaultenv# bazel build :vaultenv -s
INFO: Analysed target //:vaultenv (0 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //:vaultenv [action 'HaskellDummyObjectGhc BazelDummy.o']
(cd /root/.cache/bazel/_bazel_root/c020352ee403395ac8c8b31cb08322ca/execroot/__main__ && \
  exec env - \
    PATH=bazel-out/host/bin/visible-binaries \
  bazel-out/host/bin/visible-binaries/ghc -pgma bazel-out/host/bin/visible-binaries/cc -pgmc bazel-out/host/bin/visible-binaries/cc -pgml bazel-out/host/bin/visible-binaries/cc -pgmP bazel-out/host/bin/visible-binaries/cc -optc-fno-stack-protector -optP-E -optP-undef -optP-traditional -optc-U_FORTIFY_SOURCE -optc-fstack-protector -optc-Wall -optc-B/usr/bin -optc-B/usr/bin -optc-Wunused-but-set-parameter -optc-Wno-free-nonheap-object -optc-fno-omit-frame-pointer -optc-g0 -optc-O2 '-optc-D_FORTIFY_SOURCE=1' -optc-DNDEBUG -optc-ffunction-sections -optc-fdata-sections -optc-g0 -c bazel-out/k8-fastbuild/bin/BazelDummy.hs)
ERROR: /tmp/vaultenv/BUILD:26:1: HaskellDummyObjectGhc BazelDummy.o failed (Exit 1)
cc: error trying to exec 'as': execvp: No such file or directory
`cc' failed in phase `Assembler'. (Exit code: 1)
```

**Comment by iphydf** [comment]
Yes, I get the same error on my Debian system (can't exec `as`) and in the haskell-test branch of my repro259 repo: https://travis-ci.org/iphydf/repro259/jobs/399341484#L1379

**Comment by iphydf** [comment]
To clarify: `haskell_library` now works, but `haskell_test` does not.

**Comment by mboes** [comment]
@iphydf when running your repro in a local Docker container, I run into #324, which might mask the other error you're seeing. The thing with #324, is that one at least is reproducible *everywhere*. So we'll try solving that first and add `dbg` and `opt` to the CI harness to avoid future regressions of this kind. Does the default `fastbuild` configuration work?

**Comment by iphydf** [comment]
Yes fastbuild works for libraries, nothing works for binaries.
