### ISSUE TITLE
Proto toolchain `deps` shouldn't use the `host` configuration

### ISSUE THREAD

**Issue by judah** [tweag/rules_haskell#287]
Our Hazel-based build has been getting link errors:
```
Undefined symbols for architecture x86_64:
  "_externalZZShaskellZZUtextZZStextzm1zi2zi2zi2_DataziTextziEncoding_zdwdecodeUtf8With_closure", referenced from:
      _SuH2_srt in libHSexternalZShaskellZUprotoZUlensZSproto-lens-1.0.0.a(Encoding.o)
  "_externalZZShaskellZZUtextZZStextzm1zi2zi2zi2_DataziTextziEncodingziError_zdfExceptionUnicodeExceptionzuzdcshow_info", referenced from:
      _suhx_info in libHSexternalZShaskellZUprotoZUlensZSproto-lens-1.0.0.a(Encoding.o)
  "_externalZZShaskellZZUtextZZStextzm1zi2zi2zi2_DataziTextziEncoding_zdwdecodeUtf8With_info", referenced from:
      _cuGc_info in libHSexternalZShaskellZUprotoZUlensZSproto-lens-1.0.0.a(Encoding.o)
  "_externalZZShaskellZZUtextZZStextzm1zi2zi2zi2_DataziTextziEncodingziError_zdfExceptionUnicodeExceptionzuzdcshow_closure", referenced from:
      _SuH2_srt in libHSexternalZShaskellZUprotoZUlensZSproto-lens-1.0.0.a(Encoding.o)
  "_externalZZShaskellZZUtextZZStextzm1zi2zi2zi2_DataziTextziEncodingziError_zdfExceptionUnicodeException8_closure", referenced from:
      _cuFh_info in libHSexternalZShaskellZUprotoZUlensZSproto-lens-1.0.0.a(Encoding.o)
      _SuFK_srt in libHSexternalZShaskellZUprotoZUlensZSproto-lens-1.0.0.a(Encoding.o)
```

As far as I can tell, this is a mismatch between the host and target builds:
```
$ shasum bazel-out/*/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext-1.2.2.2.a 
c0a2f82d80cc127ad4bf1534f982b45869a35d45  bazel-out/darwin-fastbuild/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext-1.2.2.2.a
83bc55f85a5260a9e24a25a4f7fd45ec083ab480  bazel-out/host/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext-1.2.2.2.a

$ nm bazel-out/host/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext-1.2.2.2.a | grep _externalZZShaskellZZUtextZZStextzm1zi2zi2zi2_DataziTextziEncoding_zdwdecodeUtf8With_closure
                 U _externalZZShaskellZZUtextZZStextzm1zi2zi2zi2_DataziTextziEncoding_zdwdecodeUtf8With_closure
000000000000eec0 D _externalZZShaskellZZUtextZZStextzm1zi2zi2zi2_DataziTextziEncoding_zdwdecodeUtf8With_closure
                 U _externalZZShaskellZZUtextZZStextzm1zi2zi2zi2_DataziTextziEncoding_zdwdecodeUtf8With_closure
$ nm bazel-out//bin/external/haskell_text/libHSexternalZShaskellZUtextZStext-1.2.2.2.a | grep _externalZZShaskellZZUtextZZStextzm1zi2zi2zi2_DataziTextziEncoding_zdwdecodeUtf8With_closure
# No output
```

I confirmed that this is the problem by checking that `bazel build --distinct_host_configuration=false`, caused the build to succeed.

I believe that Bazel is picking `host` because the proto automatic `deps` are passed through a toolchain rather than a regular rule.  And even though they're on the same architecture, the host cfg builds with "-c opt" and(by default)  the target builds with "-c fastbuild":
https://docs.bazel.build/versions/master/user-manual.html#distinct_host_configuration-true-default

I think the right fix is the approach of `rules_go`, which uses a separate rule `go_proto_compiler` that any `go_proto_library` should depend on:
https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst

For now, we can work around the issue in our project by adding a file at `tools/bazel.rc` with the contents `build --distinct_host_configuration=false`.  Reading the documentation, that shouldn't be that bad unless developers are switching back and forth between `-c opt` and `-c fastbuild` a lot.

**Comment by Profpatsch** [comment]
Can you still reproduce this on a current `rules_haskell` and bazel 0.21?

**Comment by judah** [comment]
I no longer have access to the repo in question.  Pinging @thumphries.

To summarize the original ticket, the question is whether the existing build (that uses both Hazel and haskell_proto_library) is able to rmeove "--distinct_host_configuration=false" from its `tools/blaze.rc` file.

**Comment by Profpatsch** [comment]
We’ve deprecated hazel (and are close to removing it), let’s close this.
