### ISSUE TITLE
Allow to specify non-Haskell source files

### ISSUE THREAD

**Issue by mrkkrp** [tweag/rules_haskell#291]
I.e. what is called by Cabal "extra source files". These should just be visible during compilation, that's all. This is necessary to get packages like `wai-app-static` to compile. They use TH like this:

```
bazel-out/k8-fastbuild/bin/external/haskell_wai_app_static/gen-srcs-wai-app-static/Network/Wai/Application/Static.hs:234:151: error:
    * Exception when trying to run compile-time code:
        images/folder.png: openBinaryFile: does not exist (No such file or directory)
      Code: embedFile "images/folder.png"
    * In the untyped splice: $(embedFile "images/folder.png")
    |
234 | staticAppPieces _ [".hidden", "folder.png"] _ sendResponse = sendResponse $ W.responseLBS H.status200 [("Content-Type", "image/png")] $ L.fromChunks [$(embedFile "images/folder.png")]
    |                                         
```

`data` files do not help here because these will be available at run time only.

**Comment by mjrussell** [comment]
As https://github.com/tweag/rules_haskell/pull/292#issue-192383614 mentions:
> Unfortunately this still doesn't work out-of-the-box with Hackage packages because the path to files should include package names.

Is there any way to get the extra sources working without specifying the package names? This means any hackage package we end up needing to fork (such as what was done for https://github.com/FormationAI/wai/commit/aaa0dca56231c060372004cda46d719ec6cc3ec5), not just make a custom `BUILD` file. This seems a bit unwieldy. Is there any way to do something similar to `strip_prefix` when using `extra_srcs` files?
