### ISSUE TITLE
Declare and combine many toolchains

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#301]
PR #296 introduces a new `extra_binaries` attribute to `haskell_toolchain`. It is mostly used to make secondary tools available to GHC, such as `javac` for `inline-java`, but we can also think about uses cases with `r`,`llvm`, ...

This approach have limitations:

- Boilerplate : user must provides the binaries by themselves, for example by creating a `filegroup` based on a nix package. It may be better to be able to reuse the toolchain job already done for other languages.
- Too coarse: any change in the `extra_binaries` will invalidate any rule using the haskell toolchain and trigger a recompilation. This is not convenient when only a few rules will really use the extra binaries.

We need a solution where the extra toolchain can be declared separately and combined together on a per rule basis using the `toolchains` attribute.

**Comment by mrkkrp** [comment]
> * Boilerplate : user must provides the binaries by themselves, for example by creating a filegroup based on a nix package. It may be better to be able to reuse the toolchain job already done for other languages.

There may be no such toolchain, just an executable produced by e.g. another rule.

> We need a solution where the extra toolchain can be declared separately and combined together on a per rule basis using the `toolchains` attribute.

`toolchains` is something you declare when you define a rule iirc. I think what you mean is "on per-rule-instance" base, i.e. it should be possible to specify extra binaries when we invoke a rule. That will probably require a special attribute to be added to such (all?) rules.

**Comment by Profpatsch** [comment]
The `extra_binaries` attribute no longer exists in current versions of `rules_haskell`, it was deprecated in 0.8.
