### ISSUE TITLE
Avoiding always rebuilding proto toolchain in CI

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#311]
CI times are north of 20 minutes these days. That's unnecessarily high. A fair amount of that time is spent building proto-lens-protoc, which is not in the Nixpkgs cache because we override the versions of dependencies. Down the line we could consider switching over to building the toolchain using Hazel and then using the Bazel remote cache, but this might not be ready quite yet. A very easy fix that can be applied immediately is to use https://cachix.org.

I have already created a `tweag.cachix.org` cache and uploaded a signing key to our `org-global` CircleCI context. So now it's a matter of using `cachix` CLI in each job, and pushing via it anything we build.

**Comment by guibou** [comment]
To read the signing key on CircleCI I need to be an organisation admin. And to push packages to cachix.org, I need to know the signing key.

**Comment by guibou** [comment]
Closed by merged #319 and #314
