### ISSUE TITLE
comment on skylark API to c++

### ISSUE THREAD

**Issue by johnynek** [tweag/rules_haskell#317]
y'all should take a look at:

https://docs.google.com/document/d/1M8JA7kzZnWpLZ3WEX9rp6k2u_nlwE8smsHYgVTSSJ9k/edit#

I see you wrestling with gcc a fair amount, so you will want to make sure you can do what you want to do with that API if at all possible.

**Comment by mboes** [comment]
Thanks for the pointer! LGTM.

What we're interested in most is the full Bazel C++ sandwich.
