### ISSUE TITLE
Cross-compilation

### ISSUE THREAD

**Issue by Fuuzetsu** [tweag/rules_haskell#32]
A very useful feature would be cross-compilation support. Bazel already has the ability to specify if a target should be built on host or target. Cross-compiling Haskell is currently difficult/black magic and this feature would be a big selling point.

Related to #29. https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain might be helpful.

**Comment by joneshf** [comment]
Is there anything I (or anyone else) can do to help move this forward? I'm more than happy to help how I can here if it means cross compilation could work for Haskell.

**Comment by facundominguez** [comment]
Hello @joneshf.

Advancing the support for cross-compilation in rules_haskell is currently in my queue.  One easy way to hook in the effort, although not immediate, is to wait until I wrap up a first version of cross-compilation support and then you could test it and contribute fixes. I hope to resume work on this by February at the latest.

Another line of work would be to offer help enhancing GHC to support compilation with plugins: https://gitlab.haskell.org/ghc/ghc/-/issues/14335

Another approach would be for me to share the work-in-progress. Though there's little help I can offer understanding the issues with it, until I have more availability. Other folks at Tweag might be able to answer questions specific to the implementation of rules_haskell.

**Comment by joneshf** [comment]
> Advancing the support for cross-compilation in rules_haskell is currently in my queue. One easy way to hook in the effort, although not immediate, is to wait until I wrap up a first version of cross-compilation support and then you could test it and contribute fixes. I hope to resume work on this by February at the latest

More than happy to wait if there's already stuff in the works. I've waited this many years for cross-compilation support, a bit more time isn't that big a deal. Looking forward to testing out what you've got.

> Another approach would be for me to share the work-in-progress. Though there's little help I can offer understanding the issues with it, until I have more availability. Other folks at Tweag might be able to answer questions specific to the implementation of rules_haskell.

Also happy to give the wip stuff a whirl if you're up for making it available. No worries if not.

**Comment by facundominguez** [comment]
I have shared the work in progress in https://github.com/tweag/rules_haskell/tree/fd/cross-ghc
Approaching it would require looking at the changes that it does on top of master. It also refers to changes in rules_nixpkgs, that deserve attention.

The way I'm using to try compilation is
```
cd cross-sandbox
nix-shell --pure --run "cd bazel-project; bazel build //... --platforms=//:myplatform"
```
and currently, it fails to find some toolchains. The nix setup for cross-compilation is the same as in https://github.com/tweag/ghc-cross-sandbox, running splices on the target platform.

I think onboarding the project this way must be somewhat difficult, but you are welcome to asses it yourself.

**Comment by facundominguez** [comment]
There was some progress last week. cabal_wrapper was assuming so far that the execution and the target platforms were the same, and we changed that in #1493 

I'm now looking into removing the same assumption from the cc_wrapper.sh script that rules_haskell produces.

**Comment by facundominguez** [comment]
Another PR #1505 makes a first pass at dealing with the cc_wrapper.

**Comment by facundominguez** [comment]
The next step is having `rules_haskell` build `Setup.hs` for the execution platform instead of calling `runghc Setup.hs`. Firstly, `runghc` as it comes in the cross compiler is a binary for the target platform. Secondly, even if we change it to target the execution platform instead, we would have to use the external interpreter to run Setup.hs linking it with a Cabal library for the target platform. 

Our first bet is that the interaction with autoconf and other build tools will go smoother if we run setup in the build platform.

**Comment by joneshf** [comment]
I appreciate the updates!

I didn't say before, but I don't think I can contribute at the moment. I'm still actively following the progress and excited to see what ends up happening here.

**Comment by facundominguez** [comment]
The next issue to fix is that rules_haskell allows only one haskell toolchain to be used per build. But when cross-building we need at least two toolchains (one to build/interpret Setup.hs and another one to build for the target platform).

 These names are used for all registered haskell toolchains https://github.com/tweag/rules_haskell/blob/ec37a63448ecbc0e3fd3e8ebaaada521e1781f17/haskell/nixpkgs.bzl#L222-L225 We should use different names for each toolchain, so more than one toolchain can be used.

**Comment by facundominguez** [comment]
Next issue, Cabal is unable to find hsc2hs https://github.com/tweag/rules_haskell/pull/1514
Tweaking the inputs to the cabal_wrapper seems to fix it.

**Comment by facundominguez** [comment]
Next issue: the cross-compiling ghc can't find `opt` and `llc`. These are llvm tools that would be required to produced code for arm. One thing to figure out is why our [initial setup](https://github.com/tweag/ghc-cross-sandbox/blob/main/target-th/shell.nix) didn't need to deal with them explicitly. Another thing to do is to produce a GHC wrapper that brings this tools into the PATH.

**Comment by facundominguez** [comment]
I'm merging the work in progress in https://github.com/tweag/rules_haskell/pull/1516, https://github.com/tweag/rules_nixpkgs/pull/163 and https://github.com/tweag/rules_nixpkgs/pull/164

The example project there is already capable of producing arm artifacts with `haskell_binary`, `haskell_library` and `stack_snapshot`.

There's a bit of nix configuration that I need to figure out how to integrate from https://github.com/tweag/rules_haskell/tree/fd/cross-ghc

**Comment by aherrmann** [comment]
> The example project there is already capable of producing arm artifacts with `haskell_binary`, `haskell_library` and `stack_snapshot`.

Great work! This is wonderful news! :tada:

**Comment by facundominguez** [comment]
I submitted the cross-compilation example in https://github.com/tweag/rules_haskell/pull/1517.
The next bit of work would be building it in CI.

**Comment by facundominguez** [comment]
The cross-compilation example builds in CI now: https://github.com/tweag/rules_haskell/pull/1523
The next bit of work would be documenting how to cross-compile in the user guide.

**Comment by facundominguez** [comment]
I submitted some documentation for cross-compiling: https://github.com/tweag/rules_haskell/pull/1526

**Comment by aherrmann** [comment]
Closing this issue as support for cross-compilation has been implemented.
