### ISSUE TITLE
ghc: could not execute: touch

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#327]
Trying to compile "language-c", I get this error. If needed, I can produce a repro for it, but it sounds like "touch" just needs to be added to some visible binaries list somewhere.

**Comment by Profpatsch** [comment]
Can you post the exact commands you ran?

**Comment by iphydf** [comment]
Once #259 is fixed I can make a repro on Travis.

**Comment by mrkkrp** [comment]
Maybe the workaround from #376 applies to this as well.

**Comment by iphydf** [comment]
Yes, that workaround works.
