### ISSUE TITLE
HaskellHsc2hs needs include (-I) flags to find include files

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#329]
E.g. in https://github.com/iphydf/toktok-stack/blob/upgrade-deps/third_party/haskell/BUILD.foundation#L21 I need to pass `-I` flags to ghc for `-XCPP` to find the files in `cbits`. These flags should also be passed to `hsc2hs`.

**Comment by mrkkrp** [comment]
IIRC you need to do it via `haskell_cc_import` to get includes passed to pre-processors.

**Comment by iphydf** [comment]
I can't get it to work with `haskell_cc_import`: https://github.com/iphydf/toktok-stack/blob/upgrade-deps/third_party/haskell/BUILD.foundation#L10

I don't see a way to pass include flags there.

**Comment by mrkkrp** [comment]
You probably should try to use the `hdrs` attribute.

**Comment by mrkkrp** [comment]
Have you resolved this one? If not, please prove a repro ,the last link gives me 404.

**Comment by iphydf** [comment]
Yes, resolved.
