### ISSUE TITLE
`repl_ghci_flags` for `haskell_toolchain`.

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#331]
`bazel build //:something` is not using the same GHC flags as `bazel run //:something-repl`.

The "normal" build will use `compiler_flags` from the toolchain and the rule, when the "repl" build will only use `repl_ghci_flags` from the rule.

@mrkkrp thinks it is a good idea to keep a separation between both set of flags. However setting `repl_ghci_flags` for each rule is too much boilerplate.

We can add a `repl_ghci_flags` in `haskell_toolchain` with the same semantic as `compiler_flags`, but only for repl.

**Comment by mboes** [comment]
> @mrkkrp thinks it is a good idea to keep a separation between both set of flags.

Why?

**Comment by mrkkrp** [comment]
I guess there may be cases when some `compile_flags` may be undesirable to pass to GHCi. I'm not 100% sure though about this.

**Comment by mboes** [comment]
We need to optimize for the common case, whichever it is. My hunch is that it's likely to be that the set of flags for both matches exactly. And make the uncommon cases possible.

> A possible example could be -O2?

That will be ignored by GHCi. Also, blanket -O2 in the toolchain would be a terrible idea for a user to try.

**Comment by guibou** [comment]
@mboes so do you suggest that repl should inherit `compiler_flags` by default?

**Comment by mboes** [comment]
that's one possibility, yes. I haven't been paying attention to the details here so I don't have an opinion about the best solution.

**Comment by mboes** [comment]
I agree about the poor naming.

I think the behaviour you propose can be very surprising. Best to let `repl_ghci_flags` (or whatever it ends up being called) augment `compiler_flags`. Since nearly all flags in GHC are invertible, so long as `repl_ghci_flags` takes precedence (by being passed after `compiler_flags` on the command line), this shouldn't be a problem.

**Comment by guibou** [comment]
@m: so `compiler_flags` are passed to repl as well, and `repl_ghci_flags` extends it? I'm ok with that. I'll do a PR soon.

**Comment by mboes** [comment]
Correct.
