### ISSUE TITLE
Use external interpreter when compiling with profiling

### ISSUE THREAD

**Issue by mrkkrp** [tweag/rules_haskell#338]
Currently (as of #332) to compile modules that use TH with profiling we also compile them without profiling because RTS that GHC is linked with is without profiling and so it needs object files without profiling to run TH. This is not very nice and probably less efficient than using the newer `-fexternal-interpreter` that was introduced in GHC 8.0 to solve exactly that problem.

See also:
* https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html?highlight=#ghc-flag--fexternal-interpreter
* https://ghc.haskell.org/trac/ghc/wiki/RemoteGHCi

**Comment by mrkkrp** [comment]
I tried to mess with this one today and discovered the following:

* To register a package dynamic library has to be present, otherwise `ghc-pkg` complains.
* We still cannot compile dynamic library with profiling because GHC doesn't come with dynamic object files with profiling enabled. `-fexternal-interpreter` doesn't seem to help in that case.

**Comment by mboes** [comment]
Could we use `ghc-pkg --force` here? It looks safe to me in this case, but you'd have to think carefully about whether that's really the case.

**Comment by mrkkrp** [comment]
An update: while working on "arbitrary file layouts" I noticed that `-fexternal-interpreter` probably should work if we don't set extensions to anything non standard. GHC should pick whatever it wants, i.e. just plain `.o` then it should start working.
