### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [tweag/rules_haskell#345]
Hi @mboes 

I am a graphic designer. I wanted to contribute to the your repository and i designed a logo for it. I tried to represent the function of the project. I used some color variations of Haskell. What do you think about? If you like it, i can send a pr.  Also, Is there anything you want to edit?

![haskellrules](https://user-images.githubusercontent.com/36298335/42881192-78d742fe-8a9f-11e8-8405-3ea66d6024dc.jpg)

**Comment by mboes** [comment]
This looks good! Thanks for your contribution. We'd go with the first variant (orange) I think. The `rules_haskell` naming is a convention in the Bazel community, so I think we should stick with that. Perhaps try turning the all caps title into small caps?

**Comment by reallinfo** [comment]
Sure, How is these and Which one do you prefer?

![rules-haskell](https://user-images.githubusercontent.com/36298335/42998663-98e4c794-8c23-11e8-8560-ea409bca363a.jpg)

**Comment by mboes** [comment]
Yup. Thanks!

**Comment by reallinfo** [comment]
I sent a pr. (all files) 

https://github.com/tweag/rules_haskell/pull/353

If there is a problem, feel free to say me. Have a nice day!
