### ISSUE TITLE
Refactor REPL code to use runfiles

### ISSUE THREAD

**Issue by mrkkrp** [tweag/rules_haskell#348]
Now that `--direct_run` is the default behavior I think nothing prevents us from dropping the current hacks and just specify all things that are necessary to run a REPL as runfiles.

**Comment by Profpatsch** [comment]
After a very helpful one-on-one with Mark, we started factoring out the wrapper script inputs into `runfiles`, but hit a few obstacles. Here’s a commit with the first few changes: https://github.com/Profpatsch/rules_haskell/commit/9d067b900ffefaba8d60735707bc437b60aebb1c

**Comment by Profpatsch** [comment]
There’s a simple improvement that doesn’t let the wrapper script depend on the current working dir: https://github.com/tweag/rules_haskell/pull/366

As a next step, there’s libraries for a few different languages to detect the path of `runfiles` at runtime. The bash one is a pretty ugly hack, so we’ll use the python implementation.
Here’s a first WIP: https://github.com/tweag/rules_haskell/pull/366

**Comment by Profpatsch** [comment]
I used a bit of spare time I had today to continue this: https://github.com/Profpatsch/rules_haskell/commit/fc06c1c160b8ebab0e4af18f7776bebb9a7304b2

A bit unsure about how to pass the ghci args to the python script.

**Comment by Profpatsch** [comment]
I took another shot at this today: https://github.com/Profpatsch/rules_haskell/commit/c7603a9fc4952287b0a9286fca758fe26e69108e

@mrkkrp could you take a look at this, I can’t get it to pass the bash library to the haskell rules (see commit message). Am I passing this wrong? https://github.com/Profpatsch/rules_haskell/commit/c7603a9fc4952287b0a9286fca758fe26e69108e#diff-03670cc4bf4a3f960a6946e79ec27b13L316

**Comment by Profpatsch** [comment]
Should be fixed by https://github.com/tweag/rules_haskell/pull/736

**Comment by mboes** [comment]
OK closing in that case. Please reopen if this is still an issue.
