### ISSUE TITLE
doctest does not find packages

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#367]
This commit: 
https://github.com/tweag/rules_haskell/commit/4b8abee80a797127c19ef17bd418bcd9d9197968

fails:

```
[nix-shell:~/tweag/rules_haskell]$ bazel build //tests/haskell_doctest:doctest-lib
INFO: Analysed target //tests/haskell_doctest:doctest-lib (1 packages loaded).
INFO: Found 1 target...
ERROR: /home/guillaume/tweag/rules_haskell/tests/haskell_doctest/BUILD:53:1: error executing shell command: '
    external/doctest/bin/doctest "$@" > bazel-out/k8-fastbuild/bin/tests/haskell_doctest/doctest-log-doctest-lib-testsZShaskellZUdoctestZSlib-b-1.0.0 2>&1 || rc=$? && cat bazel-out/k8-fastbuild/bi...' failed (Exit 1)
doctest: <command line>: cannot satisfy -package lens-labels
    (use -v for more information)
Target //tests/haskell_doctest:doctest-lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.544s, Critical Path: 0.09s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I used `lens-label` because that's not a package which comes builtin with GHC by default. All the other example are using packages such as `bytestring` or `base` which are builtin with GHC.

**Comment by guibou** [comment]
`doctest` needs ghc options, such as `--package-db` to find the package. For now they are not passed. I'm working on it.

**Comment by Profpatsch** [comment]
Hm, guibhui, I suspect you will duplicate a lot of functionality that is used to generate ghci inputs: https://github.com/tweag/rules_haskell/blob/master/haskell/private/actions/repl.bzl#L51

**Comment by guibou** [comment]
I'm closing. I'm still experimenting a similar issue, but the current repro and issue description is not up to date.
