### ISSUE TITLE
python dlopen cc_haskell_import breaks with foreign imports

### ISSUE THREAD

**Issue by ghorn** [tweag/rules_haskell#370]
I've been trying to get python to call haskell using `ctypes` which uses `dlopen`. I got it working following advice i found here https://github.com/bazelbuild/bazel/issues/1475. The approach is to make a shared library `libfoo.so` using `cc_binary`, then in your `python_binary` specify `data = ["libfoo.so"]`.

I have a full example hijacking `tests/cc_haskell_import` 
here https://github.com/ghorn/rules_haskell/commit/bf1a2a79069b37d2e554247b24256a44c554b707. Check out that patch and run
`nix-shell --run 'bazel run //tests/cc_haskell_import:python_add_one'`

That works.

The problem is when the haskell library does a `foreign import ccall` on a `cc_library`, then `dlopen` can't find the C shared library. See https://github.com/ghorn/rules_haskell/commit/71315ccb3823cc8319da4b117a0aa1fef3e03cb6 for an example reproducing the problem.

**Comment by guibou** [comment]
maybe related to https://github.com/bazelbuild/bazel/issues/1475

**Comment by mboes** [comment]
Another potentially related issue: https://github.com/bazelbuild/bazel/issues/701.

**Comment by Profpatsch** [comment]
So, what we have is

```
Traceback (most recent call last):
  File "/home/philip/.cache/bazel/_bazel_philip/1cdc2152e51c0757bab1130c4f3bcee9/execroot/io_tweag_rules_haskell/bazel-out/k8-py3-fastbuild/bin/tests/cc_haskell_import/python_add_one.runfiles/io_tweag_rules_haskell/tests/cc_haskell_import/python_add_one.py", line 10, in <module>
    foreignlib = ctypes.cdll.LoadLibrary('tests/cc_haskell_import/libadd_one.so')
  File "/nix/store/r99pik3abzrizbka8906ccs7vj837356-python-2.7.15/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/nix/store/r99pik3abzrizbka8906ccs7vj837356-python-2.7.15/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtests_Scc_Uhaskell_Uimport_Sourclib_libourclib.so: cannot open shared object file: No such file or directory
```

We have three libraries in our case
- C (`ourclib`)
- A (`hs-lib-a`, built with `haskell_library`, requires the `.so` of C)
- B (`hs-lib-b`, built with `haskell_library`, requires B)
and one binary, `libadd_one.so`, which is `cc_binary` with `linkstatic` and `linkshared`, to create a correctly linked binary that Python’s `ctypes` is able to open.

The error above means C cannot be found. And indeed, when I add a call to `ldd` to our python script:

```
subprocess.call(["ldd", 'tests/cc_haskell_import/libadd_one.so'])
```

We get

```
	libtests_Scc_Uhaskell_Uimport_Sourclib_libourclib.so => not found
libHStestsZSccZUhaskellZUimportZShs-lib-a-1.0.0-ghc8.2.2.so => /home/philip/.cache/bazel/_bazel_philip/1cdc2152e51c0757bab1130c4f3bcee9/execroot/io_tweag_rules_haskell/bazel-out/k8-py3-fastbuild/bin/tests/cc_haskell_import/python_add_one.runfiles/io_tweag_rules_haskell/tests/cc_haskell_import/../../_solib_k8/_U_S_Stests_Scc_Uhaskell_Uimport_Clibadd_Uone.so___Utests_Scc_Uhaskell_Uimport/libHStestsZSccZUhaskellZUimportZShs-lib-a-1.0.0-ghc8.2.2.so (0x00007f9a2197c000)
	libHStestsZSccZUhaskellZUimportZShs-lib-b-1.0.0-ghc8.2.2.so => /home/philip/.cache/bazel/_bazel_philip/1cdc2152e51c0757bab1130c4f3bcee9/execroot/io_tweag_rules_haskell/bazel-out/k8-py3-fastbuild/bin/tests/cc_haskell_import/python_add_one.runfiles/io_tweag_rules_haskell/tests/cc_haskell_import/../../_solib_k8/_U_S_Stests_Scc_Uhaskell_Uimport_Clibadd_Uone.so___Utests_Scc_Uhaskell_Uimport/libHStestsZSccZUhaskellZUimportZShs-lib-b-1.0.0-ghc8.2.2.so (0x00007f9a21978000)
```

on stdout.

It gets weirder: running `ldd` from a command line (outside of `bazel run`) on the same `so` finds the C library just fine (even if I use exactly the same folder our `run` should see, the `runfiles` folder:

```
$ ldd /home/philip/.cache/bazel/_bazel_philip/1cdc2152e51c0757bab1130c4f3bcee9/execroot/io_tweag_rules_haskell/bazel-out/k8-py3-fastbuild/bin/tests/cc_haskell_import/python_add_one.runfiles/io_tweag_rules_haskell/tests/cc_haskell_import/libadd_one.so | grep ourclib
	libtests_Scc_Uhaskell_Uimport_Sourclib_libourclib.so => not found
	libtests_Scc_Uhaskell_Uimport_Sourclib_libourclib.so => bazel-out/k8-py3-fastbuild/bin/tests/cc_haskell_import/libtests_Scc_Uhaskell_Uimport_Sourclib_libourclib.so (0x00007f51dfbf6000)
```

So it’s found once and then not found in the same run of `ldd`? The name seems to be the same.

**Comment by Profpatsch** [comment]
Furthermore, we can follow the search chain ourselves:

```
$ objdump -p <path/to>/python_add_one.runfiles/io_tweag_rules_haskell/tests/cc_haskell_import/libadd_one.so | grep RUNP
  RUNPATH              $ORIGIN/../../_solib_k8/_U_S_Stests_Scc_Uhaskell_Uimport_Clibadd_Uone.so___Utests_Scc_Uhaskell_Uimport:$ORIGIN/../../_solib_k8/_U@ghc_S_S_Cthreaded-rts___Uexternal_Sghc_Slib_Sghc-8.2.2_Srts:/nix/store/l0adcz8y05vajfi483a7qv31i03rspqq-glibc-2.27/lib:/nix/store/i5znwsdi9yybfydd1kbdrsq5s4phjm93-gcc-7.3.0-lib/lib
$ ORIGIN=$(dirname $(readlink <path/to>/python_add_one.runfiles/io_tweag_rules_haskell/tests/cc_haskell_import/libadd_one.so))
[nix-shell:~/code/bazel/rules_haskell]$ ls $ORIGIN/../../_solib_k8/_U_S_Stests_Scc_Uhaskell_Uimport_Clibadd_Uone.so___Utests_Scc_Uhaskell_Uimport
libHStestsZSccZUhaskellZUimportZShs-lib-a-1.0.0-ghc8.2.2.so  libHStestsZSccZUhaskellZUimportZShs-lib-b-1.0.0-ghc8.2.2.so
```

So the two haskell libraries (A and B) live in that directory. A should have C as dependency and accessible from the `RUNPATH`, and indeed:

```
$ objdump -p ${ORIGIN}/../../_solib_k8/_U_S_Stests_Scc_Uhaskell_Uimport_Clibadd_Uone.so___Utests_Scc_Uhaskell_Uimport/libHStestsZSccZUhaskellZUimportZShs-lib-a-1.0.0-ghc8.2.2.so | grep RUNP
  RUNPATH              $ORIGIN/../../../../../bazel-out/k8-py3-fastbuild/bin/tests/cc_haskell_import:/nix/store/…
$ ORIGIN=$(dirname $(readlink </path/to>/libHStestsZSccZUhaskellZUimportZShs-lib-a-1.0.0-ghc8.2.2.so))
$ $ ls $ORIGIN/../../../../../bazel-out/k8-py3-fastbuild/bin/tests/cc_haskell_import
_objs                                                        libadd_one.so                                         objects-hs-lib-b
interfaces-hs-lib-a                                          libadd_one.so-2.params                                python_add_one
…
```

It should reach the file `libadd_one.so` just fine. But it’s not accessible from within the `bazel run` environment. Why?

Since the folder with our `haskell_library` `.so` links can be accessed just fine, adding transitive `.so`s to that folder could be one solution, although I don’t know whether that’s just a hack and the transitive shared objects should be found, even through multiple `RUNPATH`s.
Maybe the final filename from concatenating the shared objects is too long (it doesn’t seem to get normalized in any intermediate steps) and internally truncated?

**Comment by Profpatsch** [comment]
This is completely fixed in https://github.com/tweag/rules_haskell/pull/614, [even when run inside of tests](https://github.com/tweag/rules_haskell/pull/693).
