### ISSUE TITLE
haskell interpreted executable

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#382]
In a project, I have some `haskell_binary` (with dependencies) with an interesting usage pattern:

- They are run as many time as they are built
- Building time is aweful (6m30s in `-c fastbuild`)
- Execution time is short and does not profit at all from compilation (<1s)
- Execution time in "interpreted" haskell is faster. (2m30s "bootstrapping" and 1s execution)

So I thought that it may be interesting to have a solution to run an haskell executable in interpreted mode. I'm opening this issue to discuss the design.

- Should we add a new rule?
- Should we add an attribute to the existing `haskell_binary` rule?

**Comment by mboes** [comment]
So to be clear, you're saying that morally, `ghc -O0` is between 2x and 3x slower than the compilation time in `ghci` in your particular use case?

**Comment by guibou** [comment]
@mboes `ghc -O0` is slower than `runhaskell` (which is kind of a ghci with interpreted load of modules)

**Comment by Profpatsch** [comment]
Does https://github.com/tweag/rules_haskell/pull/630 implement what is requested here?

**Comment by guibou** [comment]
@Profpatsch partially, but that feature is not needed anymore.
