### ISSUE TITLE
`haskell_lint` doesn't forward the needed flags to GHC

### ISSUE THREAD

**Issue by regnat** [tweag/rules_haskell#390]
A lot of packages require passing a number of flags to GHC, like `-I` or `-L` flags for system dependencies. While `haskell_library` and `haskell_binary` do handle that, the `haskell_lint` rule doesn't, which makes it impossible to use.

For example, trying to build the following target (on this repo) will fail with `fatal error: main_definition.h: No such file or directory` because the required `-Itests/textual-hdrs/include` isn't passed to ghc during the `lint` job:

```python
haskell_lint(
    name = "lint",
    deps = ["//tests/textual-hdrs"],
)
```

Likewise, the target `//tests/library-with-sysincludes` builds fine, but the following target will fail because of an unresolved reference to `TH_foo_closure`:

```python
haskell_lint(
    name = "lint",
    deps = ["//tests/textual-hdrs"],
)
```

**Comment by regnat** [comment]
/cc-ing @guibou who hit a similar issue

**Comment by mboes** [comment]
@regnat still an issue? It sounds like the fix should be easy.

**Comment by regnat** [comment]
@mboes It's not an issue for me anymore because I worked around it at the time, but yes, the bug is still there.

Indeed, it should be relatively easy to fix this (I actually just did it locally by copy-pasting some logic from the `haskell_doctest` rule, will open a PR in a minute), though this issue and others such as #367 or #400 (and in particular [this remark](https://github.com/tweag/rules_haskell/issues/367#issuecomment-407417332) from @Profpatsch ) makes me wonder whether we have the right approach for this because right now each one of the `haskell_lint`,`haskell_doctest`,`haskell_doc` and `@repl` rules have to re-implement the same logic (and each time with slightly different bugs it seems ;) ) to get access to all the dependencies

**Comment by mboes** [comment]
@regnat could you revive #498 and push it past the finish line?

**Comment by regnat** [comment]
@mboes not sure there's a need for it since #931 seems to make consensus on removing it

**Comment by mboes** [comment]
Yes. If #931 gets merged then let's close this.

**Comment by mboes** [comment]
#931 got merged, so closing.
