### ISSUE TITLE
Out with BUILD, in with BUILD.bazel.

### ISSUE THREAD

**Issue by philderbeast** [tweag/rules_haskell#412]
It seems that `BUILD` files are no longer recommended and we should be using `BUILD.bazel`. Please update the docs and tutorial accordingly.

https://github.com/bazelbuild/rules_go/issues/866#issuecomment-333565005

> BUILD.bazel should be preferred for new projects. Bazel recognizes both names but prefers BUILD.bazel if both are present. The problem with BUILD is that it frequently collides with files or directories named "build" on case-insensitive file systems in projects that didn't previously use Bazel. The BUILD.bazel name was introduced about a year ago to avoid that collision.

I got bitten by this right away as I already have a `build` folder in the root of a project I'm trying out with rules_haskell and bazel.

**Comment by mboes** [comment]
PR's appreciated.

**Comment by philderbeast** [comment]
I'll give this a go.
