### ISSUE TITLE
decoding failure when haskell package contains non-ascii symbols and python3 is used

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#426]
rules_haskell does not work if the `python` provided by the environment is python3 and if a haskell package database contains non-ascii symbols.

For a simple repro, change `python` to `python3` in `tests/ghc.nix` and run the testsuite again. It should fail, because the `base-orphans` package contains non ascii chars in the name of the authors "João Cristóvão", you can see the faulty file at `bazel-out/host/bin/tests/ghc-global-pkgdb`:

```
[nix-shell:~/tweag/rules_haskell]$ head -n 1012 bazel-out/host/bin/tests/ghc-global-pkgdb | tail -n 1
           (c) 2014-2017 João Cristóvão,
```

This file comes from `ghc-pkg dump` earlier in the process.

# Error discussion

rules_haskell depends on `python` from the environment for the script `./haskell/private/ls_modules.py` which is used for compile rules.

This script is compatible python2 and 3, but with a different behavior when it comes to character encoding. One of the main difference between python 2 and 3 is that file system functions (i.e. `read` / `open`) uses array of bytes in python2  and array of opaque unicode characters in python 3. This means that all the file operations in python3 take an `encoding` attribute to specify how to decode the file (stored in bytes) to output "unicode" string.

# Possible solutions

- Continue to use byte and write the python script to use bytes in python3. This is the solution of maximum compatibility, because we keep the currently used behavior of python2.
- Start using "unicode" even in python2. The documentation of `ghc-pkg dump` states that the file is encoded in utf-8:

>  ghc-pkg dump
    Dump the registered description for every package.  This is like
    "ghc-pkg describe '*'", except that it is intended to be used
    by tools that parse the results, rather than humans.  The output is
    always encoded in UTF-8, regardless of the current locale.

- rewrite this logic in skylark. This is the more robust solution, and we'll drop the python dependency, but also the more complex.

**Comment by guibou** [comment]
Offline @Profpatsch suggested to simply set the shebang to `#!/usr/bin/env python2` and get done with that. That's a robust solution, but it also forces the users of python3 to provision their environment with `python2` too.

I pushed #427, which introduces compatibility with python 2 and 3 with a really small change. What's your point of view?

@mboes ?

**Comment by mboes** [comment]
AFAIR Bazel itself is only Python2, as is the case of many Google things. e.g. Skydoc (which we use) only works with Python2 (see https://github.com/bazelbuild/skydoc/issues/57). So pinning to Python2 is a contingency of our upstream dependencies I'd say. Not much we can do here beyond advertize that Python==2.* is a prereq.

**Comment by guibou** [comment]
Ok, so perhaps we can FORCE the script to use python2 instead of a generic "python". I'm pushing a PR for that.

**Comment by guibou** [comment]
Sorry about my last message, I didn't realized you closed because of PR merged
