### ISSUE TITLE
register_toolchain(s)

### ISSUE THREAD

**Issue by philderbeast** [tweag/rules_haskell#433]
Some [doc comments](http://api.haskell.build/haskell/toolchain.html) mention `register_toolchain`;

https://github.com/tweag/rules_haskell/search?q=register_toolchain&unscoped_q=register_toolchain&type=Code

Isn't the function [`register_toolchains`](https://docs.bazel.build/versions/master/skylark/lib/globals.html#register_toolchains)?

In WORKSPACE;
```
- register_toolchains("//:ghc")
+ register_toolchain("//:ghc")
```

```
> bazel build //...
ERROR: /.../WORKSPACE:144:1: name 'register_toolchain' is not defined
(did you mean 'register_toolchains'?)
ERROR: Error evaluating WORKSPACE file
...
```

**Comment by Profpatsch** [comment]
Looks about right.
