### ISSUE TITLE
Consider not using `ar` from `cpp` fragments.

### ISSUE THREAD

**Issue by Fuuzetsu** [tweag/rules_haskell#45]
We now use `ctx.host_fragments.cpp.ar_executable` to get `ar`. We may want to consider making the user pass `ar` as part of toolchain instead: this way we always ensure it's available and that it's the version user expects.

However `ar` is usually available/doesn't change so it's low priority.

**Comment by mboes** [comment]
I'm tempted to say that if the user wants to carefully control the version of `ar`, then the user should do so via `CROSSTOOL` or whatever is the mechanism-du-jour for modifying the CC toolchain. Arguably, we should consider `ar` a detail of the CC toolchain, and always agree with the CC toolchain on which `ar` to use when linking.

Close?
