### ISSUE TITLE
CI should build with multiples bazel version

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#452]
Current CI script uses `bazel` from a pinned `nixpkgs` commit. However we need to take care of forward and backward compatibility.

We need to define a compatibility policy and create a matrix of build targeting old bazel version and new one as soon as they are released.

**Comment by Profpatsch** [comment]
I’d always test with the latest version of our nixpkgs checkout, plus a backport of the oldest bazel version we still want to support with `rules_haskell`.

**Comment by guibou** [comment]
I think we decided to only support one version of bazel (the latest), so this can be closed.
