### ISSUE TITLE
Build against multiple versions of GHC

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#458]
In addition to testing against multiple versions of bazel (see #452), we should make an effort to be compatible against multiple versions of GHC (especially since there will be a GHC release every six months from now on).

nixpkgs keeps a few ghc package sets around, so it should be easy to run our test suite against them.

**Comment by GuillaumeGen** [comment]
Is the solution introduced by #1790 sufficient to close it (it tests all the GHC versions listed in https://github.com/tweag/rules_haskell/blob/5ac5e631b073edbdcfbb099afc1e7c859cd9cea7/haskell/gen_ghc_bindist.py#L18), or do we want also to have a mechanism to test against all GHC versions provide by nixpkgs?

**Comment by avdv** [comment]
This is quite related to https://github.com/tweag/rules_haskell/issues/1878

Currently we are checking GHC versions 9.2, 9.4, and 9.6 on CI. Support for GHC 9.8 is planned.
