### ISSUE TITLE
The `-repl` rules don't work with `-XNoImplicitPrelude`

### ISSUE THREAD

**Issue by regnat** [tweag/rules_haskell#462]
If a module in a library has `{-# LANGUAGE NoImplicitPrelude #-}`, then the ghci init script is run with `NoImplicitPrelude` and thus fails because none of the used functions is available.

#### Steps to reproduce

```shell
# Generate a new project
curl  https://haskell.build/start | sh

# Switch to a recent-enough rules_haskell commit
sed -i 's/v\?0\.6/039716ad374f25e76f2a58b2c8c7f62cef3f092b/' WORKSPACE

# Add a module with -XNoImplicitPrelude on it
mkdir src
echo "{-# LANGUAGE NoImplicitPrelude#-}\nmodule Foo where\n" > src/Foo.hs

# Try to run the repl
bazel run //:MY_LIBRARY_NAME-repl
```

#### Expected behavior

The repl should run fine, with the module `Foo` open

#### Actual behavior

The init script fails with:

```
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Foo              ( src/Foo.hs, interpreted )
Ok, one module loaded.
<interactive>:6:35: error:
    Variable not in scope:
      (>>=) :: IO FilePath -> (FilePath -> IO FilePath) -> IO FilePath
<interactive>:9:3: error:
    Variable not in scope: return :: (FilePath, Handle) -> IO (a0, b0)
Foo              ( src/Foo.hs, interpreted )
<interactive>:14:10: error:
    • Variable not in scope: rules_haskell_stdout_copy_h :: Handle
    • Perhaps you meant ‘rules_haskell_stdout_dupe’ (line 3)
-- (and a whole page more of errors)
```

Additionnaly module `Foo` is `:add`-ed, but not imported

**Comment by regnat** [comment]
I first thought of a ghci bug, but it actually makes sense: `:load Foo.hs` means that the scope of the repl should be the scope inside the `Foo` module, so if `Foo` has `NoImplicitPrelude`, so should have the interactive session − we have a similar bug if `Foo` redefines `>>=` for example.

`Prelude` remains available qualified however, so simple (although boring) workaround is to qualify all the functions used in the repl script.

**Comment by Profpatsch** [comment]
> `Prelude` remains available qualified however, so simple (although boring) workaround is to qualify all the functions used in the repl script.

+1
