### ISSUE TITLE
Document version attribute and how it affect version macro generation

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#465]
CPP version macro are only generated when `version` attribute is set on `haskell_binary` and `haskell_library`. This is documented indirectly in the `version` attribute documentation, but discovery is difficult.

A section in the documentation about CPP macro, the associated rules_haskell design and `version` attribute should be added.

**Comment by Profpatsch** [comment]
@guibhou there were some changes to this right? Is the issue still relevant?

**Comment by guibou** [comment]
@Profpatsch still open.
