### ISSUE TITLE
`run foo-repl` should not pick up anything outside of the bazel project

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#470]
(… apart from the user’s `.ghci` file, and even that is debatable)

@regnat had a broken package database in his home folder, and the `-repl` target’s imports got broken in the process, because ghci used the package database from the home folder.

We need to make sure our ghci scripts exclude all paths and information from outside the bazel workspace.

**Comment by regnat** [comment]
In the case at hand, https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/packages.html#package-databases suggests that `-no-user-package-db` would fix it, but maybe there are other flags to pass too (`-no-global-package-db`? I'm not sure what these dbs correspond to)

**Comment by mboes** [comment]
That sounds bad. Yes - we need to tell GHCi never to look in the home folder, or for that matter also insulate it from [this pesky stuff](https://github.com/haskell/cabal/issues/4542).

**Comment by mboes** [comment]
Fixed in #514.
