### ISSUE TITLE
ld complains about libffi.so.7 vs libffi.so.6 at link time

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#481]
GHC uses `libffi` for its runtime system (in the `rts/libHSrts_thr-ghc8.4.4.so` threading library). `libffi` [hasn’t seen a release since 2014](https://github.com/libffi/libffi/issues/296) so [the GHC people got anxious](https://ghc.haskell.org/trac/ghc/ticket/14056) and started [vendoring the newest master with their GHC releases](https://github.com/ghc/libffi-tarballs/blob/master/mk-snapshot.sh).

Now, the master version of libffi had a breaking ABI change, thus a [version bump](https://gcc.gnu.org/ml/gcc-bugs/2016-03/msg00035.html) from 6 to 7. According to the patch message this is especially relevant for Aarch64.
According to Ben Gamari, GHC itself doesn’t depend on any features that are not in `libffi.so.6`, yet they need `libffi.so.7` because “the last release is quite broken on several architectures that we support”.

Our downstream uses the `pango`, `gtk3` and even `glib` haskell libraries, which all link to their C-library counterparts, which in turn have a `DT_NEEDED` dependency on `libffi.so.6`, meaning any dynamic Haskell executable depending on one of these system libraries also inherits the dependency on `libffi.so.6` (it is added to `DT_NEEDED` by the build time linker).
If the Haskell executable is compiled with `-threaded` it additionally depends on `libHSrts_thr-ghc8.4.4.so`, which has a `DT_NEEDED` pointing to `libffi.so.7`.

In our downstream configuration the `ld` used at link time noticed the discrepancy and threw a warning

```
/nix/store/553rihc190vsyy8b22iqcq25a6489h8y-binutils-2.30/bin/ld: warning: libffi.so.7, needed by /nix/store/nzcmk7p670j1m1yjqxh20wyp51n4hhl2-ghc-8.4.4/lib/ghc-8.4.4/rts/libHSrts_thr-ghc8.4.4.so, may conflict with libffi.so.6
```

which @guibou [managed to reproduce in the `link_warning_ffi_repro` branch](https://github.com/tweag/rules_haskell/commit/6eb03b47a6f91855f0df0ee4cfacf7ba9a7dac0d). `ld` throws the warning only when using the provided `CROSSTOOL` though, we are not sure what the reason for that is. (It is not building for `arm`, that’s just a misnomer from copying from downstream.) 

The resulting executable lists *both* versions of the `.so` at runtime:
```
[nix-shell:~/kot/bazel/rules_haskell]$ ldd bazel-bin/tests/library-deps-libffi/pangomain
    linux-vdso.so.1 (0x00007ffde29f7000)
    …
    libffi.so.6 => /nix/store/qq9g14g39v7k1982z4512v3f13bjhg9g-libffi-3.2.1/lib/libffi.so.6 (0x00007faf63c93000)
    …
    libffi.so.7 => /nix/store/nzcmk7p670j1m1yjqxh20wyp51n4hhl2-ghc-8.4.4/lib/ghc-8.4.4/rts/libffi.so.7 (0x00007faf602ed000)
```
My hunch is that this could lead to the wrong symbols being resolved, which *might* lead to runtime crashes or weird behavior, though I don’t know enough about the inner workings of `ld.so` to be sure about that.

For `rules_haskell` this poses multiple practical questions:
* Why does the build-time linker only complain with the `CROSSTOOL` setup in the repro, not in general? The linked executable always references both versions of `libffi`.
* Does this pose potential runtime problems for the binaries we produce?
* Should we add a manual test that warns if our generated executables contain more than one version of `libffi`?

For downstream we have the possibility to link the required system libraries against `libffi.so.7` manually.

**Comment by mboes** [comment]
I'm not sure what the "problem" really is here. Is it the fact that there are linker warnings? Are the warnings unexpected, and if so, is it something rules_haskell can do something about? Fundamentally, the problem here is that you're attempting to link against two versions of the same library. Without versioned symbols, that's asking for trouble. The only solution is to just not do that (but that's not something rules_haskell can help with).

> Does this pose potential runtime problems for the binaries we produce?

Yes.

> Should we add a manual test that warns if our generated executables contain more than one version of libffi?

I don't think that's our job. Nor is it an easy test to implement reliably.

**Comment by Profpatsch** [comment]
@guibou You have found a solution for this, right? Is this something we can apply to `rules_haskell` or only in downstream repos? If so, we should add a FAQ entry on how to do that.

**Comment by guibou** [comment]
Yes, the solution in to build `ghc` with `--with-system-libffi`. I think we can close this issue because:

- It only appears in a specific setup, mainly:
   - `linkStatic = False` on `haskell_binary`, which is not the default
   - the haskell program must link to a library which itself links to `libffi`, this is not common
   - ghc is not built with `--with-system-libffi`. This is pretty common
- It does not pose any known issue
