### ISSUE TITLE
haskell_doc should fail on warning

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#484]
`haskell_doc` sometimes outputs warnings:

```
INFO: From HaskellHaddock //foo/bar:baz:
Warning: Foor.Bar.Baz: could not find link destinations for:
    FooSymbol
```

It can be interesting to make `haskell_doc` fail if output contains warning. https://github.com/haskell/haddock/issues/927 show that users are interested by this feature, but that's not yet implemented yet in haddock.

Perhaps we can add a custom attribute to `haskell_doc`, such as `fail_on_warning` which default to `False` and, when turned "on", will fail if `Warning: ` appears in the output?

cc @ghorn

**Comment by ghorn** [comment]
@peddie has some pull requests in review on haddock itself to add a flag making these warnings into errors. Then rules_haskell would pass the flag rather than parse the output. This would only work on newer haddocks, but might be less fragile.

**Comment by mboes** [comment]
@guibou the guidelines for rules (I think I heard from @judah) is that they should never produce any output. Warnings should be errors. If they're not then they shouldn't be printed.

**Comment by guibou** [comment]
Closed in favor of https://github.com/haskell/haddock/issues/927

The new `haddock_flags` attribute of `haskell_toolchain` allows the usage of `-Werror`.

However keep in mind that the haddock changes won't appear in haddock until ghc 8.10, users are encouraged to build a custom haddock, but that's not straightforward.
