### ISSUE TITLE
How to use rules_haskell in a partial workspace

### ISSUE THREAD

**Issue by robinp** [tweag/rules_haskell#486]
I made up the term. I would want to add `rules_haskell` build rules to an open source repo, but I would like to leave the choice about how `haskell_import`s are sourced to actual users. For example, some might source them from Nix, some from Hazel.

Is there a beaten path for this pattern? Maybe something with Bazel external dependencies? I don't immediately see a Bazel option to define placeholder targets that are bound later.

If you think this is not `rules_haskell`-specific enough, feel free to close and I'll open a Bazel issue.

**Comment by Profpatsch** [comment]
> Is there a beaten path for this pattern?

Not as far as I know. You could write a bazel macro (fancy word for a toplevel `WORKSPACE` subroutine that calls [repository_rules](https://docs.bazel.build/versions/master/skylark/repository_rules.html)) that switches on some information [accessible from `repository_ctx`](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html), e.g. on an environment variable (hidden in the `os` field).

Maybe one can also work with conditional importing inside of `WORKSPACE`, though afaik [`select`](https://docs.bazel.build/versions/master/be/functions.html#select) only works for `BUILD` rules.

**Comment by robinp** [comment]
Not really a burden. I wonder if there would be any issues though if I choose to source `bytestring` from `Nix`, while a user sources from `hazel`. I imagine there could be scenarios where they could end up with different versions as dependency in the same library?

Bazel's [`bind`](https://docs.bazel.build/versions/master/be/workspace.html#bind) rule sounds like something similar - my repo could depend on `//external/myrepo-base`, and the user could bind it to whatever target they wish. It's deprecated though and maybe has caveats.

**Comment by mboes** [comment]
Workspaces can't be composed at the moment. There's only a top-level workspace, that defines external repos at top-level. They're an all-or-nothing thing. So the user of your code would define a workspace however she likes, selecting e.g. Nixpkgs for dependencies or Hazel for dependencies. Thing is, right now Nixpkgs and Hazel don't have the same naming conventions, so users can't just substitute one for the other in their workspace file and expect all code to work unchanged.

I'm not sure what a partial workspace really means.

**Comment by robinp** [comment]
Sorry for being implicit. So the problem in a nutshell is: let's say I have a small library living on hackage. Now I want to add Bazel support for it, so I add WORKSPACE and BUILD files. But my library depends on other libs from GHC and/or hackage (let's say `bytestring` and `lens`), and the user likely also has imports for these libraries. Can I ensure that my rules use the imports of the user, to avoid clashing?

Well, one way could be to provide a BUILD template + some script to replace my hackage dep templates with the user's (or just let the user do it). I thought there would be something more composable.

**Comment by mboes** [comment]
>  I thought there would be something more **composable**.

That's the crucial word. And as @Profpatsch would say, workspaces are not composable right now. People write macros to automate the copy/pasting from one workspace to another, but it doesn't work well. This conversation might interest @aehlig, since he has a proposal for recursive workspaces.

**Comment by robinp** [comment]
Thank you, pinged the recursive workspaces discussion at https://groups.google.com/forum/#!topic/bazel-dev/YGV4_pMIMmA.

**Comment by aehlig** [comment]
I don't see how this is related to recursive workspaces. Generally, the idea of bazel is that there is a global name space and if one project depends on another, it refers to it by its global name, and it is the responsibility of the top-level user to provide this global name in the workspace.

Now there are two issues with that.
- Naming conventions differ; as far as I understand, this is what is asked for in this issue. Bazel's approach to this is to support renaming in an external repository. For background see https://github.com/bazelbuild/bazel/issues/3115 and the [diamond splitting design](https://docs.google.com/document/d/1254CQ8T4Rmeasg4NO1NPail2kLPC50VJ7Ok6JsoSe-c/edit#heading=h.dcdug56g93w1)
- The problem of defining indirect dependencies (I depend on `@a` which depends on `@b` which I don't use). _That_ is the problem attempted to be solved by recursive workspaces.

**Comment by mboes** [comment]
OK closing for now since this is apparently a discussion to be had upstream.
