### ISSUE TITLE
Failure with bazel-0.20

### ISSUE THREAD

**Issue by laurentlb** [tweag/rules_haskell#492]
cc @hlopko

rules_haskell works fine with bazel 0.19.2, but it fails with 0.20.0rc4

```
$ bazel-0.20.0rc4-linux-x86_64 test tests:all                                                                                                           Starting local Bazel server and connecting to it...
INFO: Invocation ID: 3726d9fa-9c0c-4b5a-b3ee-c580ce4e9544
/nix/store/rxl8zia74r3sz9ndy624shhp2kfzxh0a-all-haskell-packages.bzl
/nix/store/jzl6qh6wrvzwfrgw6i6jra17j1bdw9k4-bazel-cc-toolchain
/nix/store/whh4d9yplnpm7pykmhb7v1fn3y63v9rp-glibc-locales-2.27
/nix/store/wg5py8hw4pfff2hq0xva4bm3vwwhy4yx-ghc-bazel
/nix/store/s3raajpqzjb03n50yqwa8g493wmsb3wi-doctest-bazel
/nix/store/6imipp19z62ybv3xpr5wqgrpampdsgzd-c2hs-bazel
/nix/store/bm5wbhza4kkxix7501n48y5fgfkj26ig-proto-lens-protoc-bazel
ERROR: /usr/local/google/home/laurentlb/git/laurentlb/rules_haskell/tests/BUILD:18:1: in _haskell_toolchain rule //tests:ghc-impl: 
Traceback (most recent call last):
	File "/usr/local/google/home/laurentlb/git/laurentlb/rules_haskell/tests/BUILD", line 18
		_haskell_toolchain(name = 'ghc-impl')
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/5401bd246bcbe91e5ca1737e0ab4fe19/external/io_tweag_rules_haskell/haskell/toolchain.bzl", line 154, in _haskell_toolchain_impl
		targets_r.update({"ar": ctx.host_fragments.cpp.ar...})
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/5401bd246bcbe91e5ca1737e0ab4fe19/external/io_tweag_rules_haskell/haskell/toolchain.bzl", line 155, in targets_r.update
		ctx.host_fragments.cpp.ar_executable
Information about the C++ toolchain API is not accessible anymore through ctx.fragments.cpp (see --incompatible_disable_legacy_cpp_toolchain_skylark_api on http://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disable-legacy-c-configuration-api for migration notes). Use CcToolchainInfo instead.
ERROR: Analysis of target '//tests:test-haddock' failed; build aborted: Analysis of target '//tests:ghc-impl' failed; build aborted
INFO: Elapsed time: 30.632s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (66 packages loaded, 3455 targets configured)
FAILED: Build did NOT complete successfully (66 packages loaded, 3455 targets configured)
    Fetching @ghc; fetching
```

**Comment by mboes** [comment]
I don't know how to fix this in a backwards compatible way. Any pointers?

Which rule should we depend on to get a `CcToolchainInfo`?

**Comment by laurentlb** [comment]
@hlopko @scentini

**Comment by cceckman** [comment]
http://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disable-legacy-c-configuration-api (linked in the error report) is the migration guide; it gives an example.

**Comment by cceckman** [comment]
A quick search of the relevant sections makes it look like [this](https://github.com/tweag/rules_haskell/blob/293ddb103b3022d198f30a881e73385667e7d8e7/haskell/cc.bzl#L88) is the relevant section.

I also note a TODO pointing at bazelbuild/bazel#4571, a closed issue; I don't have context, is this the same issue?

**Comment by mhlopko** [comment]
Howdy all,

This is the change I did for rules_rust in a backwards compatible way (for inspiration): https://github.com/bazelbuild/rules_rust/commit/e7e5d6f38d97e3371f32906c825016a5bdadeb7e

Then followup fixes for the bugs in the versions check:
https://github.com/bazelbuild/rules_rust/commit/981d21712864dc28d95ab68d684d415d56807059
https://github.com/bazelbuild/rules_rust/commit/22317551f43658cca832d0f9a356a8217dc66b74

Feel free to add me as a reviewer for the migration PR.

Now to answer open questions:

You get `CcToolchainInfo` by depending on `@bazel_tools/tools/cpp:current_cc_toolchain`. The best way to get the provider in a future-proof way is to load `@bazel_tools/tools/cpp:toolchain_utils.bzl` and call `find_cpp_toolchain(ctx)`.

bazelbuild/bazel#4571 is the same issue as the incompatible flag one. Each incompatible flag has to have a separate issue that documents the current flag state, and also a reference to the bigger enclosing issue documenting the task being done.

LMK if you have more questions (and sorry for replying a bit late, github decided to not notify me of this issue, @scentini had to ping me).

**Comment by mboes** [comment]
Thanks. Was hoping for a way to shift to the new API in a way that would retain compatibility with previous versions of Bazel, but I understand now that this not a goal we can strive for.

I've managed to port rules_haskell to Bazel v0.20 (see #505), but had to add a very ugly workaround for now due to #6876.

**Comment by mhlopko** [comment]
Hi Mathieu, ftr, you can keep backwards compatibility, that's what rules_rust do.
