### ISSUE TITLE
Add "size" attribute to haskell_test

### ISSUE THREAD

**Issue by jbgi** [tweag/rules_haskell#496]
Useful to exclude long running tests in some workflows.

**Comment by judah** [comment]
"size" (like "timeout", "tag" and others) should already be available for any test rule:
https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-tests

rules_haskell shouldn't need to anything explicit to get those attributes available on haskell_test.

**Comment by jbgi** [comment]
thanks!
