### ISSUE TITLE
Start script: don't use prebuilt_dependencies

### ISSUE THREAD

**Issue by aspiwack** [tweag/rules_haskell#504]
Since we consider it deprecated:

> DEBUG: <bazel_cache>/external/io_tweag_rules_haskell/haskell/private/haskell_impl.bzl:176:9: The attribute 'prebuilt_dependencies' has been deprecated,
use the 'haskell_import' rule instead.

**Comment by aspiwack** [comment]
(unrelated to previous message)

I was wondering how we could add a test for the start script in CI. I don't know how genrules work in Bazel (I assume the tests are all Bazel-driven), but I'm expecting something like

- Call the start script in some sandbox
- Create a `src/Test.hs` module with basically nothing in it
- Run Bazel, `tee`-ing its output
- If it Bazel fails, fail the test
- If `grep -v deprecated` fails on the recorded output, fail the test (or maybe we want to catch all `DEBUG` messages?)

**Comment by mboes** [comment]
> I was wondering how we could add a test for the start script in CI. 

We already have one. And it's actually creating a problem. The `start` script uses the latest rules_haskell release. But when we update Bazel to a version that is not backwards compatible, CI breaks until we cut a new release.

**Comment by aspiwack** [comment]
Ah good point. In a way, the `start` script should point at the commit which is is taken from. Could this be achievable with git substitutions, maybe? (if there is an appropriate substitution, it would work fine for distributed versions. But not so clear for CI…)

**Comment by mboes** [comment]
I hadn't thought of that. It might well work!
