### ISSUE TITLE
Visible binaries and Windows Support

### ISSUE THREAD

**Issue by gdeest** [tweag/rules_haskell#512]
It turns out that Windows does not support creating symbolic links without administrator rights, and the `ln` command provided in `msys` actually just copies files instead of creating a link. This makes the whole `visible-binaries` hack fail on Windows. The reason is that GHC expects to find things at specific locations relative to the real path of the executable being invoked, which breaks when it is copied outside the GHC distribution.

The rationale for current design is the following: during the compilation process, some tools need to be made visible to each other. For example, `ghc` needs to call `cc` (for linking, presumably). Tool invocation is usually done via the exec* libc functions, which search in the colon-separated list of paths in the `PATH` environment variable. An obvious solution is thus to provide a valid `PATH`, pointing to at least one directory containing all the necessary tools. We could add the `dirname` of each required tool to that `PATH`, but it would break hermeticity, as it would expose _more_ than what is strictly necessary, including tools which could affect the build and compromise reproducibility. The approach chosen in `rules_haskell` is thus to create a directory ourself, populate it with symlinks, and only add that to the `PATH` when invoking an executable.

However, to make this work on Windows, we need to rethink that design. I think we have two main options:

- The first one is to replace symbolic links with wrapper scripts that invoke the correct executable in its original location.
- The second one is to pass explicitly the location of each executable. The feasibility of that approach actually depends on how many dependencies between tools we have, and on whether or not the caller can be instructed to invoke a tool at a specific path, rather than searching in `PATH`. Do we know how to do this with ghc / gcc, for example ?

There may be other options. I am opening this issue to discuss this problem and collect ideas on what a correct solution should look like.

**Comment by mboes** [comment]
@gdeest PTAL
