### ISSUE TITLE
Why not always generate Cabal macros?

### ISSUE THREAD

**Issue by thumphries** [tweag/rules_haskell#520]
Currently Cabal-style CPP macros are not generated unless `version` is set in `haskell_library`.

I am wondering if it would be reasonable to always generate them. We usually only care about the versions of other libraries, rather than one's own version.

**Comment by Profpatsch** [comment]
See https://github.com/tweag/rules_haskell/commit/b58050c284a676d64c4ea082ec44899aee837906, which fixed #414 

cc @guibou

**Comment by thumphries** [comment]
Thanks for the context. I'll do a bit of reading and get back to you if I have anything constructive :sweat_smile: 

I am using Hazel with a large collection of custom hand-written BUILD files for upstream dependencies. They all need to have their `version` set in order to case on things like `base` and `bytestring`, but they basically never need to export their own macros downstream. So, the `version` flag becomes more or less a boolean that says "this is a Hackage package that uses CPP".

It feels like `version` should control whether or not we export macros, rather than whether or not we are able to consume them. I don't know if GHC gives us that level of control, though.

**Comment by guibou** [comment]
> It feels like version should control whether or not we export macros, rather than whether or not we are able to consume them. I don't know if GHC gives us that level of control, though.

`GHC` does not gives us that power, however we can tell GHC to disable macro AND export macros by ourself, that's totally doable, but more work. Actually, what you propose was discussed when we faced this issue with macro conflict and we decided for a simpler solution.

**Comment by Profpatsch** [comment]
Is there anything actionable in this PR? I believe there were some further internal discussions on the use of cabal macros.

**Comment by guibou** [comment]
I'm closing. Feel free to reopen if the current design in a blocker for your workflow.
