### ISSUE TITLE
The buildifier command in README does not fix formatting errors

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#528]
The README contains a command to fix formatting errors in Bazel files:

```
bazel run --direct_run //skylark:buildifier **/*.bzl **/BUILD
```

Running that command does not seem to have any effect.

Instead, one has to explicitly pass a full path to the file in which to fix formatting errors. I.e. the following works

```
bazel run --direct_run //skylark:buildifier haskell/private/actions/link.bzl
```

**Comment by guibou** [comment]
Is this because your shell does not support "extended wildcard" `**`? Could you try `ls **/*.bzl`? A safer solution may be to use `bazel run --direct_run //skylark:buildifier $(find -name '*.bzl') $(find -name 'BUILD')`.

**Comment by aherrmann** [comment]
> Is this because your shell does not support "extended wildcard" `**`?

Yes, that's the reason. Sorry, my bad. I assumed that would be some buildifier syntax and overlooked that the shell would expand the `*`s before buildifier could see them.

Still for the README it's probably better not to assume extended wildcard support. Bash is still very common.
