### ISSUE TITLE
How to reload dependencies from a `repl` target?

### ISSUE THREAD

**Issue by peddie** [tweag/rules_haskell#530]
I have a package `//library` which depends on `//dependency`.  I like to hack on `//library` by calling `bazel run //library:library-repl` and using the interactive prompt.  Any time I change code in `//library`, I can load my updates into GHCI with `:r`.  I don't know how to do the equivalent for changes to `//dependency` -- it seems like I have to exit GHCI and run the REPL target again.  Is there a better way?

This also applies to `ghcid`: when I use the command listed in https://github.com/tweag/rules_haskell/issues/330#issuecomment-403895067, it works great for `//library`, but it doesn't pick up any changes to `//dependency`.

**Comment by guibou** [comment]
Random note: as far as I know, `cabal [new-]repl` have the same behavior: you need to restart the shell to reload dependencies. `stack` does not.

**Comment by aherrmann** [comment]
This is supported through [`haskell_repl`](https://api.haskell.build/haskell/defs.html#haskell_repl). It allows to define patterns to determine which dependencies to load as binary packages and which to load by source. Those loaded by source will be reloaded on `:r`.
