### ISSUE TITLE
Header dependencies are not forwarded between Haskell libraries

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#531]
Consider the following situation:
- `cc_library` `cbits` contains a header file `a.h`.
- `haskell_library` `intermediate` depends on `cbits` and refers to `a.h` via `CPP` `#include "a.h"`.
- `haskell_library` `final` depends on `intermediate` and refers to `a.h` via `CPP` `#include "a.h"`.

Currently, `intermediate` will succeed to compile. But, `final` will fail to compile, because the header file `a.h` cannot be found.

This behaviour of `haskell_library` is in contrast to that of `cc_library`, where headers are forwarded, and also to Cabal, where headers are forwarded as well.

- https://github.com/tweag/rules_haskell/commit/01156cd7093cad3ab0b7f7b8a37316be02490c2a demonstrates the issue (`bazel build //tests/library-with-stripped-includes`)

This issue manifests itself in Hazel. For example, when a Cabal library target contains a header file in `extra-source-files` and configures `include-dirs`, and when an executable target in the same package depends on the library target and tries to include the header file. Hazel generates `cc_library` targets for headers and other cbits. The `haskell_library` will depend on the `cc_library` that captures the headers, but the `haskell_binary` target will only depend on the `haskell_library` which currently doesn't forward the headers.

Could `rules_haskell` be extended to forward headers and [includes](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.includes)? This would resolve the issue on the Hazel side, and also align `haskell_library`'s behaviour with that of `cc_library` and Cabal.

**Comment by guibou** [comment]
I wonder if your example is correct.

> * `cc_library` `cbits` contains a header file `a.h`.
> * `haskell_library` `intermediate` depends on `cbits` and refers to `a.h` via `CPP` `#include "a.h"`.
> * `haskell_library` `final` depends on `intermediate` and refers to `a.h` via `CPP` `#include "a.h"`.

If `final` directly refer to `a.h`, it *MUST* depends on `:cbits`, that's not an indirect dependency, that's a direct dependency and it should be listed as such. Adding `:cbits` as dependencies of final fix the build.

A scenario with indirect dependencies may be:

* `cc_library` `cbits-indirect` contains a header file `a.h`.
* `cc_library` `cbits-direct` contains a header file `b.h` which includes `a.h`.
* `haskell_library` `intermediate` depends on `cbits-direct` and refers to `b.h` via `CPP` `#include "b.h"`, which itself depends to `a.h`.

> This issue manifests itself in Hazel. For example, when a Cabal library target contains a header file in extra-source-files and configures include-dirs, and when an executable target in the same package depends on the library target and tries to include the header file. Hazel generates cc_library targets for headers and other cbits. The haskell_library will depend on the cc_library that captures the headers, but the haskell_binary target will only depend on the haskell_library which currently doesn't forward the headers.

From my point of view, if the `haskell_binary` includes explicitly files from the `cc_library`, then the `cc_library` should be a direct dependency.

**Comment by aherrmann** [comment]
> I wonder if your example is correct.

@guibou I think you're right and my example was bad. I've changed the example in the following commit as you suggested: https://github.com/tweag/rules_haskell/commit/574b52b6269e109c38ffc4f57c62bdb96fb285ba

In that way it actually builds correctly and also the `includes` attributes seem to be handled correctly.

I think for Hazel this means that the issue can be solved there by also taking package dependencies into account for `cbits` targets. E.g. if `package-b` depends on `package-a`, then `package-b-cbits` should also depend on `package-a-cbits`. Anyway, that's out of scope for rules_haskell. I'll close here and look into this on the Hazel side and move the discussion there.

Thanks!
