### ISSUE TITLE
version api.haskell.build

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#543]
https://docs.bazel.build started versioning their docs, like

```
https://docs.bazel.build/versions/master/best-practices.html#bazelrc
https://docs.bazel.build/versions/0.19.1/best-practices.html#bazelrc
https://docs.bazel.build/versions/0.21.0/best-practices.html#bazelrc
```

This ensures it is possible to create stable references to the documentation.

If we don’t want to invest the work to do the same, we should at least prominently display the exact version of the API we document on the website.

**Comment by mboes** [comment]
api.haskell.build is just the unadulterated output of Skydoc. Could you refile upstream as a feature request?

**Comment by mboes** [comment]
We have a workaround now in the form of multiple subdomains, one for each version.
