### ISSUE TITLE
template-hsc.h:4:10: fatal error: 'stddef.h' file not found

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#545]
Repro: https://travis-ci.com/iphydf/repro545/jobs/168369465#L609 from https://github.com/iphydf/repro545.

**Comment by iphydf** [comment]
Repro case is done: https://github.com/iphydf/repro545, CI build: https://travis-ci.com/iphydf/repro545/jobs/168369465#L609

**Comment by iphydf** [comment]
Relevant BUILD file: https://github.com/iphydf/repro545/blob/master/third_party/haskell/BUILD.clock

**Comment by iphydf** [comment]
https://github.com/iphydf/repro545/blob/master/.travis.yml#L18 `bazel build @haskell_clock//:clock`

**Comment by brandon-leapyear** [comment]
I'm getting 
```
ERROR: /private/var/tmp/_bazel_brandonchinn/0a8e6892997a7541bfd4e2d7913db675/external/haskell_clock_94755854/BUILD:17:1: HaskellHsc2hs external/haskell_clock_94755854/_hsc/clock/System/Clock.hs failed (Exit 1) hsc2hs failed: error executing command external/io_tweag_rules_haskell_ghc_darwin_amd64/bin/hsc2hs bazel-out/darwin-fastbuild/bin/external/haskell_clock_94755854/gen-srcs-clock/System/Clock.hsc -o ... (remaining 52 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
clang: warning: no such sysroot directory: '__BAZEL_XCODE_SDKROOT__' [-Wmissing-sysroot]
Clock.hsc:34:10: fatal error: 'hs_clock_darwin.c' file not found
#include "hs_clock_darwin.c"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```
when building a package that depends on `clock`. Is this the same problem as described in this issue?

**Comment by Profpatsch** [comment]
Is this still a problem?

**Comment by brandon-leapyear** [comment]
i dont know, i stopped using bazel

**Comment by mboes** [comment]
The recommended way to build `clock` now is via `stack_snapshot`.
