### ISSUE TITLE
Don't call ./configure on Windows GHC bindists

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#562]
Unlike Darwin and Linux bindists, Windows GHC bindists do not have a `./configure` script. `ghc_bindist()` should therefore be adapted to omit the call to `./configure` on this platform. The bindist is in a sense already the result of a `make install`.

This ticket depends on #560.

**Comment by nmattia** [comment]
Fixed in #564

**Comment by mboes** [comment]
Likely not, since we're not copying to the right location. But I didn't want to hold up #564, and we'll get to this next.
