### ISSUE TITLE
Continuous integration for rules_haskell on Windows

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#563]
We currently have CI setup on both Linux and macOS. But we should extend this set to include Windows as well. Unfortunately, CircleCI doesn't offer a Windows option, but [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) does. The "Microsoft-managed" option has slower Linux builders than CircleCI, but we could consider moving the Darwin job to it and have Pipelines manage Windows + Darwin jobs.

We should not aim to have extensive testing like we do on Linux and Darwin at first. We should start with testing say just the `binary-simple` test and go from there.

Blocker: #562.

**Comment by nmattia** [comment]
We've settled on the following:
1. Create an [Azure Pipelines] job for Windows
1. Once that is up and running, assess whether or not we want to port Darwin and Linux as well
