### ISSUE TITLE
Haddock cannot find some symbols the files generated by proto-lens

### ISSUE THREAD

**Issue by NinjaTrappeur** [tweag/rules_haskell#575]
For instance, after a clean --expunge:

```
bazel build //...
[...]
INFO: From HaskellHaddock //tests/haskell_proto_library:address_haskell_proto:
Warning: Proto.Tests.HaskellProtoLibrary.Address: could not find link destinations for:
    Eq == Bool /= Ord compare Ordering < <= > >= max min Show showsPrec Int ShowS show String showList NFData rnf Message messageName Proxy Text defMessage fieldsByTag Map Tag FieldDescriptor fieldsByTextFormatName unknownFields Lens' FieldSet HasLens' Symbol lensOf' Functor Proxy# ZipCode Maybe
Warning: Proto.Tests.HaskellProtoLibrary.Address_Fields: could not find link destinations for:
    Functor HasLens' LensLike'
INFO: From HaskellHaddock //tests/haskell_proto_library:person_haskell_proto:
Warning: Proto.Tests.HaskellProtoLibrary.Person: could not find link destinations for:
    Eq == Bool /= Ord compare Ordering < <= > >= max min Show showsPrec Int ShowS show String showList NFData rnf Message messageName Proxy Text defMessage fieldsByTag Map Tag FieldDescriptor fieldsByTextFormatName unknownFields Lens' FieldSet HasLens' Address Symbol lensOf' Functor Proxy# Int32 Timestamp Maybe
Warning: Proto.Tests.HaskellProtoLibrary.Person_Fields: could not find link destinations for:
    Functor HasLens' LensLike'
```

Are these interface files correctly forwarded in the deps graph?

**Comment by NinjaTrappeur** [comment]
It appears that `haskell_proto_library()` does not depend on `base`, `deepseq`, `lens` or any library the generated Haskell file actually depends on.

In our tests, these dependencies are added to the `haskell_library` call making use of the various `haskell_proto_library()` generated files. This is why we are able to build these generated files.

I think we should add these deps to every target generated by `haskell_proto_library()` and transitively forward them to the `haskell_library` call. 

We also should add, on top of the already existing dependencies, the libraries used in the files generated by the `proto-lens-protoc` plugin; ie.

- deepseq
- lens-labels
- protolens
- text
- bytestring
- lens-family

**Comment by Profpatsch** [comment]
Can't reproduce on a recent master.
