### ISSUE TITLE
Build a Haskell library on Windows

### ISSUE THREAD

**Issue by nmattia** [tweag/rules_haskell#586]
Building a library with no dependencies should succeed on Windows.

**Comment by gdeest** [comment]
We are already there, and even a bit further, in the `gd-bin-with-lib` branch: it successfully builds a simple (static) library _and_ a simple binary depending on this library.

However, it uses the CC toolchain's `ar` executable (which currently does not exist on CI, I believe, as we only install Bazel). In line with #561 , we should use GCC's `ar` on Windows. Assuming we are using a standard GHC binary distribution, it leaves at `../mingw/bin/ar.exe` relative to `ghc.exe`.
