### ISSUE TITLE
Use @rpath for for mach-o binaries instead of patching in @loader_path

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#592]
At the moment Darwin mach-o binaries are patched after the fact by `_fix_darwin_linker_paths`:

https://github.com/tweag/rules_haskell/blob/3e5e413eb4d2d166a585b857541c8d34182e22c4/haskell/private/actions/link.bzl#L23-L70

Digging a few inches deeper, `man dyld` tells me that they have a synonym to `RPATH` called `@rpath`, which can also be specified at *link time*, making patching unnecessary.

Additionally, the linker path patching is the only place where we currently (still) use unmangled library paths in `rules_haskell`, leading to yet another difference from the Linux behaviour and additional code complication. It might be possible to remove that with `@rpath`.

from `man dlyd`:

>  @loader_path/
> This variable is replaced with the path to the directory containing the mach-o binary which contains the load command using @loader_path. Thus, in every binary, @loader_path resolves to a different path, whereas @executable_path always resolves to the same path. @loader_path is useful as the load path for a framework/dylib embedded in a plug-in, if the final file system location of the plugin-in unknown (so absolute paths cannot be used) or if the plug-in is used by multiple applications (so @executable_path cannot be used). If the plug-in mach-o file is at /some/path/Myfilter.plugin/Contents/MacOS/Myfilter and a framework dylib file is at /some/path/Myfilter.plugin/Contents/Frameworks/Foo.framework/Versions/A/Foo, then the framework load path could be encoded as @loader_path/../Frameworks/Foo.framework/Versions/A/Foo and the Myfilter.plugin directory could be moved around in the file system and dyld will still be able to load the embedded framework.

> @rpath/
> Dyld maintains a current stack of paths called the run path list.  When `@rpath` is encountered it is substituted with each path in the run path list until a loadable dylib if found.  The run path stack is built from the LC_RPATH load commands in the depencency chain that lead to the current dylib load.  You can add an LC_RPATH load command to an image with the -rpath option to ld(1).  You can even add a LC_RPATH load command path that starts with @loader_path/, and it will push a path on the run path stack that relative to the image containing the LC_RPATH.  The use of `@rpath` is most useful when you have a complex directory structure of programs and dylibs which can be installed anywhere, but keep their relative positions.  This scenario could be implemented using @loader_path, but every client of a dylib could need a different load path because its relative position in the file system is different. The use of `@rpath` introduces a level of indirection that simplies things.  You pick a location in your directory structure as an anchor point.  Each dylib then gets an install path that starts with `@rpath` and is the path to the dylib relative to the anchor point. Each main executable is linked with -rpath @loader_path/zzz, where zzz is the path from the executable to the anchor point.  At runtime dyld sets it run path to be the anchor point, then each dylib is found relative to the anchor point.

**Comment by judah** [comment]
It's honestly been a while since I looked at this.  That approach does sound promising; my main concern is that you don't bloat the total number of linker directives and get closer to the macOS liker limit.  In the current code we use `install_name_tool -change` to remove the old paths; you'll either need to do something similar, or else pass flags to `ld` to prevent them (not sure how possible that is).

**Comment by mboes** [comment]
@aherrmann is already running into linker limits as it is. So let's make sure not to make that worse.

**Comment by aherrmann** [comment]
This is resolved. The load commands are now patched in `haskell/private/osx_cc_wrapper.sh.tpl` relative to `@rpath`.
