### ISSUE TITLE
Build a program using a Template Haskell library on Windows

### ISSUE THREAD

**Issue by gdeest** [tweag/rules_haskell#600]
This could be problematic, as GHC seemingly does not support dynamic linking on Windows.

**Comment by gdeest** [comment]
We can't get this to work with GHC 8.6.3, presumably because of: https://ghc.haskell.org/trac/ghc/ticket/16057 

I have reverted to GHC 8.6.2 in the `gd-bin-with-th` branch, and it passes CI. Unfortunately, it is highly detrimental to nixpkgs cache hit rate and Linux and Darwin CI take forever.

We may want to specify different GHC versions for Linux/Darwin and Windows until GHC 8.6.4 is out.

cc @mboes @nmattia

**Comment by nmattia** [comment]
Fixed in #642
