### ISSUE TITLE
Impossible to know which file is currently being built

### ISSUE THREAD

**Issue by YPares** [tweag/rules_haskell#603]
Related to https://github.com/tweag/rules_haskell/issues/601, is seems that even with -v1 used to make GHC output verbose, it isn't possible to know which file is currently being built (because the output will be printed only when the whole package is done building).

This is really problematic when GHC hangs on a file (UndecidableInstances or any other reason making the compiler loop indefinitely, notably due to a bug in GHC), and makes it hard to know the culprit when we suspect that there is a bug in GHC.

**Comment by NinjaTrappeur** [comment]
I have been digging into this, I am not sure we can implement this with Bazel currently. 

There is no way to directly control how the stdout/stderr stream is collected. The only loosely-related option I found was [`--test_output=streamed`](https://docs.bazel.build/versions/master/command-line-reference.html); but I really don't see how we could take advantage of this in our context.

However, we could add an optional user-specified timeout to the building rule. This timeout would let us kill the process and collect the output when GHC does not terminate.

We are already wrapping GHC in a small shell script for the windows support, adding a `timeout` call on top shouldn't be really hard. However, I'm not sure this is a really good idea.

cc @mboes @regnat

**Comment by mboes** [comment]
I'm likewise skeptical that this is a good idea. Now that you understand the problem space adequately, I'd say: file a ticket upstream.

**Comment by mboes** [comment]
See upstream ticket.
