### ISSUE TITLE
Use bindists in start script rather than nixpkgs

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#604]
We provide a `start` script (at the root of the repo) for getting started quickly (see README). It uses Nixpkgs. Nixpkgs is not the right default. Nix users know how to deal with Nixpkgs. Non-Nix do not. Let's use bindists instead now that these are well supported.

**Comment by Profpatsch** [comment]
Implementing this will fix the problem in https://github.com/tweag/rules_haskell/issues/776
