### ISSUE TITLE
Test GHC bindist on Linux on CI

### ISSUE THREAD

**Issue by nmattia** [tweag/rules_haskell#611]
The test suite should be run with the bindist-provided GHC as well

**Comment by NinjaTrappeur** [comment]
Depends on #629

**Comment by NinjaTrappeur** [comment]
I am locally [1] able to run the tests the azure CI is able to run. I'll send a PR as soon the previously linked issue is fixed. We'll need to pin a new rules_nixpkgs commit.

[1] In a vanilla debian Docker image.

**Comment by NinjaTrappeur** [comment]
Closed by #637
