### ISSUE TITLE
Test GHC bindist on Darwin on CI

### ISSUE THREAD

**Issue by nmattia** [tweag/rules_haskell#612]
The test suite should be run with the bindist-provided GHC as well

**Comment by NinjaTrappeur** [comment]
Looking at the current circle ci darwin queue (~4 queued jobs as I post this), we should probably postpone this issue.

**Comment by mboes** [comment]
Closing for now. We can reopen if/whene there's interest later.

**Comment by nmattia** [comment]
we now have 5x concurrency on Darwin :tada:

**Comment by mboes** [comment]
Closing in favour of #1021.
