### ISSUE TITLE
Automatic spec discovery using hspec-discover

### ISSUE THREAD

**Issue by shmish111** [tweag/rules_haskell#625]
See http://hspec.github.io/hspec-discover.html for info about how it works.

Bazel simply reported:

```
  (cd /private/var/tmp/_bazel_davidsmith/62cce73873b917876ee3672f9bcefd51/execroot/plutus && \
  exec env - \
    LANG=en_US.UTF-8 \
    LD_LIBRARY_PATH='' \
    TMPDIR=/var/folders/gt/tp3vtxxs77b960txrxxndfqm0000gn/T/ \
  /var/tmp/_bazel_davidsmith/install/607b7e27bf27894119773f0cb5fdf882/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' /nix/store/jd0fg8ywjz6hfh7jk0vdx422g83nbbcz-bash/bin/bash -c '
        export PATH=${PATH:-} # otherwise GCC fails on Windows
        readarray -t ghc_args < bazel-out/darwin-fastbuild/bin/plutus-playground/plutus-playground-server/ghc_args_plutus-playground-server-test_HaskellBuildBinary
        readarray -t extra_args < bazel-out/darwin-fastbuild/bin/plutus-playground/plutus-playground-server/extra_args_plutus-playground-server-test_HaskellBuildBinary

        "${ghc_args[@]}" "${extra_args[@]}"
')
ghc: could not execute: hspec-discover
```

Presumably it needs the `haskell_test` rule to allow binary tools.

**Comment by ghorn** [comment]
Not sure if this helps but we got `tasty-discover` working with a bazel macro and a genrule.
```
def _tasty_discover_tests(name, srcs):
    # call tasty-discover binary to make a driver
    driver = "TastyDriver_" + name + ".hs"
    native.genrule(
        name = "tasty_driver_" + name,
        srcs = srcs,
        cmd = "tasty-discover . _ $(@)",
        outs = [driver],
    )

    # test suite
    haskell_test(
        name = "tasty_" + name,
        srcs = [
            driver,
        ],
        data = srcs,  # for hedgehog source code annotation
        main_function = "Main.main",
        args = ["--color", "always"],
        tags = ["tasty"],
        deps = [
            name,
            "//ghc_pkgs:base",
            "//ghc_pkgs:tasty",
            "//ghc_pkgs:tasty-hedgehog",
            "//ghc_pkgs:tasty-hunit",
            "//ghc_pkgs:tasty-quickcheck",
        ],
        timeout = "short",
    )
```
Beware: we had to use a hacked version of `tasty-discover` which parses modules from the source rather than assuming they match the path.

**Comment by regnat** [comment]
If you're using an old-enough `rules_hakell`, you can have it working by adding it to the `extra_binaries` of the toolchain (but afaik the field has been recently removed because it was complicating things).
But if an adaptation of @ghorn macro (or anything else) works for you I'm interested because we're gonna need this when updating our rules_haskell version ;)
(and that probably would deserve going to the "use cases" section of the manual)

**Comment by regnat** [comment]
An alternative which is probably worth considering is to replace `hspec-discover` by a bazel macro creating one test for each `Spec` file under the current directory. This doesn't work if the tests depend on each other but has the advantage of giving more incrementality and parallelism

**Comment by mboes** [comment]
> But if an adaptation of @ghorn macro (or anything else) works for you I'm interested because we're gonna need this when updating our rules_haskell version ;) **(and that probably would deserve going to the "use cases" section of the manual)**

Yes please do!

**Comment by facundominguez** [comment]
Something like this worked for me:
```python
# A rule that generates the test driver.
genrule(
  name = "hspec-driver",
  srcs = glob(["tests/**/*.hs"]),
  outs = ["Spec.hs"],
  cmd = "$(location @inline-java-toolchain//:bin/hspec-discover) tests/Spec.hs tests/Spec.hs $@ --module-name=Spec",
  tools = ["@inline-java-toolchain//:bin/hspec-discover"],
)

haskell_test(
  name = "spec",
  src_strip_prefix = "tests",
  srcs = glob(["tests/Language/**/*.hs", "tests/Main.hs"]) + ["hspec-driver"],
  deps = [
    "//jni",
    "//jvm",
    ":inline-java",
    ":base",
    ":hspec",
    ":text",
  ],
  size = "small",
)
```

**Comment by Profpatsch** [comment]
Can we close this issue?
