### ISSUE TITLE
`//:buildifier-fix` fetches the whole of https://github.com/bazelbuild/bazel.git

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#628]
I sadly don’t have a CLI output because bazel makes it vanish after the fetch is complete (and you can’t copy auto-updating terminal).

The whole repo takes >200s on our office connection and is basically impossible to wait on on a less potent one (>5 minutes on 1Mb/s). That’s bad.

It’s probably in a transitive dependency somewhere, the repository is called `@io_bazel`.

**Comment by mboes** [comment]
Not a rules_haskell issue. Refile upstream.
