### ISSUE TITLE
Cannot load WORKSPACE is nix is not on path on linux/darwin

### ISSUE THREAD

**Issue by NinjaTrappeur** [tweag/rules_haskell#629]
We are currently assuming that any linux or darwin platform will have nix in the $path. Since we started supporting GHC's bindist, It's not true anymore.

Checks like https://github.com/tweag/rules_haskell/blob/master/haskell/nixpkgs.bzl#L123 prevents us to use the binary distribution system on linux/darwin. We need to refactor these checks while keeping in mind that some linux/darwin users won't be able to run nix.

**Comment by mboes** [comment]
I believe this was already fixed in #571 by @nmattia.

**Comment by NinjaTrappeur** [comment]
The fix is not generic enough for this specific case. I've been pairing a bit with @nmattia on this yesterday. The fix is almost ready, I just have an unidentified strange behavior preventing me to send the PR.

This should be fixed soon.

**Comment by NinjaTrappeur** [comment]
@nmattia Found our problem: https://github.com/tweag/rules_haskell/blob/e46991e746d27384689fee447447310585297743/haskell/nixpkgs.bzl#L220 ...

We missed this yesterday.

We actually also need to patch rules_nixpkgs.
