### ISSUE TITLE
Release version 0.8

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#636]
- [x] release branch with all WIP Windows features removed /w summary of changes made
- [x] changelog
- [x] announcement

**Comment by Profpatsch** [comment]
Okay, I reverted all Windows-specific changes and pushed to the [`v0.8` branch](https://github.com/tweag/rules_haskell/tree/v0.8). cc @mboes

**Comment by Profpatsch** [comment]
Changelog needs to be merged into master first: https://github.com/tweag/rules_haskell/pull/640

**Comment by mboes** [comment]
@Profpatsch LGTM

**Comment by Profpatsch** [comment]
0.8 is released, the branch is green, the announcement is at https://twitter.com/tweagio/status/1090199208798416896
