### ISSUE TITLE
Cannot build/test rules_haskell without nix

### ISSUE THREAD

**Issue by NinjaTrappeur** [tweag/rules_haskell#641]
We currently can't build `rules_haskell` without the nixpkgs.

See https://circleci.com/gh/tweag/rules_haskell/3661

```
Analyzing: 214 targets (74 packages loaded, 116 targets configured)
ERROR: Analysis of target '//tests/haskell_proto_library:address_haskell_proto' failed; build aborted: no such package '@hackage//': The repository could not be resolved
```

**Comment by mboes** [comment]
See https://github.com/tweag/rules_haskell/pull/637#issuecomment-458429491.

**Comment by Profpatsch** [comment]
Is the goal of this issue to make every `rules_haskell` test work with the bindists? Because from what I understand that is not a goal in practice.

**Comment by Profpatsch** [comment]
Closing because it’s currently handled by filtering tests that are not supported on some platforms (e.g. Windows, Linux bindists, Darwin).
