### ISSUE TITLE
Remove usage of @hackage as much as possible in tests

### ISSUE THREAD

**Issue by nmattia** [tweag/rules_haskell#654]
The `@hackage` repository (used for fetching prebuilt haskell libraries) is only available on Nix platforms. We should use it in tests only as little as necessary so that we can enable more tests for non-Nix platforms.

**Comment by mboes** [comment]
I believe this is already the case since #615. What is left to be done?

**Comment by NinjaTrappeur** [comment]
I tagged the rules using hackage with `requires_hackage`.

After fixing this, we will be able to remove the corresponding flag in the circleci config: https://github.com/tweag/rules_haskell/blob/master/.circleci/config.yml#L18
