### ISSUE TITLE
Fix hsc tests on Windows

### ISSUE THREAD

**Issue by gdeest** [tweag/rules_haskell#683]
Those tests currently fail with the following error:

```
Execution platform: @bazel_tools//platforms:host_platform
ghc-pkg.exe: 0: Parse of field '
unexpected '\\'
expecting ".", white space, "from", ",", "\"" or end of input

Bar, Flags, Foo, Bar\Baz
' failed.

**Comment by aherrmann** [comment]
I believe this is fixed. E.g. `//tests/hsc` ran successfully on Windows [here](https://github.com/tweag/rules_haskell/runs/5153873641?check_suite_focus=true#step:6:320).
