### ISSUE TITLE
inline-java and sparkle toolchain issue after removal of visible-binaries

### ISSUE THREAD

**Issue by facundominguez** [tweag/rules_haskell#713]
We’ve lost our ability to build inline-java and sparkle with bazel, after the following commit
https://github.com/tweag/rules_haskell/commit/93e1f6fed11a5b0d172e59c23a6464d02b9daa00

This was the issue that was solved by introducing extra_binaries: https://github.com/tweag/rules_haskell/issues/282

If `extra_binaries` is not an admissible solution, should we pursue a per-rule-instance attribute to combine toolchains as suggested in https://github.com/tweag/rules_haskell/issues/301?

**Comment by mboes** [comment]
Really interesting question. I'm a bit stumped TBH. Perhaps ask on bazel-discuss@?

I'm assuming you're interested in th Haskell/Java special case. Since Java is a built-in rule set, and we already have special integration with C/C++, another primitive rule set, we could have `haskell_{library,binary}` depend on the Java toolchain in addition to the CC toolchain.

**Comment by facundominguez** [comment]
Asked here https://groups.google.com/forum/?nomobile=true#!topic/bazel-discuss/ni2QhE2C1PY

**Comment by mboes** [comment]
On further thought I think we need to solve this in a less general way. There are two use cases:

* `-F -pgmF <cmd>`, where `<cmd>` is some filter (e.g. `tasty-discover` and `hspec-discover`),
* `-fplugin=<module>`, where `<module>` is the entry point for some source plugin.

For the first case, we can add a `filter` attribute that would act much like `extra_binaries` before. But it wouldn't need to pass the filter via the `PATH`. It can pass a relative path instead. We get the benefit no recompilation if the source file changed but the output of the filter is still the same.

For the second case we can modify the source plugin to obtain the Java command via the runfiles library.

**Comment by facundominguez** [comment]
> For the second case we can modify the source plugin to obtain the Java command via the runfiles library.

I assume you refer to both source and core plugins. Still, I don't understand what the solution would be. Add a plugin option like `-fplugin-opt Language.Java.Inline.Plugin:javac=/path/to/javac`?

Then how do we make `/path/to/javac` visible to the rule? `extra_binaries` for a rule instances?

**Comment by mboes** [comment]
You don't need a plugin option: the plugin would know where `javac` is. It would know because the build rule that creates the plugin could say something like:

```python
# A rule that writes the location of javac to a text file.
genrule(
  name = "javac",
  srcs = [],
  outs = ["javac.location"],
  cmd = "echo $(JAVABASE)/bin/javac > $@",
  toolchains = ["@bazel_tools//tools/jdk:current_java_runtime"]
)

haskell_library(
  name = "plugin"
  srcs = ...
  extra_srcs = [":javac"],
)
```

**Comment by mboes** [comment]
See https://docs.bazel.build/versions/master/be/make-variables.html#custom_variables.

**Comment by facundominguez** [comment]
Looks like adding javac to the runfiles won't help. Runfiles are visible when a binary is executed. However, we need `javac` when we build the binary. The complication of a ghc plugin is that it is considered a library by the build system, yet it is executed by ghc when building targets that use them.

Should we give plugins a special status? Suppose we added an attribute to `haskell_library` that told whether the given library is a plugin, and therefore the runfiles should be made available when building libraries which depend on it.

In my experiments, I use `javac.location` to hard-code the absolute `realpath` to `javac` in the plugin. This seems to work but could cause problems when caching or deploying builds of inline-java.

One alternative could be to implement in `haskell_{binary/library}` the attribute `toolchains` that `cc_binary` and `genrule` have. This should allow to pass to the plugin the location of `javac` via ghc command line arguments and make variables. Thus every library using inline-java would look like:
```python
haskell_library(
  name = "sparkle"
  srcs = ...
  compiler_flags = "-fplugin-opt Language.Java.Inline.Plugin:javac=$(JAVABASE)/bin/javac",
  deps = [":inline-java"],
  toolchains = ["@bazel_tools//tools/jdk:current_java_runtime"]
)
```
I don't know if `compiler_flags` is subject to make variable expansion, but if we go this route, it should be made so.

**Comment by mboes** [comment]
> Looks like adding javac to the runfiles won't help. Runfiles are visible when a binary is executed. However, we need javac when we build the binary. The complication of a ghc plugin is that it is considered a library by the build system, yet it is executed by ghc when building targets that use them.

Similarly to what you suggest, we may well need a `haskell_plugin` rule for this very reason.

**Comment by Profpatsch** [comment]
I created a feature request https://github.com/tweag/rules_haskell/issues/772

**Comment by Profpatsch** [comment]
Is there anything else to be done here?

**Comment by facundominguez** [comment]
I think we are good for. Thanks!
