### ISSUE TITLE
Move hazel into rules_haskell

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#716]
`rules_haskell` should always be compatible with `hazel`, but `hazel` depends on `rules_haskell`, so we cannot add tests here. Since the two are closely connected, they should be merged into one repository.

For the complete reasoning, see https://github.com/tweag/rules_haskell/issues/703

The licenses are the same so that is not a problem.

- [x] get the approval of `hazel` authors
- [x] move the files (if possible merge git histories)
- [ ] add integration tests

Update:

- [ ] migrate issues
- [ ] deprecate old repository and point to `rules_haskell`

**Comment by thumphries** [comment]
Full approval from me (current Hazel "maintainer"). Will stay apprised of this ticket and all too happy to deprecate the Hazel repo on success.

@judah had a few requests about how this should be done in https://github.com/tweag/rules_haskell/issues/357#issuecomment-408224455 ; worth checking if he still feels strongly about them, particularly the `cabal2bazel` component.

**Comment by judah** [comment]
Sure, I also support this change.  FYI @blackgnezdo

To copy what I said from the other thread: Hazel is at its core a fork of (a subset of) https://github.com/google/cabal2bazel.  So I would prefer you to preserve Hazel's commit history when it's merged into rules_haskell, for example, via `git merge --allow-unrelated-histories`.  We plan to push out another version of `cabal2bazel` at some point, and that would make it easier for us to share improvements in both directions.

I do still think it would be better to keep what was forked from `cabal2bazel` in a distinct directory (in Hazel, it's currently `third_party/cabal2bazel`), to simplify any future merges and/or cherry-picks, and to make the license attribution easier .  But if that doesn't fit well into `rules_haskell`, let us know and we can probably figure out a way to work around it.

**Comment by nmattia** [comment]
Someone brought up that these commands should do the job:

- `cd $(mktemp -d)`: start fresh.
- `git clone git@github.com:tweag/rules_haskell.git`
- `cd rules_haskell`
- `git remote add hazel git@github.com:FormationAI/hazel.git` add hazel as a remote
- `git fetch hazel`: download current branches from hazel repo
- `git checkout hazel/master`: checks out the current master of hazel
- `git checkout -b merge-hazel`: create a new local branch
- `mkdir hazel; mv * .bazelrc .circleci .gitignore hazel/`: move everything but .git to the hazel subdir
- `git add .; git commit -m "move hazel to subdir"`: create a commit
- `git merge --allow-unrelated-histories master`: remember that `master` here is the local copy of `rules_haskell/master`
- `git push origin merge-hazel`: and now you can create a PR

though note that:

> When you merge this you'll get a slight weirdness in the history as there will be two merge commits but it shouldn't be too much of an issue, if you want to avoid that you can just push to master

@judah and @thumphries do you want to try this out and see if it yields an acceptable result?

**Comment by Profpatsch** [comment]
I’ll be merging https://github.com/DACH-NY/hazel/commits/da-master into `rules_haskell` now, which is a version that should be compatible with current `rules_haskell`.

**Comment by Profpatsch** [comment]
Here’s the PR: https://github.com/tweag/rules_haskell/pull/733

**Comment by nmattia** [comment]
Done in #733

**Comment by thumphries** [comment]
Thanks for doing all this work! Will archive the original Hazel repo when the next rules_haskell release goes out.
