### ISSUE TITLE
How to run hspec-discover?

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#724]
There used to be an `extra_binaries` option in the `haskell_toolchain` macro, but that seems to no longer be supported. How do I get hspec-discover to be visible at compile time?

**Comment by regnat** [comment]
See https://github.com/tweag/rules_haskell/issues/625: There's no official way to do it but it should be relatively easy to adapt the macro from https://github.com/tweag/rules_haskell/issues/625#issuecomment-456920122 to emulate the ghc plugin
