### ISSUE TITLE
Make sure all labels we use in `rules_haskell` are fully qualified

### ISSUE THREAD

**Issue by nmattia** [tweag/rules_haskell#726]
Last week I got bitten by rules_haskell's assumption that a `./haskell/` directory exists and contains a `ghc.BUILD` (see https://github.com/tweag/rules_haskell/pull/719#issue-256692187). Most likely this is only the case in the root of this repo. I suspect there are a few similar bugs lurking around.

One way to make sure that we don't make such assumptions is to have tests be run from a different directory.

CC @Profpatsch

**Comment by mboes** [comment]
You mean from a dependent project. Please update title and description accordingly. I think we should do better than this: detect all hard-coded labels and make sure they are all fully qualified.

**Comment by Profpatsch** [comment]
> detect all hard-coded labels and make sure they are all fully qualified.

What kind of labels are problematic for outside projects?

**Comment by mboes** [comment]
It's unclear that this still an issue. See https://github.com/bazelbuild/bazel/issues/7130.

**Comment by ylecornec** [comment]
Indeed, it seems that within the main repository, `//` at the start of labels should now be equivalent to `@rules_haskell//`.

**Comment by mboes** [comment]
OK let's close then.
