### ISSUE TITLE
Improve CPP macro error messages

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#730]
https://github.com/tweag/rules_haskell/issues/414 disabled CPP macro expansion by default, until a `version` attribute is specified. 

If the user doesn’t do that, she is greeted with a GHC output like

```
vector/Data/Vector.hs:308:0: error:
     error: missing binary operator before token "("
     #if MIN_VERSION_base(4,9,0)
     
    |
308 | #if MIN_VERSION_base(4,9,0)
    | ^
`gcc' failed in phase `C pre-processor'. (Exit code: 1)
```

because the gcc preprocessor called by GHC chokes on the unexpanded `MIN_VERSION_base` macro.

The error handling all through the stack is abysmal, but we should provide the user with a hint, akin to:

```
vector/Data/Vector.hs:308:0: error:
     error: missing binary operator before token "("
     #if MIN_VERSION_base(4,9,0)
     
    |
308 | #if MIN_VERSION_base(4,9,0)
    | ^
`gcc' failed in phase `C pre-processor'. (Exit code: 1)

rules_haskell hint: It looks like you need to enable the version macro expansion (it is disabled by default). You can achieve that by adding a `version` attribute to the `haskell_*` rule of this failing target.
```

I’d write a small golang wrapper around our GHC invocation that filters `stdout` and `stderr` to search for `MIN_VERSION` and append the hint at the end of `stderr` (it’s non-trivial in python because of blocking file handle reads, but should be simple to write in golang with channels).

Companion issue to https://github.com/tweag/rules_haskell/issues/465
cc @guibou

**Comment by mboes** [comment]
> I’d write a small golang wrapper around our GHC invocation that filters stdout and stderr to search for MIN_VERSION and append the hint at the end of stderr

That doesn't sound worth the additional complexity and extra failure modes to me. This is an upstream issue, more than a rules_haskell one. The error we show is the same as anyone would get with any undefined macro.

**Comment by symbiont-ji** [comment]
Since this is still open...
I have a dependency on, say, `store-0.7.4`. In my `WORKSPACE`, I have
```
http_archive(
    name = "store",
    build_file = "@//deps:store.BUILD.bazel",
    strip_prefix = "store-0.7.4",
    # sha256 = "",
    urls = [
        "https://hackage.haskell.org/package/store-0.7.4/store-0.7.4.tar.gz",
    ],
)
```
and then in `deps/store.BUILD.bazel` I have:
```
package(default_visibility = ["//visibility:public"])
load(
    "@rules_haskell//haskell:defs.bzl",
    "haskell_library",
    "haskell_toolchain_library",
)
haskell_toolchain_library(name = "base")
haskell_library(
    name = "store",
    srcs = glob(['src/**/*.hs']),
    src_strip_prefix = "src",
    deps = [
        ":base",
    ],
    compiler_flags = [
           "-XHaskell2010",
    ],
)
```

Building with `bazel build @store//:store` fails:
```
...
external/store/src/Data/Store/Impl.hs:295:0: error:
     error: missing binary operator before token "("
      295 | #if MIN_VERSION_base(4,9,0)
          |
    |
295 | #if MIN_VERSION_base(4,9,0)
    | ^
```

If this were a `haskell_library`, i would add a `version=` parameter, but `haskell_toolchain_library` does not take that parameter. What is the workaround?

**Comment by aherrmann** [comment]
The `version` parameter on `haskell_library(name = "store", ...)` is also required to make version macros of its dependencies visible. An easier solution may be to use `stack_snapshot` if you don't need to vendor the package or `haskell_cabal_library` to build a vendored Cabal package.

**Comment by aherrmann** [comment]
Closing as wontfix.

As @mboes said:
> That doesn't sound worth the additional complexity and extra failure modes to me. This is an upstream issue, more than a rules_haskell one. The error we show is the same as anyone would get with any undefined macro.
