### ISSUE TITLE
Check bazel version

### ISSUE THREAD

**Issue by facundominguez** [tweag/rules_haskell#741]
Check that rules haskell is being used with a version of bazel that is known to work.

A lower bound check should ensure a not-too-old bazel is used. And an upper bound check should ensure that a not-to-new version of bazel is used with an old version of `rules_haskell`. Ideally, the error message should hint what to do: either try a different version of bazel, or a newer version of rules_haskell, or lift the upper bound.

**Comment by facundominguez** [comment]
In other languages:
https://bazelbuild.github.io/rules_nodejs/common/check_bazel_version.html
https://github.com/bazelbuild/rules_go/issues/1108

**Comment by facundominguez** [comment]
This is what we might want to use here:
https://github.com/bazelbuild/bazel-skylib/blob/master/docs/versions_doc.md

Got it from https://github.com/bazelbuild/bazel/issues/1014#issuecomment-436734881

**Comment by smelc** [comment]
Closed by #1277
