### ISSUE TITLE
Add rules_haskell to regression-checked bazel projects

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#754]
Bazel has ~50 repositories it auto-checks for regressions on their CI for every release: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/821

We should make an effort to get `rules_haskell` in that list.

**Comment by jin** [comment]
You can start here :smile: https://github.com/bazelbuild/continuous-integration/issues/new?assignees=&labels=new-project&template=adding-your-project-to-bazel-ci.md&title=Request+to+add+new+project+%5BPROJECT_NAME%5D

**Comment by laurentlb** [comment]
Yes, it would be great to have it.
(I filed the same issue some time ago: https://github.com/bazelbuild/continuous-integration/issues/235)

**Comment by Profpatsch** [comment]
We [moved our start script to GHC bindists yesterday](https://github.com/tweag/rules_haskell/pull/804), meaning the runner won’t have to have `nix` installed for a simple setup check. I think we are ready to add at least a simple regression check to the upstream pipeline.

Since we also [merged hazel](https://github.com/tweag/rules_haskell/pull/733), we should be able to get rid of the nix requirement for most of our basic testing setup soon.

I don’t know if I can find the time to do this soon, but @laurentlb if you are interested I’d gladly help with any questions you have.

**Comment by laurentlb** [comment]
What is the status of this? Is there any blocker?

@fweikert may be able to help you with Buildkite integration.

**Comment by Profpatsch** [comment]
Most of our tests still depend on nix, but we could start by only enabling a subset of them in the Buildkite config.
Alternatively, the CI machine would have to have nix installed.

**Comment by philwo** [comment]
I haven't used nix myself yet, is it difficult to install? If it's just a matter of installing it in our Docker image, that shouldn't be a problem.

**Comment by Profpatsch** [comment]
Actually, we recently [switched to a non-nix setup for our tests](https://github.com/tweag/rules_haskell/pull/887/commits/79125608c850b6e21700fcedae01d8c91edbe74e), by adding a repository rule to install things with the [`stack`](https://docs.haskellstack.org/en/stable/README/) tool instead. So no additional provisioning of the build machine should be necessary.

**Comment by mboes** [comment]
@philwo Nix is no longer required. Have a look at the CircleCI config (`.circleci/config.yaml`) and the `build-linux-ghc-bindist` job in particular. That job assumes Bazel is in the Docker image along with a small set of other system dependencies that you probably already have, and is able to run a core part of the full rules_haskell test suite while assuming nothing else from the environment. We do disable a few tests, however. See `--build_tag_filters` line.

**Comment by Profpatsch** [comment]
https://github.com/tweag/rules_haskell/pull/1066 added us to the official upstream pipeline, and a few of our maintainers got access to https://buildkite.com/bazel/rules-haskell-haskell.

The next step is getting `rules_haskell` to actually build on the upstream buildkite, then they will add us to their downstream testing pipeline.

**Comment by Profpatsch** [comment]
@fweikert The CI is currently failing because we need the `libgmp-dev` apt package installed for GHC to work. Is there a way to add it to the build description yaml? cc @laurentlb @philwo 

Related, is there documentation of how the `.bazelci` file format works?

**Comment by fweikert** [comment]
We have to deploy the libgmp-dev package to our CI workers.

Configuration documentation: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#basic-syntax

**Comment by philwo** [comment]
@Profpatsch @fweikert I added the `libgmp-dev` package to our ubuntu1604, ubuntu1804 and debian10 environments and pushed the new containers, so it should be effective immediately.

**Comment by Profpatsch** [comment]
https://github.com/bazelbuild/continuous-integration/issues/235#issuecomment-531757882

**Comment by aherrmann** [comment]
AFAIU this is done.
