### ISSUE TITLE
Code coverage analysis with non-percentage evaluation options

### ISSUE THREAD

**Issue by SebastianKG** [tweag/rules_haskell#763]
The new code coverage functionality currently supports expression coverage analysis and can fail tests based on a user-specified integer percentage of expressions that should be covered.

@ghorn suggested in the previous coverage issue (https://github.com/tweag/rules_haskell/issues/33) that integer percentage may not be sufficient for his use case. In his own words:
> I'm not sure % coverage as an integer is a sufficient metric to prevent regressions. If you have 100 tests and someone adds one it probably won't change the number. A better metric could be number of uncovered "things" like expressions, if conditions, etc. Is there a mechanism for making people update the number when they improve it? Maybe if the actual coverage is not exactly equal to the number it would be better than if the actual coverage was less than the number for a failure condition.

This seems like it could be a common request, so it may be worth looking into. The desired functionality would be to implement another attribute for haskell_test rules. Currently we have

`expected_expression_coverage :: Int`

Instead we could have:

`expected_covered_expressions_percentage :: Int`
`expected_uncovered_expression_count :: Int`

Breaking the API on this feature (changing the name of the existing attribute) is probably okay if this is done fairly soon. Documentation will need to be updated accordingly.

**Comment by Profpatsch** [comment]
Another approach would be to have an attribute that points to a script with a defined input and output, so users can define their own metrics. aka replace `Int` by `CoverageData -> a`.

**Comment by SebastianKG** [comment]
Completed by https://github.com/tweag/rules_haskell/pull/777
