### ISSUE TITLE
Code coverage with scoping of which deps are included

### ISSUE THREAD

**Issue by SebastianKG** [tweag/rules_haskell#764]
Currently, code coverage functionality (activated using `bazel coverage`) builds all included libraries (srcs *and* deps) with coverage enabled for a `haskell_test` rule. This means the resulting values of expression coverage are based on coverage of every single Haskell library built from source by your local Bazel (not, however, dependencies pulled from Nix, etc.).

It would be nice to have some capacity to restrict the scope of the coverage test. To only the most directly included `haskell_library`s? To libraries in the same package? How configurable should this be? Still TBD.

**Comment by Profpatsch** [comment]
See also the recent Multi Target REPL PR: https://github.com/tweag/rules_haskell/pull/736. It includes a way to filter targets (in order to define which ones should be loaded from source and which as binaries).
