### ISSUE TITLE
Use skylib's _uniq over depset(foo).to_list()

### ISSUE THREAD

**Issue by Fuuzetsu** [tweag/rules_haskell#77]
We uses `depset(foo).to_list()` in many places to get unique elements of `foo`. Skylib offers this in a much faster way: build a dictionary with None values then use `.keys()`: apparently depsets do _not_ support fast membership check and to_list() is definitely bad.

Minor ticket but simple.

**Comment by Fuuzetsu** [comment]
In many places we may want to just using depset all together and instead build a uniq list: this is somewhat related to #87 : whatever info that's spit out should just spit a unique collection that's traversable instead of abusing depsets. As far as I understand in the end depsets don't give you anything but efficient union; if we're traversing or even checking for membership, we already screwed up and shouldn't use them.

**Comment by mrkkrp** [comment]
Do you mean "we may want to just **stop** using depset"?

**Comment by mrkkrp** [comment]
Looks like you're right, the relevant documentation: https://docs.bazel.build/versions/master/skylark/lib/depset.html. I'll add this refactoring to #106.

**Comment by mrkkrp** [comment]
Also, what `_uniq` is meant, I can't find anything with that name in skylib:

https://github.com/bazelbuild/bazel-skylib/search?utf8=%E2%9C%93&q=_uniq&type=

**Comment by mboes** [comment]
https://github.com/bazelbuild/bazel-skylib/blob/master/lib/collections.bzl#L69
