### ISSUE TITLE
Add a `ghc_plugin` attribute

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#772]
**Is your feature request related to a problem? Please describe.**

Based on the issue in https://github.com/tweag/rules_haskell/issues/713#issuecomment-476202960:

> Should we give plugins a special status? Suppose we added an attribute to haskell_library that told whether the given library is a plugin, and therefore the runfiles should be made available when building libraries which depend on it.

**Describe the solution you'd like**

A `ghc_plugin` attribute to `haskell_*` rules should be added, to specify dependencies that should be made available to the compiler as plugins.

**Describe alternatives you've considered**

We could name it `haskell_plugin` (as suggested in https://github.com/tweag/rules_haskell/issues/713#issuecomment-476204289), but the plugin API is really very GHC-specific.

We could add it to the toolchain, but each source file can use different plugins as far as I know (investigate).

**Comment by mboes** [comment]
This was added in #799 and followup PR's.
