### ISSUE TITLE
haskell_repl should not load all dependencies by default

### ISSUE THREAD

**Issue by SebastianKG** [tweag/rules_haskell#779]
`haskell_repl` currently loads all `deps` into the REPL scope. This makes loading the REPL take a long time, and is (I believe) almost never what is desired by the user.

It would be more covenient if only `srcs` were loaded into scope by default.

I've considered just adding some kind of pattern for what should be included, but that shouldn't be necessary. It's also not as easy as you would think to make a pattern for all `srcs`.

**Comment by SebastianKG** [comment]
@aherrmann Would love to hear your thoughts on this.

**Comment by aherrmann** [comment]
@SebastianKG could you specify what you mean by loading into the REPL scope? Do you mean that all sources are added using `:add` in the ghci script? Or generally that they're made available by source?

> haskell_repl currently loads all deps into the REPL scope. This makes loading the REPL take a long time, and is (I believe) almost never what is desired by the user.

In the client use-case that motivated adding the `haskell_repl` rule they explicitly wanted to load all workspace local targets (excluding some vendored ones) into the REPL by source.

> It would be more covenient if only srcs were loaded into scope by default.
>
> I've considered just adding some kind of pattern for what should be included, but that shouldn't be necessary. It's also not as easy as you would think to make a pattern for all srcs.

`haskell_repl` doesn't have a `srcs` attribute. Which `srcs` are you referring to?


Sorry, if those are silly questions. I might be missing some context. Do you have a concrete example for this issue?

**Comment by SebastianKG** [comment]
This ended up being solved indirectly by the above PR. We decided that haskell_repl's default behaviour shouldn't change, but the user can now elect to scope which dependencies are loaded.
