### ISSUE TITLE
Create tutorial for setting up a haskell toolchain (bindists & nixpkgs)

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#780]
The current tutorial focuses on what to do *once* you have a working toolchain setup.

As we can see in issues like https://github.com/tweag/rules_haskell/issues/776, bazel’s error messages are extremely poor when it comes to workspace rules and toolchains, plus the logic on what goes where is *extremely* convoluted, especially for a new user.

We must provide a step-by-step example and self-contained setups that can be copied for each supported path and decouple them from `rules_haskell` in a way that they are self-contained (which is not extremely easy, because `bazel //...` happily tries to build all subdirectories, even those with `WORKSPACE` files in them.

**Comment by smelc** [comment]
I could pick up this task but it's unclear to me if there's something we wanna add: since this issue was created, the tutorial was augmented, see e.g. https://github.com/tweag/rules_haskell/commit/ebdc3f18e8a6d2118bc1a581c9a788b763492736#diff-5f5e275525bbf8345047d3df2fb0f087
cc @aherrmann

**Comment by aherrmann** [comment]
That's a good point, it looks like all the necessary information is there. Though, it's a bit hard to discover from just following the tutorial: The ["Set up the workspace" section](https://rules-haskell.readthedocs.io/en/latest/haskell.html#set-up-the-workspace) only talks about empty `WORKSPACE` files, but says nothing about external dependencies (like `rules_haskell` or a GHC distribution). We could improve it by mentioning that the `WORKSPACE` file also defines external dependencies and registers toolchains, and by pointing to the [toolchain setup section](https://rules-haskell.readthedocs.io/en/latest/haskell-use-cases.html#picking-a-compiler).
