### ISSUE TITLE
Provide cache for CI

### ISSUE THREAD

**Issue by nmattia** [tweag/rules_haskell#781]
**Describe the bug**

CI is too slow.

**To Reproduce**

Add Hazel to the build: https://github.com/tweag/rules_haskell/pull/733
For this commit: https://github.com/tweag/rules_haskell/pull/733/commits/e61102f7155a3fa6e1db945c1dca9f34c479c7e8
Windows build time: 16mn https://dev.azure.com/tweag/rules_haskell/_build/results?buildId=1196

CircleCI: https://github.com/tweag/rules_haskell/pull/733/checks?check_run_id=85487250

Darwin's been running for 30mn at the time of writing: https://circleci.com/gh/tweag/rules_haskell/5050?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Expected behavior**

On a no-op change (as is the case for all pipelines except windows in the commit above) should be definitely no longer than 5mn.

**Environment**
 - OS name + version: everything
 - Bazel version: 0.22.0
 - Version of the rules: N/A

**Notes**

There may be an issue on Windows: #744 
Related: #319 #314 

CC @flokli

**Comment by flokli** [comment]
With #1003, #1012 and mergify, is this still an issue?
