### ISSUE TITLE
Provide a start script for a setup based on nixpkgs

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#784]
After we implement https://github.com/tweag/rules_haskell/issues/604, users on NixOS might have a hard time setting up a basic example without `rules_nixpkgs` support. We should provide a second start script (`/start-nixpkgs`), or make the start script ask interactively.

**Comment by mboes** [comment]
Or auto-detect NixOS.

**Comment by Profpatsch** [comment]
Apparently we forgot about OSX, which also only works with the nix backend, see https://github.com/tweag/rules_haskell/issues/855.

In https://github.com/tweag/rules_haskell/issues/855#issuecomment-488819184 I give an example of a working `WORKSPACE` file. Trying to get it to run with `rules_haskell` 0.8 is completely hopeless.
