### ISSUE TITLE
Interop with java rules

### ISSUE THREAD

**Issue by Fuuzetsu** [tweag/rules_haskell#80]
If a Java dependency is provided, add its (transitive?) jar(s?) to CLASSPATH during compilation. This should allow much more natural implementation of things like https://github.com/tweag/sparkle/pull/133

**Comment by johnynek** [comment]
in bazel, you would not add the transitive deps to the compile classpath, but instead the transitive compile classpath (which only includes direct deps and exports).

Skylark does have a pretty good java API, so this is quite doable.

**Comment by Fuuzetsu** [comment]
Right now I'll only be adding direct deps to classpath because bazel throws NPE if I try to access `transitive_compile_time_jars` (which is what I think you mean we should be using) on one of our Java targets. I'll be filing a ticket in a bit after I craft a repro case.

**Comment by Fuuzetsu** [comment]
Relevant upstream ticket: https://github.com/bazelbuild/bazel/issues/4384

**Comment by mboes** [comment]
Close? We can create another ticket to track the upstream issue.

**Comment by Fuuzetsu** [comment]
I don't know. The ticket is just not complete until we have that I would think. We can create one to track upstream I guess.

**Comment by mboes** [comment]
We have Java interop - just sometimes the `CLASSPATH` isn't exactly the one we want. I thin you should claim victory for this ticket and create another one for what remains.

**Comment by Fuuzetsu** [comment]
#96
