### ISSUE TITLE
Migrate from Skydoc to Stardoc

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#807]
The Skydoc version we use currently is 0.2, Skydoc has been deprecated since 0.3 and will vanish soon. See the [deprecation notice](https://skydoc.bazel.build/docs/skydoc_deprecation.html) for more information & migration instructions.

**Comment by Profpatsch** [comment]
https://github.com/tweag/rules_haskell/pull/804#issuecomment-479004673

**Comment by aherrmann** [comment]
This was done in https://github.com/tweag/rules_haskell/pull/1244.
