### ISSUE TITLE
haskell_test: cannot satisfy package hspec

### ISSUE THREAD

**Issue by chris-bacon** [tweag/rules_haskell#812]
**Describe the bug**
I feel like this is a simply one where I am missing something. 

My `WORKSPACE` file is the `WORKSPACE` generated by the start script. Inside `test/BUILD`, I have,

```
load(
    "@io_tweag_rules_haskell//haskell:haskell.bzl",
    "haskell_toolchain",
    "haskell_import",
    "haskell_test",
)

haskell_import(name = "base")
haskell_import(name = "hspec")

haskell_test(
  name = "mytest",
  srcs = ["Spec.hs"],
  deps = [
    ":base",
    ":hspec"
  ],
)
```

Inside `test/Spec.hs` I have, 

```
module Main where

import Test.Hspec

main = hspec $ describe "" $ it "" $ 1 `shouldBe` 1
```

Upon running `bazel build //...` or `bazel test //...` I get,

```
INFO: Invocation ID: 80420246-c33b-4c6e-b7f9-2e736d804466
INFO: Analysed 7 targets (0 packages loaded, 0 targets configured).
INFO: Found 7 targets...
ERROR: {repo_root}/test/BUILD.bazel:11:1: error executing shell command: '/bin/bash -c 
        export PATH=${PATH:-} # otherwise GCC fails on Windows
        readarray -t ghc_args < bazel-out/k8-fastbuild/bin/parse-csv/test/ghc_args_parse-csv-test_HaskellBuildBinary
   ...' failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
<command line>: cannot satisfy -package hspec
    (use -v for more information)
INFO: Elapsed time: 0.475s, Critical Path: 0.10s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**To Reproduce**
See above.

**Expected behavior**
I expect it to build.

**Environment**
 - OS name + version: Linux Ubuntu
 - Bazel version: 0.22.0
 - Version of the rules: 0.8

**Comment by Profpatsch** [comment]
`haskell_import` can only refer to packages from the GHC distribution, which contains `base`, but not `hspec`.

If you want to use a dependency from hackage, we provide two ways:
* pull it via nix, via the [`nixpkgs workspace rules`](https://api.haskell.build/haskell/nixpkgs.html)
* use [`hazel`](https://github.com/FormationAI/hazel), which we will distribute with `rules_haskell` from the next release.

**Comment by chris-bacon** [comment]
That makes sense now! Cheers @Profpatsch :)
