### ISSUE TITLE
Regression: start script should not use unreleased rules_haskell

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#815]
**Describe the bug**
1fcd3c13ed8184bbf82c425309836686ca6ddf68 made the `start` script use whatever is the current `master` branch of rules_haskell. That's not a good user experience, because the `master` branch can introduce arbitrary breaking changes that may or may not make it into the next release. It is less stable than a release. We should use the latest rules_haskell release, like previously.

There is another bug here. 9a9452749831cf203857d28d50c5f7a1f3c9da89 removed the repository override. But there is a strong reason why that was there. See 4082d4d5f3d51c1b6a90f94afd5e803f9b13508d, the original commit that introduced it. As-is, when we upgrade Bazel in a feature branch but force the `start` script in that feature branch to use `master`, then we'll get spurious failing builds with no way to fix except to merge the feature branch.

**To Reproduce**
See https://circleci.com/gh/tweag/rules_haskell/5384?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link. This is an example of a CI build that fails with no way to make it go green without merging a red branch first.

**Expected behavior**
I expect two things:

1. the `start` script to use release versions only.
2. feature branch builds to be self-contained. That is, to use the rules_haskell code for all parts of the build as found on that branch, not code as found on other branches for parts of the build.

**Comment by Profpatsch** [comment]
> made the `start` script use whatever is the current `master` branch of rules_haskell.

Uhh, that shouldn’t have made it into the commit. It needs to be reset to the release version.

**Comment by Profpatsch** [comment]
> [9a94527](https://github.com/tweag/rules_haskell/commit/9a9452749831cf203857d28d50c5f7a1f3c9da89) removed the repository override. But there is a strong reason why that was there. See [4082d4d](https://github.com/tweag/rules_haskell/commit/4082d4d5f3d51c1b6a90f94afd5e803f9b13508d), the original commit that introduced it.

I missed that commit. I don’t understand the description, but I can revert my commit.
