### ISSUE TITLE
Add buildozer as another linting tool

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#818]
https://github.com/bazelbuild/buildtools/tree/master/buildozer is a starlark AST-rewriting tool.
It has a linting mode (`buildozer fix`) that can apply a few linting fixes automatically, like moving `load` statements to the top of files. We already use `buildifier-fix`, so we should apply those fixes as well.

They are “documented” in https://github.com/bazelbuild/buildtools/blob/895625218c56cdb73dbac181329eb7f693c0ab26/edit/fix.go

**Comment by laurentlb** [comment]
Using Buildifier-fix should be enough.
Buildozer fixes are historical, you can file a bug if something is missing in Buildifier.

**Comment by aherrmann** [comment]
As I understand @laurentlb's comment `buildifier-fix` supersedes `buildozer fix`.
