### ISSUE TITLE
Shorten GHC command lines by using package environment files

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#819]
Especially on MacOS we often breach the maximal command line length for client problems.

GHC supports so-called [“package environment” files](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/packages.html#package-environments), which can list all dependencies that would otherwise have to go in the arguments as `-package-id` or `-package-db`. 

This might be an easy win concerning argument length.

If I see this right, we only have to patch this in one place, the body of `pkg_info_to_ghc_args`.

cc @aherrmann

**Comment by mboes** [comment]
Aren't we already using param files for everything, precisely due to command-line length limitations, hence making the point moot?

**Comment by aherrmann** [comment]
I think not too long ago this was an issue on Windows. IIRC @nmattia was fighting with that. @nmattia would package environment files have helped in that case?

**Comment by nmattia** [comment]
Maybe it would have helped a little bit, but the problem was really the list of (module) files: https://gitlab.haskell.org/ghc/ghc/issues/16476
