### ISSUE TITLE
Start an appropriate ghci from Bazel

### ISSUE THREAD

**Issue by aspiwack** [tweag/rules_haskell#82]
Cabal and stack have a `ghci` subcommand (_e.g._ `stack ghci`) which loads the appropriate environment (compiler, dependencies, runs within docker or nix when appropriate) as well as the files for the project.

This is used by most IDEs (`intero`, `dante`, `ghcid`) to provide feedback to the programmer (type errors, type informations, completion options, etc…).

In order to provide compatibility with these IDEs, there should be an equivalent invocation of `ghci` with Bazel and rules_haskell, which uses the `WORKSPACE` and `BUILD`.

**Comment by mboes** [comment]
Blocked by https://github.com/bazelbuild/bazel/issues/1394. @johnynek the original ticket was filed in mid-2016, but given what you know now, do you think making the required changes to Bazel itself would be easy? Might be worth pooling our efforts on this one.

**Comment by johnynek** [comment]
What we did in the scala rules was make a `scala_repl` rule. It’s more work, but it works.

Then people make a scala_repl target that has the deps they want then they can script_run that target.

I would love to help with a doc proposing adding a repl command to bazel but the work around above has taken a lot of my enthusiasm.
