### ISSUE TITLE
Missing version macros on hsc files.

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#821]
**Describe the bug**
rules_haskell tells ghc to generate version macros if a target has a version attribute. However, with hsc files rules_haskell runs them through the hsc2hs preprocessor first, which doesn't seem to generate version macros in that case.

**To Reproduce**
Checkout https://github.com/tweag/rules_haskell/commit/25fc107002d9b8bb260da15ea058e163a28f65b3 and execute `nix-shell --pure --run 'bazel test //tests/package-name:bin-c'`

**Expected behavior**
Version macros should also be generated for `.hsc` files, so that the example above passes.

**Environment**
 - NixOS + 18.03:
 - Bazel version: `rules_haskell` Nix shell.
 - Version of the rules: Revision 25fc107002d9b8bb260da15ea058e163a28f65b3

**Additional context**
https://github.com/tweag/rules_haskell/commit/25fc107002d9b8bb260da15ea058e163a28f65b3 adds a regression test which currently fails with the following error due to missing version macros:
```
Main.hsc:12:24: error: missing binary operator before token "("
Main.hsc:18:24: error: missing binary operator before token "("
Main.hsc: In function 'main':
Main.hsc:12:24: error: missing binary operator before token "("
Main.hsc:18:24: error: missing binary operator before token "("
Main.hsc:12:24: error: missing binary operator before token "("
Main.hsc:18:24: error: missing binary operator before token "("
```

This also seems to be the cause for https://github.com/tweag/rules_haskell/issues/796.

**Comment by Profpatsch** [comment]
cc @guibou

**Comment by guibou** [comment]
AFAIK `hsc2hs` does not generate version macro. I wonder if we are supposed to generate by ourself. In this case, it may be a good idea to rework all of this and have a saner default (i.e. macro version generated for package with version flag, when they are used as a dependency).

We need to check what `cabal` is doing here.

**Comment by aherrmann** [comment]
@guibou Indeed, `hsc2hs` itself does not generate version macros. Cabal generates a header file for these itself and [passes it on to the various tools that need it](http://hackage.haskell.org/package/Cabal-2.4.1.0/docs/src/Distribution.Simple.BuildPaths.html#cppHeaderName). The Cabal library [exposes that functionality as well](http://hackage.haskell.org/package/Cabal-2.4.1.0/docs/Distribution-Simple-Build-Macros.html).

It seems we'll have to generate it ourselves.
