### ISSUE TITLE
Use relocatable GHC bindists

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#841]
**Is your feature request related to a problem? Please describe.**

When using GHC from Nixpkgs, the content of the `bin/ghc` script and all absolute paths in all other files inside the GHC folder is always the same. In particular, these paths do not depend on the current user's name. Not so with bindists. After `./configure && make install`, we end up with absolute paths that include a Bazel cache key. This key changes if the the location of the Bazel checkout changes, hence will be different for different users typically. Since `bin/ghc` and others are inputs of the toolchain rule, and the toolchain an input to nearly every action, the action cache becomes useless across different users on different machines.

**Describe the solution you'd like**

Use the `RelocatableBuild` feature of the GHC Makefile's. This should be set in `mk/config.mk.in`. This setting will prevent any absolute paths from going into package conf's in the package database. But it won't fix the wrapper scripts in `bin/`. However, we can patch that (and submit a fix upstream to avoid having to patch this ourselves in future GHC releases).

**Comment by aherrmann** [comment]
Addressed in #853.
