### ISSUE TITLE
Make Coverage Report Renderer More Available to Clients

### ISSUE THREAD

**Issue by SebastianKG** [tweag/rules_haskell#850]
Currently, the coverage report renderer is fully implemented, but unusable for most client workspaces, because it relies on this repository's naming structure for Haskell packages as dependencies.

I see a few different options for solutions:

1. push the package up to Hackage/Stackage/etc and let clients pull it down themselves
2. include a function for importing the dependencies into the client's WORKSPACE file, and hardcode the dependencies as coming from that new source

**Comment by Profpatsch** [comment]
The coverage renderer is something that we provide, so we should provide the dependencies (2), in a fixed version that always works.

**Comment by SebastianKG** [comment]
This ended up being solved by pushing the coverage report renderer to Hackage. https://hackage.haskell.org/package/bazel-coverage-report-renderer

It wasn't possible to upstream by providing a Bazel utility, so the user will need to pull from Hackage and use the binary.
