### ISSUE TITLE
Relocatable binaries

### ISSUE THREAD

**Issue by Fuuzetsu** [tweag/rules_haskell#86]
Ideally `rules_haskell` should produce binaries that are relocateable. This is a discussion ticket. Most basic things to consider:

Relocateable where:
* elsewhere on build host
* onto a different host

There are multiple things to solve
* non-absolute dynamic libraries: this is all .so objects we depend on that come from bazel itself for example.
* absolute dynamic libraries: if we use something like rules_nixpkgs toolchain for system libs, we can only move the binary onto hosts with those libraries present
* runtime files: bazel has some support for files needed at binary runtime: think of something like Cabal's `getDataDir`. These have to be moved with the binary.

Possibly we can use [packaging rules](https://docs.bazel.build/versions/master/be/pkg.html) to help somehow. I'd be interested to see what `pkg_tar` results in: perhaps it will dutifully copy both dependencies and runtime files with the binary out. I don't think we can do much about absolute dynamic binaries so if we want to cross host boundaries we'll have to do something magic. Ideally we probably don't want to rely on absolute paths at all. May require GHC work(?).

----

I think non-targets of this ticket are movable `haskell_library` and `haskell_haddock` artifacts: both may be desired though: haskell_library for general use and haskell_haddock if we want to host the docs somewhere for example.

**Comment by jayed** [comment]
Moving binaries to a different host is my ideal use case.

**Comment by Profpatsch** [comment]
We already provide quasi-static (except for the standard system stuff) building with `linkstatic = True` and [there’s a ticket for full static binaries](https://github.com/tweag/rules_haskell/issues/379).

Relocatable binaries should only be a matter of resolving all symlinks in the `runfiles` directory of a target (or the files in `MANIFEST` on Windows) and tarring the resulting directory.

I suggest we close this issue until there is some explicit need to have this feature implemented.
