### ISSUE TITLE
haskell_repl experiences name conflicts between packages

### ISSUE THREAD

**Issue by SebastianKG** [tweag/rules_haskell#867]
**Description**
When using `haskell_repl`, if you have an external-to-the-WORKSPACE dependency which is named `package_a`, and there is a package in Hackage called `package_a` that is also your dependency, only one of the two will be loaded into the REPL.

**To Reproduce**
* Make a `haskell_repl` target which depends on a target and on a Hackage package which share a name.
* `bazel run` your `haskell_repl` target
* You should see an error regarding modules from one of the two conflicting packages not being added into the REPL scope.

**Expected behavior**
When doing the steps to reproduce, no error should occur and all expected modules should be loaded.

**Additional Notes**
This may be nicely fixed if the REPL can import with the package ID instead of the package name, since the work has been done to make those unique.

There are problems with qualifying the package name: Hazel needs the correct package name for versioning, and Windows might suffer from the longer paths.

**Comment by Profpatsch** [comment]
@SebastianKG Is this still a problem?

**Comment by aherrmann** [comment]
`haskell_repl` [uses `-package-id`](https://github.com/tweag/rules_haskell/blob/9c5d3dc5fa63de85194392f3d07d4f32f58587bf/haskell/repl.bzl#L318) now, so this should be fixed.
