### ISSUE TITLE
Don't use HaskellPackageInfo as build information structure

### ISSUE THREAD

**Issue by Fuuzetsu** [tweag/rules_haskell#87]
HaskellPackageInfo contains far too much information and a lot of it is only needed during build: if a user was to inspect this provider for a target, they would find all information clumped together without being any wiser about the target itself.

gather_dependency_info should use a dedicated structure for build information and HaskellPackageInfo should only carry the information that it needs for itself + any other info that's absolutely needed where transitive dependencies are concerned.

**Comment by Fuuzetsu** [comment]
I spent a little time giving this a go (on cleanup-haskell-package-info) and conclusion is poor. Using a dedicated structure for gather_dependency_info works but actually ends up being what HaskellPackageInfo is right now. On top of this we would now also have a HaskellPackageInfo which would end up unused. The reason is that we really do need all that info: we just don't necessarily need it in our "default" provider. However outputting two providers is not useful for us because if you want to do just about anything with a package, you need all transitive stuff anyway ;/

Possible ways forward:
* Rename HaskellPackageInfo to HaskellBuildInfo, make HaskellPackageInfo return only information for the package: this is more or less original idea but we now have to expose HaskellBuildInfo to users either way. It doesn't end up cleaner internally either. What it does improve is if user wants to perform some simpler queries on individual package. This would need exposing those be it in new HaskellPackageInfo or current one anyway.
* Keep HaskellPackageInfo but simply clean up its usage throughout rules and the way we build it.
* Do nothing and close the ticket, wait for user requests if they want something else from provider.

For now just unassigning myself.

**Comment by mboes** [comment]
What two providers would you see?

**Comment by mboes** [comment]
> * Do nothing and close the ticket, wait for user requests if they want something else from provider.

Opting for this option.
