### ISSUE TITLE
Haskell/CC/Haskell sandwich leads to spurious extra-libraries

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#873]
**Describe the bug**
Assume the following dependency structure:

```python
haskell_library(name = "A", ...)
cc_library(name = "B", deps = ["A"], ...)
haskell_library(name = "C", deps = ["B"], ...)
```

then the package db `.conf` file for `C` will include both `B` and its dependencies (i.e. Haskell libraries) in its `extra-libraries` field. This causes all manner of subtle problems, in particular because GHC will during linking pull in `A` via the `hs-libraries` field in `A`'s `.conf` file and pull it in again via the `extra-libraries` field in `C`'s `.conf` file.

Admittedly, this use case is fairly contrived, in that CC dependencies are usually system libraries that don't themselves depend on Haskell libraries. But Hazel is an example. Also, this use case is illustrative of a deeper problem.

**To Reproduce**
Checkout ca1e955fe12c5b70b415a6a245bdfddea4cc021d and

```
$ bazel test tests/hs_cc_hs_sandwich
```

Inspect `.conf` files.

**Expected behavior**

There should be no duplicate edges in the dependency graph. Segmentation faults have been observed on Darwin when these occur.

cc @aherrmann

**Comment by mboes** [comment]
One way to solve this is to filter out any library whose name starts with `HS` in `extra-libraries`. That's a hack though. In principle, there should be little difference between CC libraries and Haskell libraries. They're all just pairs of (static library, dynamic library) after all (even though GHC's preferred view is not that simple).

Another way to solve this would be to drop using package databases during the linking phase. In fact package databases sometimes feel like unnecessary overhead in rules_haskell. We do need them because they are the only way we can support features like module thinning and reexports. They will also be necessary for Backpack support down the road. Because we need them, we currently use them at each stage of the build. But that's not entirely necessary.

All the information we need for linking is maintained in-memory in Bazel providers. The problem we are seeing here is a symptom of the fact that there are two parallel ground truths that sometimes conflict with each other: the set of dependencies as exposed in the providers, and the set of dependencies GHC actually sees via the `.conf` files. What we should do is declare the `.conf` files the ground truth for compilation only, and then forego them for linking, since we already have all the information we need in the providers (including link order for static libraries).

We can still call GHC to do the linking, though we could also use the link actions from the CC Starlark API. The latter is out of scope for this ticket. It's just that during the linking phase, instead of passing `-package-id foo` to GHC, we instead directly pass `-lHSfoo -L<dir>` etc, based on the dependencies found in the providers.

Now, @aherrmann might object that we're still left with the Template Haskell problem. He would be right. TH does its own linking at compile time. We don't have any control over that from Bazel. But it turns out that package databases already allows two sets of dependencies to be declared, including an alternative one for GHCi/TH (using the `extra-ghci-libraries` field). Since GHCi only needs the dynamic libraries (or only the static libraries on Windows), i.e. a single "way", we can forego recording anything in `hs-libraries` entirely, and record only one variant (static or dynamic) of every dependency in `extra-ghci-libraries`, leaving `extra-libraries` blank as well.

That way Bazel providers carry the authoritative truth for linking programs, and package conf files are the authority for GHCi's linking.

cc @moritzkiefer-da

**Comment by cocreature** [comment]
(Just to avoid confusion, I’m the same person as @moritzkiefer-da)
As mentioned in #728 we are already putting in Haskell libraries in `extra-libraries` and so far it seems to work quite well. One thing that I brought up when discussing this with @aherrmann is that I am not quite sure how it interacts with profiling. It seems like in theory it should be possible to get it work but I wouldn’t be surprised if there is some magic somewhere in the linker that only gets turned on when libraries are declared in hs-libraries so this is definitely something that should be checked first.

**Comment by cocreature** [comment]
Oh and another point: The `rts` lib seems to be special and if you don’t put the corresponding library in `extra-libraries` then `-threaded` will not pick up the right rts lib.

**Comment by aherrmann** [comment]
> Another way to solve this would be to drop using package databases during the linking phase.
> [...]
> What we should do is declare the .conf files the ground truth for compilation only, and then forego them for linking, since we already have all the information we need in the providers (including link order for static libraries).

In the context of Bazel this sounds like the cleanest solution to me. At that point it's probably also easier to defer linking to the Cc Starlark API.

> TH does its own linking at compile time. We don't have any control over that from Bazel. But it turns out that package databases already allows two sets of dependencies to be declared, including an alternative one for GHCi/TH (using the extra-ghci-libraries field). Since GHCi only needs the dynamic libraries (or only the static libraries on Windows), i.e. a single "way", we can forego recording anything in hs-libraries entirely, and record only one variant (static or dynamic) of every dependency in extra-ghci-libraries, leaving extra-libraries blank as well.

I think this can be made to work. Though there are a few technical difficulties to keep in mind.

- The `extra-ghci-libraries` field (same as the `extra-libraries` field) only takes library names, not fully qualified paths to library files.
    - For dynamic libraries Bazel produces `.so` files on platforms where GHC expects different endings, e.g. `.dylib`. We're already working around this by create symbolic links for such `.so` files. The same workaround should apply here.
    - For static libraries Bazel does not mangle the names, so that libraries with identical target name have conflicting library names (https://github.com/tweag/rules_haskell/issues/862). To avoid such collisions in the `extra-ghci-libraries` field we'll have to apply our own mangling and create symlinks.
- In some cases GHC generates temporary dynamic libraries during compilation which link against all dependencies. If we're not careful we can quickly exceed the MACH-O header size limit in these temporary objects. We should use static libraries for dependencies wherever possible to avoid this.

**Comment by aherrmann** [comment]
I've experimented with some of the ideas above:

### Recache toolchain libraries

In 584f34fd7ad80e75ab4a797f1b3228084fbc5074 I've dropped the global package-db and generated and cached new package configurations for the toolchain libraries. This allows full control over the package configuration entries. E.g. to drop `hs-libraries`. In this commit the package configuration no longer carries any libraries. Building the objects for a simple target succeeds this way. Linking still fails due to missing references to the RTS header files. Looking at the output of `ghc -v` during linking it seems that GHC performs some more compilation steps. 

### Linking with the Cc Starlark API

In b87a11d1d5500dcd10ea1c585cb4a1ca79b1780b I've further replaced GHC by the Cc Starlark API for linking - so far only for `haskell_binary`. I've tested this on Bazel 0.26.0rc11, because 0.24.0 does not seem to expose linking of binaries in the Starlark API. It was not straight forward to update the Nix expression for Bazel, so I'm using a Bazel binary installation with the GHC bindist instead. I've noticed two complications:

First, we need to construct an explicit list of all object files generated during compilation to pass to `cc_common.create_compilation_outputs`. With GHC as the linker we get away with only specifying the output directory for object files. In the general case this might require more careful handling of `src_strip_prefix` and possibly allowing users to specify a list of source directories, at least for Hazel.

Second, at this point linking fails as follows:
```
/usr/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/8/../../../../lib64/crt1.o: in function `_start':
/home/abuild/rpmbuild/BUILD/glibc-2.29/csu/../sysdeps/x86_64/start.S:104: undefined reference to `main'
```

GHC probably generates a small wrapper `main` at the linking stage to generate the final binary, that may be the compilation step in the linking phase mentioned above. Using the Cc Starlark API for linking may require us to replicate that logic in rules_haskell.

**Comment by Profpatsch** [comment]
Is this still a problem?

**Comment by aherrmann** [comment]
`rules_haskell` works around it using the approach that @mboes described above
> One way to solve this is to filter out any library whose name starts with HS in extra-libraries. That's a hack though.

It's not a clean solution, but I'm currently not aware of a better way around this problem.

Dropping `hs-libraries` and carrying everything in `extra-libraries`, as described above, is unfortunately incompatible with GHC plugins.

**Comment by Profpatsch** [comment]
The source code TODO was removed in https://github.com/tweag/rules_haskell/pull/1256/commits/8a6515df62679b15f6459c420fa91e94347dc903#diff-bd64d8d5f7f730dd6c86f3c013668198L36-L53

@aherrmann can we close this issue?

**Comment by aherrmann** [comment]
Yes, we're now using [`get_cc_libraries`](https://github.com/tweag/rules_haskell/commit/8a6515df62679b15f6459c420fa91e94347dc903#diff-dc1393f8dc2b51503ee202cbd8e1f1dfR32-R51) to avoid such spurious extra-libraries.
