### ISSUE TITLE
Direct Cabal support

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#874]
**Is your feature request related to a problem? Please describe.**

We have @formationai's Hazel checked into this repository. Using Hazel, we can emulate Cabal on top of basic rules_haskell primitives, like `haskell_library`, `haskell_binary` etc. The problem is that Hazel is not simple. More specifically,

* Cabal is a beast with by now very complicated semantics that don't map very well to assumptions made by rules_haskell. For example, we end up needing to push versions through `haskell_library` and also reimplement our own CPP version macros for those tools that don't generate them themselves. This adds some complexity and extra code to the core rules. But there are also cases where rules_haskell makes Hazel's life hard, e.g. because rules_haskell insists on compiling cbits separately from Haskell code, leading to hacky workarounds in Hazel.
* Getting Hazel support to the level where all Cabal packages work even on Windows has proved challenging. Between .buildinfo files, configure scripts and the like, the surface area offered by Cabal is quite large, and getting everything right on all platforms is tough.

**Describe the solution you'd like**

There is another way to build Cabal libraries: call Cabal itself instead of emulating it. This is not a fantastic idea for new libraries, but for existing ones that already have a .cabal file (+ configure scripts and custom hooks potentially), better to reuse the existing build system as a black box rather than attempt translating it. We can still get the benefit of sandboxing, remote caching and distributed builds, if at a less granular level.

We would need two components.

One is, provided an unpacked source distribution, a way to call `Setup.hs`, to populate `HaskellInfo`, `HaskellLibraryInfo` and `CcInfo` providers in particular including a package database for the package and a (static, dynamic) library pair.

```python
haskell_cabal_library(
    name = "transformers-0.5.2.0",
    srcs = glob(["**"]),
    deps = ...,
)
```

If the above exposes the exact same providers as a `haskell_library`, then they become interchangeable.

The other component is a way to generate a dependency graph from a package set, so that the above doesn't need to be written manually. We can introduce a workspace rule that:

* given a list of Cabal dependencies, computes the transitive closure of all Cabal packages we'll need,
* downloads all source distributions for all transitive Cabal dependencies and unpacks them.

We could design it along the same lines as rules_jvm_external. Key differences with Hazel:

* There is a single external repository hosting all sources, rather than one per package.
* This makes it possible to have multiple versions of a Cabal package available, although defined in separate external repositories.
* This is also slightly more efficient, because the full dependency graph is visible to Bazel upfront, in a single `BUILD.bazel` file, rather than scattered across many external repositories that need downloading. (Keep in mind that I don't really know the details of the Hazel model.)

It would look something like this:

```python
stackage_snapshot(
    name = "stackage",
    snapshot = "lts-13.20",
    packages = ...,
)
```

The list of packages could be made optional, in which case we would compute the dependency graph for the entire snapshot. But that will in the future require fetching all sources for all packages or at least fetch the Hackage index of Cabal files. The reason is that the LTS build plan files that Hazel was relying on are now being phased out following the introduction of pantry in Stack. New-style snapshot files do not include dependencies and reverse dependencies like the old ones did.

How does `stackage_snapshot` work under the hood? We potentially have a bootstrap problem, like Hazel does, if we need a GHC toolchain available in order to interpret Haskell code that does the parsing of the plan files or Cabal files. One option here is to outsource all dependency analysis to Stack (which features `stack ls dependencies` and `stack dot` subcommands). We can download prebuilt Stack binaries from the official locations, or expect a `stack` command from the environment. Bootstrap problem avoided. No prep commands like `runhaskell Stackage.hs packages.bzl` required ahead of the `bazel build` command any time the snapshot changes.

**Describe alternatives you've considered**

The main alternative is to press on with making Hazel work on Windows. Calling Cabal rather than emulating it is likely less code to maintain in the long run, so there would need to be benefits to the Hazel approach to justify maintaining the extra code. At this point, it's unclear to me what the benefits really would be.

cc @thumphries @aherrmann @moritzkiefer-da

**Comment by aherrmann** [comment]
I'd very much welcome direct Cabal support in rules_haskell.

Some notes about Hazel:

- Hazel uses the stackage snapshot to pin package versions. But, it doesn't use it to discover the dependency graph. Instead, for each package it fetches the source tarball and parses the Cabal file to discover package dependencies. Since each package lands in its own external workspace, Hazel gets away with this without having to fetch Cabal files of all packages. Bazel takes care of only fetching the repositories that are required. However, as you point out, Bazel can't see the full dependency graph up front, but has to discover it layer by layer.
- Something that has proven very useful and sometimes necessary in Hazel, is the ability to override builds of individual packages, either by defining a different version/git-repo, or by providing a patch, or by providing a full custom build. Version overrides are a simple use-case. But, sometimes packages need to be patched to work under Hazel. I'd hope that most those patches would not be necessary under Cabal. However, some packages need patching due to Bazel's directory layout. Paths modules and embedded data files come to mind, e.g. in [`wai-app-static`](https://github.com/tweag/rules_haskell/blob/30621d196f45520e5decc2183d5974e692fdfbb8/hazel/tools/wai.patch). I'm not sure to what extent these can be solved with Cabal parameters rather than patches to the source.

**Comment by mboes** [comment]
> Bazel takes care of only fetching the repositories that are required. However, as you point out, Bazel can't see the full dependency graph up front, but has to discover it layer by layer.

There is an interesting pro and a con to this approach:

* **pro** The user doesn't need to write down in a unique monolithic list the root set of all direct dependencies it has on the snapshot, like in rules_jvm_external, because Hazel lazily maps in the entire dependency graph of the snapshot.
* **con** since the lazyness can only be achieved with external repositories, we need to pollute the global namespace with package names, which in the current state of things leads to the single-snapshot, single-package-version constraints in the entire workspace.

rules_jvm_external flips it around: it requires a root set of dependencies, then (eagerly) computes the dependency graph of the transitive closure. But it gains the multiple-snapshot, multiple-package-version flexibility. And in theory Bazel can fetch more efficiently since it's not discovering the dependency graph in layers.

**Comment by mboes** [comment]
> However, some packages need patching due to Bazel's directory layout. Paths modules and embedded data files come to mind

Urgh, data files. Cabal will generate `Paths_*` modules, which embed absolute paths. BUT, we're in luck. With the `--enable-relocatable` flag to `Setup.hs`, Cabal will actually avoid absolute paths in these generated modules. So we should be in the clear here, even achieving cache friendliness.
