### ISSUE TITLE
stack_install: let user apply source patches

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#902]
**Is your feature request related to a problem? Please describe.**
With Hazel some Hackage packages require small source patches to build under Bazel. E.g. to adjust file paths to embedded files or runtime data dependencies. See `wai-app-static` for example. The new `stack_install` does not allow users to apply source patches.

**Describe the solution you'd like**
`stack_install` should allow users to specify source patches. Ideally in a way similar to [`http_archive`](https://github.com/bazelbuild/bazel/blob/62e3df71ca74d493a48351fa36760fa5bd889322/tools/build_defs/repo/http.bzl#L56).

**Describe alternatives you've considered**
Users could fork the package repository and if `stack_install` allowed to override a package's source repository users could inject patches that way. For small patches this is usually too much overhead.

**Additional context**
Opening issue as suggested in https://github.com/tweag/rules_haskell/pull/887#discussion_r287280815.

**Comment by mboes** [comment]
A simple but powerful way to achieve this would be to add a `vendored_packages` attribute that lets users include source checkouts local to the repo, or in a `http_archive`. Users can patch that source as much as they want, or include a `BUILD.bazel`, which would override any default target definition.

**Comment by aherrmann** [comment]
`vendored_packages` sounds like a very good solution to this problem.

**Comment by hanshoglund** [comment]
Looks like this is covered by #1060. Shall we close?
