### ISSUE TITLE
linkopts in haskell_import grow exponentially

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#917]
**Describe the bug**
The `haskell_import` rule constructs the `HaskellImportHack` provider with a field to carry the `linkopts` field meant for `CcInfo`. It does so by combining the `HaskellImportHack.linkopts` of all its dependencies. This causes `linkopts` to grow exponentially. This is generally wasteful, and quickly exceeds the maximum command line length (tested on Linux) if those `linkopts` are passed to a tool like `gcc` (e.g. in #913).

**To Reproduce**
Build a Haskell target, e.g. `//tests/binary-simpl`, and observe the toolchain libararies' `linkopts`. E.g. adding the following to `haskell_import_impl`
```
    print(id, "len(linkopts)", len(import_info.linkopts))
```
produces the following output (formatted for readability)
```
ghc-prim-0.5.3            len(linkopts) 83
rts                       len(linkopts) 83
integer-gmp-1.0.2.0       len(linkopts) 86
array-0.5.3.0             len(linkopts) 252
base-4.12.0.0             len(linkopts) 252
filepath-1.4.2.1          len(linkopts) 252
ghc-boot-th-8.6.5         len(linkopts) 252
transformers-0.5.6.2      len(linkopts) 252
xhtml-3000.2.2.1          len(linkopts) 252
terminfo-0.4.1.2          len(linkopts) 255
ghc-heap-8.6.5            len(linkopts) 418
deepseq-1.4.4.0           len(linkopts) 504
mtl-2.2.2                 len(linkopts) 504
stm-2.5.0.0               len(linkopts) 504
time-1.8.0.2              len(linkopts) 756
pretty-1.1.3.6            len(linkopts) 839
bytestring-0.10.8.2       len(linkopts) 925
containers-0.6.0.1        len(linkopts) 1091
ghc-compact-0.1.0.0       len(linkopts) 1260
template-haskell-2.14.0.0 len(linkopts) 1343
unix-2.7.2.2              len(linkopts) 1937
binary-0.8.6.0            len(linkopts) 2520
directory-1.3.3.0         len(linkopts) 3197
text-1.2.3.1              len(linkopts) 4622
hpc-0.6.0.3               len(linkopts) 5548
process-1.6.5.0           len(linkopts) 6142
parsec-3.1.13.0           len(linkopts) 6303
ghc-boot-8.6.5            len(linkopts) 7398
haskeline-0.7.4.3         len(linkopts) 14807
ghci-8.6.5                len(linkopts) 17396
libiserv-8.6.3            len(linkopts) 24625
Cabal-2.4.0.1             len(linkopts) 30348
ghc-8.6.5                 len(linkopts) 50690
```

**Expected behavior**
`ld-options` should not grow more than linearly. Ideally, `linkopts` should only hold the `ld-options` of the current package being imported. The `linkopts` should only be combined later on using `merge_cc_infos`, so that Bazel can avoid unnecessarily duplicating `linkopts`.

**Environment**
 - OS name + version: openSUSE Tumbleweed 20190529
 - Bazel version: 0.24.0 provided by `shell.nix`
 - Version of the rules: 1672e2bff44ce7ef66cf638e7819215ffd9936b5

**Additional context**
As detailed in https://github.com/bazelbuild/bazel/issues/8129 we cannot directly produce a `CcInfo` in `haskell_import` as any toolchain dependencies would be built in the `host` configuration. As further detailed in https://github.com/bazelbuild/bazel/pull/5650 there is work in progress to allow to control the configuration of toolchain dependencies, but it is not available, yet. The recommended work around seems to be to define such targets separately from the toolchain and have all rules depend on them directly.

`rules_haskell` currently implements this with the separation of `haskell_import` and `haskell_toolchain_library`. However, this is still not fully satisfactory. Consider the following example:
```
haskell_toolchain_library(name = "base")
haskell_toolchain_library(name = "transformers")
haskell_library(name = "foo", deps = [":base", ":transformers"], ...)
```
Here, `base` and `transformers` will share common toolchain library dependencies, e.g. `rts`, however, as there is no functioning target providing `CcInfo` for `rts`, both `:base` and `:transformers` will still have to duplicate the corresponding `linkopts` (and other fields) internally.

It seems difficult to come up with an alternative implementation while maintaining the user interface. Here's a first attempt (which doesn't work):
- `haskell_import` will continue to return a provider like `HaskellImportHacked`.
- We add a (private) repository rule, say `make_toolchain_libraries`, that is called automatically by `haskell_repositories`, which defines unique global targets for all toolchain libraries. It does so by calling what is now `haskell_toolchain_library`. This would produce targets like `@io_tweag_rules_haskell_toolchain_libraries//:base`. These targets would produce the proper `CcInfo` and `HaskellInfo` providers, which don't manually duplicate `linkopts` and others, but instead use regular dependencies and `merge_cc_info`.
- We replace the user facing `haskell_toolchain_library` by a macro that just generates an `alias` to the global toolchain library targets.

Unfortunately, this doesn't work because `make_toolchain_libraries` wouldn't know which toolchain libraries are actually provided by the toolchain (especially in case of nixpkgs). Also, in order to know the dependencies of a toolchain library we need access to the toolchain's package db.

**Comment by mboes** [comment]
Closed by #917
