### ISSUE TITLE
Generate dedicated package configuration files for compilation and linking

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#926]
**Is your feature request related to a problem? Please describe.**
Currently we're passing flags for compile and link steps to GHC on the command-line. This has a few issues.
- Especially on Windows we can quickly exceed the maximum command-line length
- GHCi's loader (Template Haskell and REPL) has somewhat surprising behaviour wrt locating libraries specified via `-l` flags. Namely, it will not look for these libraries in directories specified via `-L` flags, but instead the directories have to be contained in the `(LD_)LIBRARY_PATH` environment variables. 

**Describe the solution you'd like**
Instead of passing these flags on the command-line we can generate dedicated package configuration files listing those dependencies. E.g.
```
extra-ghci-libraries: <libraries for TH/REPL>
extra-libraries: <libraries for linking>
library-dirs: <-L flags>
ld-options: <other flags, can also list static archives>
```
Additional benefit: The separate fields `extra-ghci-libraries` and `extra-libraries` allow to pass different libraries for GHCi's linker or final linking. This might be very useful for interaction with Cabal/Stack.

**Describe alternatives you've considered**
- Patching GHC to search libraries in `-L` flags. Does not address command-line length.
    Possibly related to https://gitlab.haskell.org/ghc/ghc/issues/1019
- Patching GHC to support response files. Not easy as it might involve argument handling in the RTS. See https://gitlab.haskell.org/ghc/ghc/issues/16476

**Comment by Profpatsch** [comment]
> Instead of passing these flags on the command-line we can generate dedicated package configuration files listing those dependencies. E.g.

Is that a feature of GHC that can read those files? If not, how do we pass these without moving them to the command line again?

**Comment by aherrmann** [comment]
> Is that a feature of GHC that can read those files?

Yes, specifically the binary package database representation as generated by `ghc-pkg recache`.

**Comment by aherrmann** [comment]
This is implemented for linking to the extent possible, see [here](https://github.com/tweag/rules_haskell/blob/182995f9ad0eeb076deaecbc1d6e2abe6bd2b8c4/haskell/private/actions/link.bzl#L131-L139). Efforts to implement this for compilation were thwarted by differences in how GHC loads library dependencies for template Haskell vs. plugins.

Additionally we use package environment files to avoid listing package dependencies on the command-line and exceeding length limits on Windows.
