### ISSUE TITLE
readthedocs is wrong at several points

### ISSUE THREAD

**Issue by ulysses4ever** [tweag/rules_haskell#938]
**Describe the bug**
[Readthedocs](https://rules-haskell.readthedocs.io/en/latest/haskell.html) says that you need to `cd tutorial` to build tutorial targets, but apparently you should not. Instead, you have to not just `bazel build //lin:booleans`, as Readthedocs suggests, but:
```
bazel build @io_tweag_rules_haskell_tutorial//lib:booleans
```
Then, Readthedocs doesn't mention `--host_platform` flag, which when omitted again breaks the build of tutorial targets.

**Expected behavior**
Readthedocs should mirror what is said in README.md which addresses both points.

**Environment**
 - OS name + version: Ubuntu 18.04
 - Bazel version: 0.24.0 (inside nix-shell)
 - Version of the rules: HEAD (55e910e)

**Comment by Profpatsch** [comment]
One *should* `cd` into the `tutorial` subdir again, as of https://github.com/tweag/rules_haskell/pull/947

The `--host-platform` is *only* needed on NixOS, we need to add a section to help out NixOS users.

**Comment by ulysses4ever** [comment]
@Profpatsch good to know, thanks! Feel free to close whenever.
