### ISSUE TITLE
Add transitive JARs of Java dependencies to CLASSPATH

### ISSUE THREAD

**Issue by Fuuzetsu** [tweag/rules_haskell#96]
https://github.com/tweag/rules_haskell/issues/80 introduced some interop with Java rules: if a Java provider is present, we add its `jar` to `CLASSPATH` during compilation. The right thing to do there however is to add _transitive_ `jar`s. This is blocked on an upstream bazel ticket (https://github.com/bazelbuild/bazel/issues/4384).

Until then, the user has to manually insert all the jars they require even if they are already present somewhere down the Java compilation chain.

**Comment by Profpatsch** [comment]
Is this still relevant?

**Comment by Fuuzetsu** [comment]
Well, I imagine it is. IIRC the issue was that if I depend on on some jar-provider X that depends on D1, D2 and D3, I have to also explicitly depend on D1, D2 and D3 instead of just on X. I don't see what would have changed. I think https://github.com/tweag/rules_haskell/issues/80 gives a little more info.

**Comment by mboes** [comment]
I think the status quo is fine. There's a [post on Bazel's blog](https://blog.bazel.build/2017/06/28/sjd-unused_deps.html) explaining that it's better if all Java dependencies are direct. We don't need everything in the `CLASSPATH`, just the stuff that is actually imported by code, but those should be in the direct dependencies.
