### ISSUE TITLE
Unexpected "Loaded package environment" messages during build

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#969]
**Describe the bug**

During a build, `bazel` is outputting many debug messages (i.e. the "Loaded package env...."):

```
INFO: From HaskellBuildLibrary //tests/package-id-clash-binary/a:foo:
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/package-id-clash-binary/a/compile-package_env-foo
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/package-id-clash-binary/a/compile-package_env-foo
INFO: From HaskellBuildLibrary //tests/library-with-sysdeps:library-with-sysdeps:
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/compile-package_env-library-with-sysdeps
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/compile-package_env-library-with-sysdeps
INFO: From HaskellBuildLibrary @haskell_package_repository_dummy//:library-with-cbits:
Loaded package environment from bazel-out/k8-fastbuild/bin/external/haskell_package_repository_dummy/compile-package_env-library-with-cbits
Loaded package environment from bazel-out/k8-fastbuild/bin/external/haskell_package_repository_dummy/compile-package_env-library-with-cbits
INFO: From HaskellLinkDynamicLibrary tests/package-id-clash-binary/a/libHStestsZSpackage-id-clash-binaryZSaZSfoo-ghc8.6.5.so:
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/package-id-clash-binary/a/link-package_env-foo
INFO: From HaskellBuildLibrary //tests/version-macros:versioned-lib:
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/version-macros/compile-package_env-versioned-lib
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/version-macros/compile-package_env-versioned-lib
INFO: From HaskellLinkDynamicLibrary tests/library-with-sysdeps/libHStestsZSlibrary-with-sysdepsZSlibrary-with-sysdeps-ghc8.6.5.so:
Loaded package environment from bazel-out/k8-fastbuild/bin/tests/library-with-sysdeps/link-package_env-library-with-sysdeps
```

This is annoying,

**To Reproduce**

`bazel test //...` in master.

**Expected behavior**

Less output.

**Additional context**

A quick and dirty solution is to redirect ghc output:

```
diff --git a/haskell/toolchain.bzl b/haskell/toolchain.bzl
index 2a453b8..af87ac4 100644
--- a/haskell/toolchain.bzl
+++ b/haskell/toolchain.bzl
@@ -80,7 +80,7 @@ while IFS= read -r line; do compile_flags+=("$line"); done < %s
 while IFS= read -r line; do extra_args+=("$line"); done < %s
 while IFS= read -r line; do param_file_args+=("$line"); done < %s
 
-"${compile_flags[@]}" "${extra_args[@]}" ${param_file_args+"${param_file_args[@]}"}
+"${compile_flags[@]}" "${extra_args[@]}" ${param_file_args+"${param_file_args[@]}"} 2> /dev/null
 """ % (compile_flags_file.path, extra_args_file.path, params_file_src)
 
     ghc_wrapper_name = "ghc_wrapper_%s_%s" % (hs.name, mnemonic)
```

But that's not an acceptable solution as it also disabled ghc errors in case of failure.

I did a quick research in ghc manual but I did not find any flag which control this output.

**Comment by aherrmann** [comment]
Relevant issue: https://gitlab.haskell.org/ghc/ghc/issues/15145
and commit: https://gitlab.haskell.org/ghc/ghc/commit/00049e2dce93b1e468c3fde3287371eb988aafdc

**Comment by guibou** [comment]
I'm unable to find a ghc flag to disable that. I opened an upstream ticket: https://gitlab.haskell.org/ghc/ghc/issues/16879

**Comment by mboes** [comment]
These spurious messages at every build of every target are quite a cost. @aherrmann how do you avoid them in the DAML repo?

**Comment by mboes** [comment]
It doesn't appear to me that environment files are really meant as replacements for response files. I think we should instead work on proper response file support in GHC, i.e. properly fix https://gitlab.haskell.org/ghc/ghc/issues/8596, which was closed a little too hastily by https://phabricator.haskell.org/D1158. Which as Phyx notes in a comment there, does not add response files to GHC itself.

**Comment by aherrmann** [comment]
> how do you avoid them in the DAML repo?

@mboes we don't avoid them in the DAML repo. So, we have the same problem there.

As I understand https://gitlab.haskell.org/ghc/ghc/issues/8596 the issue there was a too long command line to `gcc`, so D1158 seems like the right solution for that particular issue. There is also a dedicated open issue for response files to GHC itself, which would definitely be better for our use-case than package environment files: https://gitlab.haskell.org/ghc/ghc/issues/16476

**Comment by ulysses4ever** [comment]
FTR, the change muting the message with `-v0` was merged. I guess, 8.10 is the venue where one could get it.

**Comment by mboes** [comment]
These are gone now, since #991.
