### ISSUE TITLE
Startup script: have both bindist and nixpkgs in the workspace

### ISSUE THREAD

**Issue by aspiwack** [tweag/rules_haskell#971]
The onboarding process is harder than it need be. In particular, it is finicky to make the nixpkgs version of the toolchain works. As the startup script only builds a workspace with the ghc_bindist option.

It would presumably be better, if the generated workspace had both the ghc_bindist toolchain and the nixpkgs toolchain registered. Together with the instruction to switch between these using a platform flag (which is currently necessary for the nixpkgs toolchain anyway, so it wouldn't be much of a change for the end user, it simply saves setup time).

**Comment by Profpatsch** [comment]
Duplicate of https://github.com/tweag/rules_haskell/issues/784 I think

**Comment by aspiwack** [comment]
#784  seems to be suggesting a different solution to the same problem. Feel free to merge the two issues as you feel like.

**Comment by Profpatsch** [comment]
@aspiwack Do you think autodiscovery is a good idea?

**Comment by aspiwack** [comment]
No idea. What does it entail?
