### ISSUE TITLE
Add stack_snapshot to start script

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#978]
**Is your feature request related to a problem? Please describe.**

Most users most of the time will need a third-party dependency hosted on Hackage. The preferred way to build those is using `stack_snapshot` and `haskell_cabal_library`. It is not obvious to the user that this is so just by running the `start` script alone.

**Describe the solution you'd like**

Since the above is the common case, we should include a dummy call to `stack_snapshot` in the `start` script. It could expose just `base` using that rule, even if in the case of `base`, use of this workspace rule is not strictly necessary.

One downside to doing this is that we'll be making Bazel projects depend on Stack by default. I don't think this is too onerous a dependency.

**Comment by smelc** [comment]
An ambitious way to help users would be to make `start` generate most of the boilerplate.

A minimal way to do that would be to:

- Look for `stack.yaml` to infer `stack_snapshot`
- Look for `*.cabal` files to infer `haskell_cabal_*`
- Crawl subdirectories, to infer mimimal `BUILD.bazel` files for splitting the project bazel-package wise

If we don't invest too much in handling cabal subtleties, such a tool would have a good `output / effort` ratio (given that we appropriately advertise it's a helper tool, not an automatic translator..) and we could test its coverage easily by testing against public packages.

**Comment by aherrmann** [comment]
I think what @mboes had in mind here was much simpler. 

> include a dummy call to `stack_snapshot` in the `start` script

We can make this a bit more featureful and include a dependency on a tool like `alex` (showcasing `haskell_cabal_binary`) and a C library like `zlib` just to demonstrate common use-cases, and to avoid people getting stuck early on.

---

The tool you're proposing, is more of a `stack2bazel` tool than a `start` script, I think.

**Comment by smelc** [comment]
> I think what @mboes had in mind here was much simpler.

Yes of course, my intent is not to do `stack2bazel` for this task; I wanted to highlight a more ambitious way to make `rules_haskell` easier for newcomers :smiley:

**Comment by mboes** [comment]
I think @aherrmann's suggested examples are great. Let's go for that.

**Comment by smelc** [comment]
> I think @aherrmann's suggested examples are great. Let's go for that.

Implemented @aherrmann's examples:

- Introduced use of `alex` in `start` in 9e6943d
- Introduced use of `zlib` in `start` in e4cd57d.
