### ISSUE TITLE
Custom snapshots in stack_snapshot

### ISSUE THREAD

**Issue by aspiwack** [tweag/rules_haskell#984]
I'd like for stack snapshot to be extensible:

- it is frequent that some dependencies in a stackage snapshot is missing or you need a specific version.
- As far as I can tell, writing Haskell dependencies which are not in the stackage snapshot is pretty painful currently.

What I'm proposing is to make it possible, for `stack_snapshot` to take a custom `snapshot.yaml` (in the stack syntax) rather than a globally named snapshot. This would still let stack do all the dependency solving, with all the convenience and simplicity that it buys us.

It sounds easy enough in principle. But I'm not sure what tools Bazel gives me to do this. So this is very much a design conversation.

- I think that my preferred way would be to make the `snapshot` attribute be either a string or a label, and call something like `--resolver ($location snapshot)` when it is a label. But I don't know if Bazel lets me distinguish between the two.
- The other solution which I can think of at the moment is to have two attributes, one for global snapshot, and one for local snapshots, the global one is a string, the local one is a label, we disambiguate depending on which is set. This looks more straightforward, but feels kind of clunky.

In either case, the label would refer to some `local_stack_snapshot` target, which we would need to add to pull the custom snapshot in scope.

What do you guys think?

PS: I did check that you could pass a custom snapshot in `stack --resolver <snapshot>`.

**Comment by mboes** [comment]
Custom snapshots would be a welcome addition, but note that `stack_snapshot` already supports the equivalent of extra-deps functionality, as noted in the API documentation. So you can add dependencies that are not in the snapshot.

**Comment by aspiwack** [comment]
Ah, indeed, I missed it. But it can only handle hackage dependencies, right, no git repository or any such thing?

**Comment by mboes** [comment]
That's right. Hence why supporting custom snapshots is still useful.

**Comment by aspiwack** [comment]
There does not appear to be a way to build an attribute with a type like string-or-label.

Is there any option that I missed, or do we need to duplicate the `snapshot` attribute?

**Comment by aspiwack** [comment]
Also, I'm operating under the assumption that I need to be backwards compatible, but just to be sure: do we have a release with `stack_snapshot` yet?

**Comment by mboes** [comment]
You could have `snapshot` and `snapshot_file`. However, labels are very under powered and are quasi strings in workspace rules (unlike in build rules). So maybe you can get away with using a string typed attribute to either locate a file (using label syntax) or name a snapshot.

**Comment by mboes** [comment]
>  do we have a release with stack_snapshot yet?

We don't.

**Comment by aspiwack** [comment]
Ah, right. `stack_snapshot` is a workspace rule, so it allowed to slurp some file.

We could detect strings which start with, say `//` and use these to mean “a local file”. Does that sound reasonable? Is there any risk of conflict with the stackage syntax?

**Comment by mboes** [comment]
It's doable, but possibly in bad taste. Separate mutually exclusive
attributes looks semantically cleaner. Another idea for naming: `snapshot`
and `local_snapshot`.

**Comment by aspiwack** [comment]
(I would have gone for `local_snapshot`, too: seems consistent with the rest of the names)

I think it may not be easy to play that game anyway: because we would have to declare the fake-label as a dependency, for cache invalidation. And it's not clear to me how to do that with the Bazel API (I'm still a beginner, so I might have missed something).

So if you think that having two attributes (which is really easy: the hardest part will be to check that exactly one of them is set), then I can go for it.

**Comment by aherrmann** [comment]
There is precedent for two separate, mutually exclusive attributes. E.g. [`http_archive`](https://github.com/bazelbuild/bazel/blob/fe28bb7ffef7b7a93799be6c1f9da3fdf7223eb1/tools/build_defs/repo/http.bzl#L55-L56) has `build_file` and `build_file_content`. I'm in favor of following that convention with `snapshot` and `local_snapshot`.
