### ISSUE TITLE
I wish I could invoke my GHC plugins with different arguments from different targets

### ISSUE THREAD

**Issue by peddie** [tweag/rules_haskell#996]
**Is your feature request related to a problem? Please describe.**

I've got a GHC plugin and am using the [`ghc_plugin`](https://api.haskell.build/haskell/plugins.html) target to handle it.  This target accepts plugin arguments that get passed to my plugin as command-line arguments.  Unfortunately there doesn't seem to be a way to pass different command-line arguments to the plugin from different library targets that I would like to be built using the plugin, so I end up creating lots of plugin targets for the same plugin with different arguments and having my library targets depend on the appropriate one.

**Describe the solution you'd like**

One solution that seems straightforward to me would be for `haskell_binary` and `haskell_library` targets (and perhaps others?) to have a `plugin_args` argument, which, if a plugin is declared in the `plugins` field, declares the arguments that will be passed to the GHC plugin.  I don't know how to handle multiple plugins syntactically.

**Describe alternatives you've considered**

I'm using the workaround described at the beginning of this report, which involves defining extra plugin targets.  This works but results in ugly code, because every parameter I might want to change means I have to produce a new plugin target to go with it.

**Additional context**

I can't think of any additional information to include, but please ask if anything is unclear.

**Comment by aherrmann** [comment]
@peddie Thank you for the feature request.

Plugin options are passed using the `-fplugin-opt` GHC flag. So, another workaround that doesn't require creating many `ghc_plugin` targets could be to set the plugin options in the `haskell_library/binary`'s `compiler_flags` attribute. See [implementation](https://github.com/tweag/rules_haskell/blob/33acc8061f5c92e0b3f333ae868115ffbccf795c/haskell/private/actions/compile.bzl#L298-L301). E.g. `compiler_flags = ["-fplugin-opt", "Plugin.Module:plugin_arg"]`.

> One solution that seems straightforward to me would be [...] to have a `plugin_args` argument, which, if a plugin is declared in the `plugins` field, declares the arguments that will be passed to the GHC plugin. I don't know how to handle multiple plugins syntactically.

Only supporting this for a single plugin seems unfortunate. Maybe this could be solved with a `dict` attribute mapping plugins to their flags. Unfortunately, Bazel only provides [`label_keyed_string_dict`](https://docs.bazel.build/versions/master/skylark/lib/attr.html#label_keyed_string_dict) and not `label_keyed_string_list_dict`, which we would probably want here.

**Comment by ghorn** [comment]
Sounds like rules_haskell already fully supports this use case through compiler_opts. I don't see a reason to expand the API.

**Comment by peddie** [comment]
@ghorn I agree that the `compiler_flags` workaround is better than my one.  But it seems to me like the `ghc_plugin` API is incomplete without a direct way to pass arguments; otherwise why not just pass `-fplugin` and my source plugin by hand as well, and avoid `ghc_plugin` entirely?

**Comment by peddie** [comment]
@aherrmann 

> Only supporting this for a single plugin seems unfortunate. Maybe this could be solved with a `dict` attribute mapping plugins to their flags. Unfortunately, Bazel only provides [`label_keyed_string_dict`](https://docs.bazel.build/versions/master/skylark/lib/attr.html#label_keyed_string_dict) and not `label_keyed_string_list_dict`, which we would probably want here.

Some kind of map dictionary sounds like the right thing!  Unfortunately I don't have any good suggestions about getting around the Bazel limitations here.
